import { expect, test } from '@playwright/test'
import { SAVE_KEY_V10 } from '../../src/domain/save-v10'

test('正常新档从江湖战利品完成首笔城市收入，剧情和账簿重载保留', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 960 })
  await page.goto('/')
  await page.getByRole('button', { name: '新建游戏' }).click()
  await page.getByLabel('玩家姓名').fill('城中少侠')
  await page.getByLabel('玩家姓名').press('Enter')
  await page.getByTestId('world-world_01').click()
  await page.getByTestId('start-crossing').click()
  await page.getByTestId('world-section-city').click()
  await expect(page.getByTestId('city-story')).toContainText('旧契归来')
  await page.screenshot({ path: testInfo.outputPath('city-story-desktop.png'), animations: 'disabled' })
  await page.getByRole('button', { name: '接过钥匙' }).click()
  await expect(page.getByTestId('city-story')).toContainText('江湖有宝')
  await page.reload()
  await page.getByRole('button', { name: '继续游戏' }).click()
  await page.evaluate(() => window.__EGG_JIANGHU__.setJianghuSection('city'))
  await expect(page.getByTestId('city-story')).toContainText('江湖有宝')
  await page.getByRole('button', { name: '看看如何经营' }).click()
  await page.getByRole('button', { name: '开始打理古玩店' }).click()
  await expect(page.getByTestId('city-story')).toHaveCount(0)
  await page.getByRole('button', { name: '去江湖寻货' }).click()
  await page.getByTestId('stage-1').click()
  // 仅加速游戏时钟；不添加装备、现金、等级或通关结果，战利品来自真实战斗。
  const lootCount = await page.evaluate(() => {
    const api = window.__EGG_JIANGHU__
    for (let i = 0; i < 200 && api.getState().inventory.length === 0; i++) api.advanceCombat(100)
    return api.getState().inventory.length
  })
  expect(lootCount).toBeGreaterThan(0)
  await page.locator('[data-action="stop-combat"]').click()
  await page.getByTestId('world-section-city').click()
  await page.locator('[data-action="city-stock"]').first().click()
  await expect(page.locator('[aria-label="货架"] .city-goods-row')).toHaveCount(1)
  await page.locator('[data-action="city-hire-open"]').first().click()
  await page.getByRole('button', { name: '去势力招募侠客' }).click()
  await expect(page.getByTestId('faction-page-title')).toBeVisible()
  await page.getByTestId('tab-formation').click()
  await page.locator('[data-action="formation-clear"]').click()
  await page.getByTestId('tab-idle').click()
  await page.getByTestId('world-section-city').click()
  await page.locator('[data-action="city-hire"][data-hero-id="hero_player"]').click()
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 960 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.locator('.city-shop-head').scrollIntoViewIfNeeded()
    await page.screenshot({ path: testInfo.outputPath(`city-business-${width}.png`), animations: 'disabled' })
  }
  const copper = await page.evaluate(() => window.__EGG_JIANGHU__.getState().worldCurrency)
  await page.evaluate(() => window.__EGG_JIANGHU__.advanceRuntime(120_000))
  const sold = await page.evaluate(() => window.__EGG_JIANGHU__.getState())
  expect(sold.city.company.cash).toBeGreaterThan(0)
  expect(sold.city.shop.soldCount).toBe(1)
  expect(sold.city.company.currentFinance.销售收入).toBe(sold.city.company.cash)
  expect(sold.worldCurrency).toEqual(copper)
  await expect(page.getByTestId('city-guide')).toContainText('第一笔生意已成')
  await page.locator('.city-receipts').scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('city-first-sale-mobile.png'), animations: 'disabled' })
  await page.setViewportSize({ width: 1440, height: 960 })
  await page.locator('.city-guide').scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('city-first-sale-desktop.png'), animations: 'disabled' })
  await page.reload()
  await page.getByRole('button', { name: '继续游戏' }).click()
  await page.evaluate(() => window.__EGG_JIANGHU__.setJianghuSection('city'))
  const loaded = await page.evaluate(() => window.__EGG_JIANGHU__.getState())
  expect(loaded.version).toBe(20)
  expect(loaded.city.company.cash).toBe(sold.city.company.cash)
  expect(loaded.city.shop.stock).toHaveLength(0)
  expect(loaded.city.shop.introStep).toBe(3)
  expect(loaded.city.shop.receipts).toEqual(sold.city.shop.receipts)
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!).version, SAVE_KEY_V10)).toBe(20)
  expect(errors).toEqual([])
})

test('v18 旧档保留但不能继续，新建和删档只操作 v19', async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.setItem('egg-jianghu-2-save-v18', '{"version":18}'))
  await page.reload()
  await expect(page.getByRole('button', { name: '继续游戏' })).toBeDisabled()
  await expect(page.getByRole('alert')).toContainText('旧档保留但不可继续')
  await page.getByRole('button', { name: '新建游戏' }).click()
  await page.getByLabel('玩家姓名').fill('新城主')
  await page.getByLabel('玩家姓名').press('Enter')
  expect(await page.evaluate(() => localStorage.getItem('egg-jianghu-2-save-v18'))).toBe('{"version":18}')
  await page.locator('[data-action="request-reset-save"]').click()
  await page.locator('[data-action="confirm-reset-save"]').click()
  expect(await page.evaluate(() => localStorage.getItem('egg-jianghu-2-save-v18'))).toBe('{"version":18}')
  expect(await page.evaluate(key => localStorage.getItem(key), SAVE_KEY_V10)).toBeNull()
})
