import { expect, test } from '@playwright/test'

for (const width of [1440, 390]) {
  test(`阶段定位、原门槛兑换及筛选 ${width}`, async ({ page }, testInfo) => {
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.setViewportSize({ width, height: 960 })
    await page.goto('/')
    await page.getByRole('button', { name: '新建游戏' }).click()
    await page.getByLabel('玩家姓名').fill('阶段核验')
    await page.getByLabel('玩家姓名').press('Enter')
    await page.evaluate(() => window.__EGG_JIANGHU__.setJianghuSection('factions'))
    const card = page.getByTestId('faction-recruitment-hero-5')
    await card.scrollIntoViewIfNeeded()
    await expect(card).toContainText('前期过渡')
    await expect(card).toContainText('第1章可得')
    await expect(card.getByRole('button')).toBeDisabled()
    await card.getByText('培养与替换建议').click()
    await page.evaluate(() => window.__EGG_JIANGHU__.grantWorldCurrency('world_01', 1_600_000))
    await expect(card.locator('details')).toHaveAttribute('open', '')
    await expect(card.getByRole('button')).toBeDisabled()
    await page.evaluate(() => window.__EGG_JIANGHU__.grantWorldReputation('world_01', 1800))
    await expect(card.getByRole('button', { name: '邀请入队' })).toBeEnabled()
    await card.scrollIntoViewIfNeeded()
    await page.screenshot({ animations: 'disabled', path: testInfo.outputPath(`recruitment-${width}.png`) })
    await card.getByRole('button', { name: '邀请入队' }).click()
    expect(await page.evaluate(() => window.__EGG_JIANGHU__.getState().worldCurrency.world_01)).toBe(0)
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await page.evaluate(() => window.__EGG_JIANGHU__.grantWorldCurrency('world_01', 30_000))
    await page.getByTestId('faction-recruitment-hero-4').getByRole('button', { name: '邀请入队' }).click()
    await page.getByTestId('tab-heroes').click()
    await page.locator('[data-filter-kind="lifecycle"][data-filter-value="transition"]').click()
    for (const button of await page.locator('.lifecycle-filters .fchip').all()) {
      expect(await button.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
    }
    await page.locator('.lifecycle-filters').scrollIntoViewIfNeeded()
    await page.screenshot({ animations: 'disabled', path: testInfo.outputPath(`filters-${width}.png`) })
    await expect(page.locator('.roster-row')).toHaveCount(1)
    await page.getByTestId('hero-hero_orig_5').click()
    const detail = page.getByTestId('hero-lifecycle-hero_orig_5')
    await expect(detail).toContainText('中期重点评估换下')
    await detail.scrollIntoViewIfNeeded()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    const radar = await page.locator('.hb-radar').boundingBox()
    const aptitudes = await page.locator('.hb-aptlist').boundingBox()
    expect(radar!.x + radar!.width <= aptitudes!.x + 1 || radar!.y + radar!.height <= aptitudes!.y + 1).toBe(true)
    await page.screenshot({ animations: 'disabled', path: testInfo.outputPath(`hero-${width}.png`) })
    await page.locator('[data-filter-kind="lifecycle"][data-filter-value="utility"]').click()
    await expect(page.locator('.roster-row')).toHaveCount(1)
    await page.getByTestId('hero-hero_orig_4').click()
    await expect(page.getByTestId('hero-lifecycle-hero_orig_4')).toContainText('商业4 · 商店员工')
    await page.locator('[data-filter-kind="lifecycle"][data-filter-value="welfare"]').click()
    await expect(page.locator('.roster-row')).toHaveCount(0)
    await page.locator('[data-action="locate-hero"]').click()
    await expect(page.getByTestId('hero-hero_orig_5')).toBeVisible()
    await page.reload()
    await page.getByRole('button', { name: '继续游戏' }).click()
    expect(await page.evaluate(() => window.__EGG_JIANGHU__.getState().heroes.hero_orig_5.recruited)).toBe(true)
    expect(errors).toEqual([])
  })
}
