import { openPanel } from './ink-helpers'
import { expect, test } from '@playwright/test'

for (const width of [1440, 390]) {
  test(`玩家界面不展示设计分析且保留原门槛兑换 ${width}`, async ({ page }, testInfo) => {
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.setViewportSize({ width, height: 960 })
    await page.goto('/')
    await page.getByRole('button', { name: '新建游戏' }).click()
    await page.getByLabel('玩家姓名').fill('阶段核验')
    await page.getByLabel('玩家姓名').press('Enter')
    await page.evaluate(() => window.__EGG_JIANGHU__.setJianghuSection('factions'))
    await page.locator('.ink-faction-tabs [data-faction-panel="recruit"]').click()
    const card = page.getByTestId('faction-recruitment-hero-5')
    await card.scrollIntoViewIfNeeded()
    await expect(card).not.toContainText('前期过渡')
    await expect(card).not.toContainText('第1章可得')
    await expect(card.getByRole('button')).toBeDisabled()
    await page.evaluate(() => window.__EGG_JIANGHU__.grantWorldCurrency('world_01', 1_600_000))
    await expect(card.getByRole('button')).toBeDisabled()
    await page.evaluate(() => window.__EGG_JIANGHU__.grantWorldReputation('world_01', 1800))
    await expect(card.getByRole('button', { name: '邀请入队' })).toBeEnabled()
    await card.scrollIntoViewIfNeeded()
    await page.screenshot({ animations: 'disabled', path: testInfo.outputPath(`recruitment-${width}.png`) })
    await card.getByRole('button', { name: '邀请入队' }).click()
    expect(await page.evaluate(() => window.__EGG_JIANGHU__.getState().worldCurrency.world_01)).toBe(0)
    await expect(page.getByRole('dialog')).toHaveCount(1)
    await expect(page.getByTestId('ink-panel')).toBeVisible()
    await page.evaluate(() => window.__EGG_JIANGHU__.grantWorldCurrency('world_01', 30_000))
    await page.locator('.ink-faction-tabs [data-faction-panel="recruit"]').click()
    await page.getByTestId('faction-recruitment-hero-4').getByRole('button', { name: '邀请入队' }).click()
    await openPanel(page, 'heroes')
    await page.getByTestId('hero-hero_orig_5').click()
    const detail = page.locator('.hero-basic')
    await expect(page.locator('.heroes-page')).not.toContainText(/章节培养|第1章可得|前期过渡|培养与替换建议|已有赵云时|中期重点评估/)
    await detail.scrollIntoViewIfNeeded()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    const radar = await page.locator('.hb-radar').boundingBox()
    const aptitudes = await page.locator('.hb-aptlist').boundingBox()
    expect(radar!.x + radar!.width <= aptitudes!.x + 1 || radar!.y + radar!.height <= aptitudes!.y + 1).toBe(true)
    await page.screenshot({ animations: 'disabled', path: testInfo.outputPath(`hero-${width}.png`) })
    await page.reload()
    await page.getByRole('button', { name: '继续游戏' }).click()
    expect(await page.evaluate(() => window.__EGG_JIANGHU__.getState().heroes.hero_orig_5.recruited)).toBe(true)
    expect(errors).toEqual([])
  })
}
