import { openPanel } from './ink-helpers'
import { expect, test } from '@playwright/test'
import { SAVE_KEY_V10 } from '../../src/domain/save-v10'

const start = Date.parse('2026-09-11T08:00:00+08:00')
const hour = 3_600_000

test('挂机退出后补蛋蛋，重进不重复；钱包在桌面和手机可用', async ({ page, context }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.clock.setFixedTime(start)
  await page.goto('/')
  await page.getByRole('button', { name: '新建游戏' }).click()
  await page.getByLabel('玩家姓名').fill('蛋蛋少侠')
  await page.getByLabel('玩家姓名').press('Enter')
  await expect(page.getByTestId('voucher-balance')).toHaveText('0')
  await page.evaluate(() => window.__EGG_JIANGHU__.startStage('world_01', 1, 'guard', 1))
  await page.clock.setFixedTime(start + 6 * 60_000)
  await expect(page.getByTestId('voucher-balance')).toHaveText('10')
  // 关闭实际页面，新页面仅改变日期；不模拟八小时战斗。
  await page.close()
  const next = await context.newPage()
  next.on('pageerror', e => errors.push(e.message))
  await next.clock.setFixedTime(start + 8 * hour)
  await next.goto('/')
  await next.getByRole('button', { name: '继续游戏' }).click()
  await expect(next.getByTestId('voucher-balance')).toHaveText('700')
  await next.setViewportSize({ width: 1440, height: 960 })
  await next.getByRole('button', { name: '关闭册页', exact: true }).click()
  const navBefore = await next.getByTestId('tab-idle').boundingBox()
  await next.getByTestId('voucher-balance').hover()
  await expect(next.locator('#voucher-details')).toBeVisible()
  expect((await next.getByTestId('tab-idle').boundingBox())!.y).toBe(navBefore!.y)
  await next.locator('#voucher-details').hover()
  await expect(next.locator('#voucher-details')).toBeVisible()
  await next.mouse.move(1100, 800)
  await expect(next.locator('#voucher-details')).toHaveCount(0)
  await next.locator('[data-action="toggle-voucher-details"]').click()
  await next.mouse.move(1100, 800)
  await expect(next.getByTestId('offline-voucher-reward')).toContainText('+690')
  for (const width of [1440, 390]) {
    await next.setViewportSize({ width, height: 960 })
    const bounds = await next.locator('#voucher-details').boundingBox()
    expect(bounds).not.toBeNull()
    expect(bounds!.x).toBeGreaterThanOrEqual(0)
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(width)
    await next.screenshot({ path: testInfo.outputPath(`vouchers-${width}.png`) })
  }
  await next.keyboard.press('Escape')
  await expect(next.locator('#voucher-details')).toHaveCount(0)
  await next.getByRole('button', { name: '查看蛋蛋说明' }).dispatchEvent('click')
  await expect(next.locator('#voucher-details')).toBeVisible()
  await openPanel(next, 'idle')
  await expect(next.locator('#voucher-details')).toHaveCount(0)
  await next.getByRole('button', { name: '查看蛋蛋说明' }).dispatchEvent('click')
  await expect(next.locator('#voucher-details')).toBeVisible()
  await next.getByRole('button', { name: '查看蛋蛋说明' }).dispatchEvent('click')
  await expect(next.locator('#voucher-details')).toHaveCount(0)
  await next.reload()
  await next.getByRole('button', { name: '继续游戏' }).click()
  await expect(next.getByTestId('voucher-balance')).toHaveText('700')
  await next.evaluate(() => window.__EGG_JIANGHU__.startStage('world_01', 1, 'roam', 2))
  await next.locator('[data-action="stop-combat"]').click()
  expect(await next.evaluate(key => JSON.parse(localStorage.getItem(key)!).idleVouchers.activeMode, SAVE_KEY_V10)).toBeNull()
  await next.clock.setFixedTime(start + 32 * hour)
  await next.reload()
  await next.getByRole('button', { name: '继续游戏' }).click()
  await expect(next.getByTestId('voucher-balance')).toHaveText('700')
  expect(errors).toEqual([])
})
