import { expect, test } from '@playwright/test'
import { SAVE_KEY_V10 } from '../../src/domain/save-v10'

const now = Date.parse('2026-09-11T08:00:00+08:00')
test('蛋蛋购卡、阵容加成、续期持久化和到期在桌面手机可用', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.clock.setFixedTime(now)
  await page.goto('/')
  await page.getByRole('button', { name: '新建游戏' }).click()
  await page.getByLabel('玩家姓名').fill('特权少侠')
  await page.getByLabel('玩家姓名').press('Enter')
  await page.getByTestId('tab-shop').click()
  await page.locator('[data-action="shop-section"][data-section="premium"]').click()
  await expect(page.getByTestId('shop-page')).toContainText('收益特权')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('[data-card-id="monthly"]')).toBeDisabled()
  await page.keyboard.press('Escape')
  // 测试存档注入预算，不给正式游戏增加免费蛋蛋入口。
  const data = await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), SAVE_KEY_V10)
  data.idleVouchers.balance = 10_000
  await page.goto('about:blank')
  await page.addInitScript(({ key, data }) => {
    if (!sessionStorage.getItem('premium-test-funded')) {
      localStorage.setItem(key, JSON.stringify(data))
      sessionStorage.setItem('premium-test-funded', '1')
    }
  }, { key: SAVE_KEY_V10, data })
  await page.goto('/')
  await page.getByRole('button', { name: '继续游戏' }).click()
  await page.setViewportSize({ width: 1440, height: 960 })
  await page.getByTestId('tab-shop').click()
  await page.locator('[data-action="shop-section"][data-section="premium"]').click()
  for (const id of ['monthly', 'treasure', 'training']) await page.locator(`[data-card-id="${id}"]`).click()
  await expect(page.getByTestId('voucher-balance')).toHaveText('5,400')
  await expect(page.getByTestId('premium-totals')).toContainText('1.13')
  await page.locator('[data-card-id="treasure"]').click()
  await expect(page.getByTestId('voucher-balance')).toHaveText('4,600')
  await expect(page.getByTestId('premium-card-treasure')).toContainText('2026/09/25')
  await page.screenshot({ path: testInfo.outputPath('premium-shop-1440.png') })
  await page.keyboard.press('Escape')
  await page.getByTestId('tab-formation').click()
  await page.getByRole('button', { name: '查看加成', exact: true }).click()
  await expect(page.getByTestId('premium-panel')).toContainText('原有加成合计')
  await expect(page.getByTestId('premium-totals')).toContainText('1.10')
  await page.screenshot({ path: testInfo.outputPath('premium-bonuses-1440.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: testInfo.outputPath('premium-bonuses-390.png') })
  const panel = await page.getByTestId('premium-panel').boundingBox()
  expect(panel!.x).toBeGreaterThanOrEqual(0)
  expect(panel!.x + panel!.width).toBeLessThanOrEqual(390)
  await page.getByRole('button', { name: '前往商城' }).click()
  await expect(page.getByTestId('tab-shop')).toHaveAttribute('aria-current', 'page')
  await expect(page.getByTestId('premium-panel')).toHaveCount(0)
  await page.locator('[data-card-id="training"]').click()
  await expect(page.getByTestId('voucher-balance')).toHaveText('3,800')
  await page.getByRole('heading', { name: '商城', exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('premium-shop-390.png') })
  await page.reload()
  await page.getByRole('button', { name: '继续游戏' }).click()
  await expect(page.getByTestId('voucher-balance')).toHaveText('3,800')
  await page.getByTestId('tab-shop').click()
  await page.locator('[data-action="shop-section"][data-section="premium"]').click()
  await expect(page.getByTestId('premium-totals')).toContainText('1.13')
  await page.clock.setFixedTime(now + 30 * 86_400_000)
  await expect(page.getByTestId('premium-card-monthly')).toContainText('已到期')
  await expect(page.getByTestId('premium-totals')).not.toContainText('1.13')
  expect(errors).toEqual([])
})
