/**
 * 属性注册表（202 属性）——由《诸天刷宝录》sx.json 解包生成（证据等级 A）。
 * 生成器：scripts/gen-attributes.py；请改源数据后重跑，勿手改本文件。
 *
 * sx.json 是属性中枢：装备词条 / buff / 技能效果 / 势力威力 / 元素威力
 * 全部以 id（1..202）为外键。战斗公式的 18 个乘区直接按 id 读取面板值。
 */

export type AttributeCategory = "元素" | "元素类" | "工作加成" | "战斗隐藏" | "技能效果" | "技能等级" | "技能组" | "技能被动" | "核心" | "熟练伤害" | "特殊" | "独立" | "能力" | "资质" | "附加" | "额外成长"
export type AttributeUnit = "小数" | "整数" | "每秒" | "百分比"
export type AttributeCalcType = "乘法" | "固定" | "增幅" | "指数"

export interface AttributeDefinition {
  id: number
  name: string
  category: AttributeCategory
  /** 默认值（sx.json 第 4 字段） */
  default: number
  unit: AttributeUnit
  /** 计算类型：乘法 / 指数 / 固定 / 增幅（决定面板成长与结算形态） */
  calcType: AttributeCalcType
  /** 词条前缀（sx.json 第 8 字段）；战斗隐藏/技能被动类为空或「无」 */
  affix: string
  /** 减伤/抗性类的生效上限（物法减伤/最终减伤/元素抗性=80；受 X 伤害=95）；其余为 0 */
  capMin: number
  /** 增伤/威力类的 roll 上限（增伤=1500、最终增伤=1000、技能组=1500）；部分减伤类=750 */
  capMax: number
  /** 是否参与战斗结算 */
  combatFlag: boolean
  /** 是否在角色界面显示 */
  uiFlag: boolean
}

export const ATTRIBUTES: AttributeDefinition[] = [
  { id: 1, name: "勇", category: "资质", default: 10, unit: "小数", calcType: "乘法", affix: "勇敢的", capMin: 0, capMax: 0, combatFlag: true, uiFlag: false },
  { id: 2, name: "智", category: "资质", default: 10, unit: "小数", calcType: "乘法", affix: "智慧的", capMin: 0, capMax: 0, combatFlag: true, uiFlag: false },
  { id: 3, name: "体", category: "资质", default: 10, unit: "小数", calcType: "乘法", affix: "体能的", capMin: 0, capMax: 0, combatFlag: true, uiFlag: false },
  { id: 4, name: "敏", category: "资质", default: 10, unit: "小数", calcType: "乘法", affix: "敏捷的", capMin: 0, capMax: 0, combatFlag: true, uiFlag: false },
  { id: 5, name: "精", category: "资质", default: 10, unit: "小数", calcType: "乘法", affix: "精神的", capMin: 0, capMax: 0, combatFlag: true, uiFlag: false },
  { id: 6, name: "生命", category: "核心", default: 10000, unit: "整数", calcType: "指数", affix: "生命的", capMin: 0, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 7, name: "速度", category: "核心", default: 5, unit: "整数", calcType: "乘法", affix: "速度的", capMin: 0, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 8, name: "物攻", category: "核心", default: 2000, unit: "整数", calcType: "指数", affix: "勇士的", capMin: 0, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 9, name: "物防", category: "核心", default: 1000, unit: "整数", calcType: "指数", affix: "厚重的", capMin: 0, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 10, name: "法攻", category: "核心", default: 2000, unit: "整数", calcType: "指数", affix: "法师的", capMin: 0, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 11, name: "法防", category: "核心", default: 1000, unit: "整数", calcType: "指数", affix: "坚韧的", capMin: 0, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 12, name: "暴击几率", category: "附加", default: 6, unit: "百分比", calcType: "乘法", affix: "暴击的", capMin: 100, capMax: 500, combatFlag: true, uiFlag: true },
  { id: 13, name: "暴击伤害", category: "附加", default: 40, unit: "百分比", calcType: "乘法", affix: "暴伤的", capMin: 0, capMax: 5000, combatFlag: true, uiFlag: true },
  { id: 14, name: "吸血比例", category: "附加", default: 3, unit: "百分比", calcType: "乘法", affix: "吸血的", capMin: 0, capMax: 300, combatFlag: true, uiFlag: true },
  { id: 15, name: "生命恢复", category: "附加", default: 200, unit: "每秒", calcType: "指数", affix: "自愈的", capMin: 0, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 16, name: "治疗加成", category: "附加", default: 20, unit: "百分比", calcType: "乘法", affix: "治疗的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 17, name: "护盾加成", category: "附加", default: 20, unit: "百分比", calcType: "乘法", affix: "护盾的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 18, name: "命中修正", category: "附加", default: 5, unit: "百分比", calcType: "乘法", affix: "命中的", capMin: 0, capMax: 1000, combatFlag: true, uiFlag: true },
  { id: 19, name: "闪避修正", category: "附加", default: 5, unit: "百分比", calcType: "乘法", affix: "闪避的", capMin: 0, capMax: 1000, combatFlag: true, uiFlag: true },
  { id: 20, name: "物理增伤", category: "附加", default: 20, unit: "百分比", calcType: "乘法", affix: "战士的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 21, name: "物理减伤", category: "附加", default: 8, unit: "百分比", calcType: "乘法", affix: "龟甲的", capMin: 80, capMax: 750, combatFlag: true, uiFlag: true },
  { id: 22, name: "法术增伤", category: "附加", default: 20, unit: "百分比", calcType: "乘法", affix: "异能的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 23, name: "法术减伤", category: "附加", default: 8, unit: "百分比", calcType: "乘法", affix: "结界的", capMin: 80, capMax: 750, combatFlag: true, uiFlag: true },
  { id: 24, name: "护盾超限", category: "附加", default: 20, unit: "百分比", calcType: "乘法", affix: "超盾的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 25, name: "普攻增伤", category: "附加", default: 20, unit: "百分比", calcType: "乘法", affix: "鹰击的", capMin: 0, capMax: 2000, combatFlag: true, uiFlag: true },
  { id: 26, name: "最终增伤", category: "附加", default: 10, unit: "百分比", calcType: "乘法", affix: "凤羽的", capMin: 0, capMax: 1000, combatFlag: true, uiFlag: true },
  { id: 27, name: "最终减伤", category: "附加", default: 4, unit: "百分比", calcType: "乘法", affix: "龙鳞的", capMin: 80, capMax: 750, combatFlag: true, uiFlag: true },
  { id: 28, name: "初始能量", category: "特殊", default: 100, unit: "整数", calcType: "固定", affix: "聚能的", capMin: 5, capMax: 100, combatFlag: true, uiFlag: true },
  { id: 29, name: "能量回复", category: "特殊", default: 100, unit: "整数", calcType: "固定", affix: "凝神的", capMin: 5, capMax: 100, combatFlag: true, uiFlag: true },
  { id: 30, name: "武器熟练", category: "特殊", default: 20, unit: "百分比", calcType: "乘法", affix: "熟练的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 31, name: "召唤强度", category: "特殊", default: 20, unit: "百分比", calcType: "乘法", affix: "召唤的", capMin: 0, capMax: 1200, combatFlag: true, uiFlag: false },
  { id: 32, name: "召唤数量", category: "特殊", default: 100, unit: "整数", calcType: "固定", affix: "通灵的", capMin: 3, capMax: 100, combatFlag: true, uiFlag: false },
  { id: 33, name: "召唤时间", category: "特殊", default: 50, unit: "百分比", calcType: "乘法", affix: "空间的", capMin: 0, capMax: 2000, combatFlag: true, uiFlag: false },
  { id: 34, name: "增益时间", category: "特殊", default: 50, unit: "百分比", calcType: "乘法", affix: "祝福的", capMin: 0, capMax: 2000, combatFlag: true, uiFlag: false },
  { id: 35, name: "减益时间", category: "特殊", default: 50, unit: "百分比", calcType: "乘法", affix: "诅咒的", capMin: 0, capMax: 2000, combatFlag: true, uiFlag: false },
  { id: 36, name: "灵兽经验", category: "特殊", default: 20, unit: "百分比", calcType: "乘法", affix: "御兽的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 37, name: "技能冷却", category: "特殊", default: 10, unit: "百分比", calcType: "乘法", affix: "时间的", capMin: 95, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 38, name: "受疗效果", category: "特殊", default: 20, unit: "百分比", calcType: "乘法", affix: "受疗的", capMin: 0, capMax: 2000, combatFlag: true, uiFlag: true },
  { id: 39, name: "技能学习", category: "特殊", default: 20, unit: "百分比", calcType: "乘法", affix: "修炼的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 40, name: "经验加成", category: "特殊", default: 20, unit: "百分比", calcType: "乘法", affix: "经验的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 41, name: "职业成长", category: "特殊", default: 20, unit: "百分比", calcType: "乘法", affix: "职业的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 42, name: "物品掉落", category: "特殊", default: 5, unit: "百分比", calcType: "乘法", affix: "幸运的", capMin: 0, capMax: 1000, combatFlag: true, uiFlag: false },
  { id: 43, name: "工作效率", category: "特殊", default: 20, unit: "百分比", calcType: "乘法", affix: "工匠的", capMin: 0, capMax: 2000, combatFlag: true, uiFlag: false },
  { id: 44, name: "雷系增伤", category: "元素", default: 20, unit: "百分比", calcType: "乘法", affix: "天空的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 45, name: "雷系抗性", category: "元素", default: 8, unit: "百分比", calcType: "乘法", affix: "雷鸣的", capMin: 80, capMax: 750, combatFlag: true, uiFlag: true },
  { id: 46, name: "水系增伤", category: "元素", default: 20, unit: "百分比", calcType: "乘法", affix: "海洋的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 47, name: "水系抗性", category: "元素", default: 8, unit: "百分比", calcType: "乘法", affix: "潮汐的", capMin: 80, capMax: 750, combatFlag: true, uiFlag: true },
  { id: 48, name: "火系增伤", category: "元素", default: 20, unit: "百分比", calcType: "乘法", affix: "火山的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 49, name: "火系抗性", category: "元素", default: 8, unit: "百分比", calcType: "乘法", affix: "熔岩的", capMin: 80, capMax: 750, combatFlag: true, uiFlag: true },
  { id: 50, name: "木系增伤", category: "元素", default: 20, unit: "百分比", calcType: "乘法", affix: "森林的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 51, name: "木系抗性", category: "元素", default: 8, unit: "百分比", calcType: "乘法", affix: "树精的", capMin: 80, capMax: 750, combatFlag: true, uiFlag: true },
  { id: 52, name: "土系增伤", category: "元素", default: 20, unit: "百分比", calcType: "乘法", affix: "大地的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 53, name: "土系抗性", category: "元素", default: 8, unit: "百分比", calcType: "乘法", affix: "岩石的", capMin: 80, capMax: 750, combatFlag: true, uiFlag: true },
  { id: 54, name: "精神增伤", category: "元素", default: 20, unit: "百分比", calcType: "乘法", affix: "幻想的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 55, name: "精神抗性", category: "元素", default: 8, unit: "百分比", calcType: "乘法", affix: "意志的", capMin: 80, capMax: 750, combatFlag: true, uiFlag: true },
  { id: 56, name: "神圣增伤", category: "元素", default: 20, unit: "百分比", calcType: "乘法", affix: "神圣的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 57, name: "神圣抗性", category: "元素", default: 8, unit: "百分比", calcType: "乘法", affix: "圣洁的", capMin: 80, capMax: 750, combatFlag: true, uiFlag: true },
  { id: 58, name: "黑暗增伤", category: "元素", default: 20, unit: "百分比", calcType: "乘法", affix: "黑暗的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 59, name: "黑暗抗性", category: "元素", default: 8, unit: "百分比", calcType: "乘法", affix: "邪恶的", capMin: 80, capMax: 750, combatFlag: true, uiFlag: true },
  { id: 60, name: "通用类效果", category: "技能效果", default: 25, unit: "百分比", calcType: "乘法", affix: "通用的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 61, name: "战技类效果", category: "技能效果", default: 25, unit: "百分比", calcType: "乘法", affix: "战技的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 62, name: "武功类效果", category: "技能效果", default: 25, unit: "百分比", calcType: "乘法", affix: "武功的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 63, name: "符咒类效果", category: "技能效果", default: 25, unit: "百分比", calcType: "乘法", affix: "符咒的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 64, name: "箭弩类效果", category: "技能效果", default: 25, unit: "百分比", calcType: "乘法", affix: "箭弩的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 65, name: "方术类效果", category: "技能效果", default: 25, unit: "百分比", calcType: "乘法", affix: "方术的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 66, name: "异能类效果", category: "技能效果", default: 25, unit: "百分比", calcType: "乘法", affix: "异能的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 67, name: "神技类效果", category: "技能效果", default: 25, unit: "百分比", calcType: "乘法", affix: "神技的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 68, name: "斗气类效果", category: "技能效果", default: 25, unit: "百分比", calcType: "乘法", affix: "斗气的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 69, name: "忍术类效果", category: "技能效果", default: 25, unit: "百分比", calcType: "乘法", affix: "忍术的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 70, name: "魔法类效果", category: "技能效果", default: 25, unit: "百分比", calcType: "乘法", affix: "魔法的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 71, name: "功法类效果", category: "技能效果", default: 25, unit: "百分比", calcType: "乘法", affix: "功法的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 72, name: "枪械类效果", category: "技能效果", default: 25, unit: "百分比", calcType: "乘法", affix: "枪械的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 73, name: "机甲类效果", category: "技能效果", default: 25, unit: "百分比", calcType: "乘法", affix: "机甲的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 74, name: "召唤类效果", category: "技能效果", default: 25, unit: "百分比", calcType: "乘法", affix: "召唤的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 75, name: "医术类效果", category: "技能效果", default: 25, unit: "百分比", calcType: "乘法", affix: "医术的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: true },
  { id: 76, name: "通用类等级", category: "技能等级", default: 10, unit: "整数", calcType: "乘法", affix: "通用的", capMin: 0, capMax: 100, combatFlag: true, uiFlag: false },
  { id: 77, name: "战技类等级", category: "技能等级", default: 10, unit: "整数", calcType: "乘法", affix: "战技的", capMin: 0, capMax: 100, combatFlag: true, uiFlag: false },
  { id: 78, name: "武功类等级", category: "技能等级", default: 10, unit: "整数", calcType: "乘法", affix: "武功的", capMin: 0, capMax: 100, combatFlag: true, uiFlag: false },
  { id: 79, name: "符咒类等级", category: "技能等级", default: 10, unit: "整数", calcType: "乘法", affix: "符咒的", capMin: 0, capMax: 100, combatFlag: true, uiFlag: false },
  { id: 80, name: "箭弩类等级", category: "技能等级", default: 10, unit: "整数", calcType: "乘法", affix: "箭弩的", capMin: 0, capMax: 100, combatFlag: true, uiFlag: false },
  { id: 81, name: "方术类等级", category: "技能等级", default: 10, unit: "整数", calcType: "乘法", affix: "方术的", capMin: 0, capMax: 100, combatFlag: true, uiFlag: false },
  { id: 82, name: "异能类等级", category: "技能等级", default: 10, unit: "整数", calcType: "乘法", affix: "异能的", capMin: 0, capMax: 100, combatFlag: true, uiFlag: false },
  { id: 83, name: "神技类等级", category: "技能等级", default: 10, unit: "整数", calcType: "乘法", affix: "神技的", capMin: 0, capMax: 100, combatFlag: true, uiFlag: false },
  { id: 84, name: "斗气类等级", category: "技能等级", default: 10, unit: "整数", calcType: "乘法", affix: "斗气的", capMin: 0, capMax: 100, combatFlag: true, uiFlag: false },
  { id: 85, name: "忍术类等级", category: "技能等级", default: 10, unit: "整数", calcType: "乘法", affix: "忍术的", capMin: 0, capMax: 100, combatFlag: true, uiFlag: false },
  { id: 86, name: "魔法类等级", category: "技能等级", default: 10, unit: "整数", calcType: "乘法", affix: "魔法的", capMin: 0, capMax: 100, combatFlag: true, uiFlag: false },
  { id: 87, name: "功法类等级", category: "技能等级", default: 10, unit: "整数", calcType: "乘法", affix: "功法的", capMin: 0, capMax: 100, combatFlag: true, uiFlag: false },
  { id: 88, name: "枪械类等级", category: "技能等级", default: 10, unit: "整数", calcType: "乘法", affix: "枪械的", capMin: 0, capMax: 100, combatFlag: true, uiFlag: false },
  { id: 89, name: "机甲类等级", category: "技能等级", default: 10, unit: "整数", calcType: "乘法", affix: "机甲的", capMin: 0, capMax: 100, combatFlag: true, uiFlag: false },
  { id: 90, name: "召唤类等级", category: "技能等级", default: 10, unit: "整数", calcType: "乘法", affix: "召唤的", capMin: 0, capMax: 100, combatFlag: true, uiFlag: false },
  { id: 91, name: "医术类等级", category: "技能等级", default: 10, unit: "整数", calcType: "乘法", affix: "医术的", capMin: 0, capMax: 100, combatFlag: true, uiFlag: false },
  { id: 92, name: "长柄增伤", category: "熟练伤害", default: 25, unit: "百分比", calcType: "乘法", affix: "长柄的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 93, name: "刀剑增伤", category: "熟练伤害", default: 25, unit: "百分比", calcType: "乘法", affix: "刀剑的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 94, name: "拳指增伤", category: "熟练伤害", default: 25, unit: "百分比", calcType: "乘法", affix: "拳指的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 95, name: "暗器增伤", category: "熟练伤害", default: 25, unit: "百分比", calcType: "乘法", affix: "暗器的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 96, name: "法杖增伤", category: "熟练伤害", default: 25, unit: "百分比", calcType: "乘法", affix: "法杖的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 97, name: "法球增伤", category: "熟练伤害", default: 25, unit: "百分比", calcType: "乘法", affix: "法球的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 98, name: "枪弩增伤", category: "熟练伤害", default: 25, unit: "百分比", calcType: "乘法", affix: "枪弩的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 99, name: "大炮增伤", category: "熟练伤害", default: 25, unit: "百分比", calcType: "乘法", affix: "大炮的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 100, name: "书卷增伤", category: "熟练伤害", default: 25, unit: "百分比", calcType: "乘法", affix: "书卷的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 101, name: "仪器增伤", category: "熟练伤害", default: 25, unit: "百分比", calcType: "乘法", affix: "仪器的", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 102, name: "驯兽等级", category: "能力", default: 100, unit: "整数", calcType: "固定", affix: "驯兽的", capMin: 5, capMax: 100, combatFlag: false, uiFlag: false },
  { id: 103, name: "管理等级", category: "能力", default: 100, unit: "整数", calcType: "固定", affix: "管理的", capMin: 5, capMax: 100, combatFlag: false, uiFlag: false },
  { id: 104, name: "锻造等级", category: "能力", default: 100, unit: "整数", calcType: "固定", affix: "锻造的", capMin: 5, capMax: 100, combatFlag: false, uiFlag: false },
  { id: 105, name: "修习等级", category: "能力", default: 100, unit: "整数", calcType: "固定", affix: "修习的", capMin: 5, capMax: 100, combatFlag: false, uiFlag: false },
  { id: 106, name: "研究等级", category: "能力", default: 100, unit: "整数", calcType: "固定", affix: "研究的", capMin: 5, capMax: 100, combatFlag: false, uiFlag: false },
  { id: 107, name: "建造等级", category: "能力", default: 100, unit: "整数", calcType: "固定", affix: "建造的", capMin: 5, capMax: 100, combatFlag: false, uiFlag: false },
  { id: 108, name: "商业等级", category: "能力", default: 100, unit: "整数", calcType: "固定", affix: "商业的", capMin: 5, capMax: 100, combatFlag: false, uiFlag: false },
  { id: 109, name: "合成等级", category: "能力", default: 100, unit: "整数", calcType: "固定", affix: "合成的", capMin: 5, capMax: 100, combatFlag: false, uiFlag: false },
  { id: 110, name: "计略等级", category: "能力", default: 100, unit: "整数", calcType: "固定", affix: "计略的", capMin: 5, capMax: 100, combatFlag: false, uiFlag: false },
  { id: 111, name: "收藏等级", category: "能力", default: 100, unit: "整数", calcType: "固定", affix: "收藏的", capMin: 5, capMax: 100, combatFlag: false, uiFlag: false },
  { id: 112, name: "生命上限修正", category: "战斗隐藏", default: 25, unit: "百分比", calcType: "乘法", affix: "", capMin: 0, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 113, name: "速度修正", category: "战斗隐藏", default: 25, unit: "百分比", calcType: "乘法", affix: "", capMin: 0, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 114, name: "物攻修正", category: "战斗隐藏", default: 25, unit: "百分比", calcType: "乘法", affix: "", capMin: 0, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 115, name: "法攻修正", category: "战斗隐藏", default: 25, unit: "百分比", calcType: "乘法", affix: "", capMin: 0, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 116, name: "物防修正", category: "战斗隐藏", default: 25, unit: "百分比", calcType: "乘法", affix: "", capMin: 0, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 117, name: "法防修正", category: "战斗隐藏", default: 25, unit: "百分比", calcType: "乘法", affix: "", capMin: 0, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 118, name: "受物理伤害", category: "战斗隐藏", default: 25, unit: "百分比", calcType: "乘法", affix: "", capMin: 95, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 119, name: "受法术伤害", category: "战斗隐藏", default: 25, unit: "百分比", calcType: "乘法", affix: "", capMin: 95, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 120, name: "受所有伤害", category: "战斗隐藏", default: 25, unit: "百分比", calcType: "乘法", affix: "", capMin: 95, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 121, name: "受治疗效果", category: "战斗隐藏", default: 25, unit: "百分比", calcType: "乘法", affix: "", capMin: 100, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 122, name: "受护盾效果", category: "战斗隐藏", default: 25, unit: "百分比", calcType: "乘法", affix: "", capMin: 100, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 123, name: "受雷系伤害", category: "战斗隐藏", default: 25, unit: "百分比", calcType: "乘法", affix: "", capMin: 95, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 124, name: "受水系伤害", category: "战斗隐藏", default: 25, unit: "百分比", calcType: "乘法", affix: "", capMin: 95, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 125, name: "受火系伤害", category: "战斗隐藏", default: 25, unit: "百分比", calcType: "乘法", affix: "", capMin: 95, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 126, name: "受木系伤害", category: "战斗隐藏", default: 25, unit: "百分比", calcType: "乘法", affix: "", capMin: 95, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 127, name: "受土系伤害", category: "战斗隐藏", default: 25, unit: "百分比", calcType: "乘法", affix: "", capMin: 95, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 128, name: "受精神伤害", category: "战斗隐藏", default: 25, unit: "百分比", calcType: "乘法", affix: "", capMin: 95, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 129, name: "受神圣伤害", category: "战斗隐藏", default: 25, unit: "百分比", calcType: "乘法", affix: "", capMin: 95, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 130, name: "受黑暗伤害", category: "战斗隐藏", default: 25, unit: "百分比", calcType: "乘法", affix: "", capMin: 95, capMax: 0, combatFlag: true, uiFlag: true },
  { id: 131, name: "生命增幅", category: "技能被动", default: 100, unit: "百分比", calcType: "增幅", affix: "", capMin: 0, capMax: 0, combatFlag: true, uiFlag: false },
  { id: 132, name: "速度增幅", category: "技能被动", default: 100, unit: "百分比", calcType: "增幅", affix: "", capMin: 0, capMax: 0, combatFlag: true, uiFlag: false },
  { id: 133, name: "物攻增幅", category: "技能被动", default: 100, unit: "百分比", calcType: "增幅", affix: "", capMin: 0, capMax: 0, combatFlag: true, uiFlag: false },
  { id: 134, name: "物防增幅", category: "技能被动", default: 100, unit: "百分比", calcType: "增幅", affix: "", capMin: 0, capMax: 0, combatFlag: true, uiFlag: false },
  { id: 135, name: "法攻增幅", category: "技能被动", default: 100, unit: "百分比", calcType: "增幅", affix: "", capMin: 0, capMax: 0, combatFlag: true, uiFlag: false },
  { id: 136, name: "法防增幅", category: "技能被动", default: 100, unit: "百分比", calcType: "增幅", affix: "", capMin: 0, capMax: 0, combatFlag: true, uiFlag: false },
  { id: 137, name: "驯兽工作效率", category: "工作加成", default: 25, unit: "百分比", calcType: "乘法", affix: "驯兽的", capMin: 0, capMax: 2500, combatFlag: false, uiFlag: false },
  { id: 138, name: "管理工作效率", category: "工作加成", default: 25, unit: "百分比", calcType: "乘法", affix: "管理的", capMin: 0, capMax: 2500, combatFlag: false, uiFlag: false },
  { id: 139, name: "锻造工作效率", category: "工作加成", default: 25, unit: "百分比", calcType: "乘法", affix: "锻造的", capMin: 0, capMax: 2500, combatFlag: false, uiFlag: false },
  { id: 140, name: "修习工作效率", category: "工作加成", default: 25, unit: "百分比", calcType: "乘法", affix: "修习的", capMin: 0, capMax: 2500, combatFlag: false, uiFlag: false },
  { id: 141, name: "研究工作效率", category: "工作加成", default: 25, unit: "百分比", calcType: "乘法", affix: "研究的", capMin: 0, capMax: 2500, combatFlag: false, uiFlag: false },
  { id: 142, name: "建造工作效率", category: "工作加成", default: 25, unit: "百分比", calcType: "乘法", affix: "建造的", capMin: 0, capMax: 2500, combatFlag: false, uiFlag: false },
  { id: 143, name: "商业工作效率", category: "工作加成", default: 25, unit: "百分比", calcType: "乘法", affix: "商业的", capMin: 0, capMax: 2500, combatFlag: false, uiFlag: false },
  { id: 144, name: "合成工作效率", category: "工作加成", default: 25, unit: "百分比", calcType: "乘法", affix: "合成的", capMin: 0, capMax: 2500, combatFlag: false, uiFlag: false },
  { id: 145, name: "计略工作效率", category: "工作加成", default: 25, unit: "百分比", calcType: "乘法", affix: "战略的", capMin: 0, capMax: 2500, combatFlag: false, uiFlag: false },
  { id: 146, name: "收藏工作效率", category: "工作加成", default: 25, unit: "百分比", calcType: "乘法", affix: "收藏的", capMin: 0, capMax: 2500, combatFlag: false, uiFlag: false },
  { id: 147, name: "勇额外成长", category: "额外成长", default: 10, unit: "小数", calcType: "乘法", affix: "勇敢的", capMin: 0, capMax: 0, combatFlag: true, uiFlag: false },
  { id: 148, name: "智额外成长", category: "额外成长", default: 10, unit: "小数", calcType: "乘法", affix: "智慧的", capMin: 0, capMax: 0, combatFlag: true, uiFlag: false },
  { id: 149, name: "体额外成长", category: "额外成长", default: 10, unit: "小数", calcType: "乘法", affix: "体能的", capMin: 0, capMax: 0, combatFlag: true, uiFlag: false },
  { id: 150, name: "敏额外成长", category: "额外成长", default: 10, unit: "小数", calcType: "乘法", affix: "敏捷的", capMin: 0, capMax: 0, combatFlag: true, uiFlag: false },
  { id: 151, name: "精额外成长", category: "额外成长", default: 10, unit: "小数", calcType: "乘法", affix: "精神的", capMin: 0, capMax: 0, combatFlag: true, uiFlag: false },
  { id: 152, name: "货币掉落", category: "独立", default: 5, unit: "百分比", calcType: "乘法", affix: "财富的", capMin: 0, capMax: 0, combatFlag: true, uiFlag: false },
  { id: 153, name: "<汉末武技>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 154, name: "<曹魏虎卫>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 155, name: "<蜀汉青书>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 156, name: "<东吴射术>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 157, name: "<丐帮技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 158, name: "<少林技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 159, name: "<华山技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 160, name: "<武当技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 161, name: "<摸金技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 162, name: "<搬山技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 163, name: "<卸岭技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 164, name: "<发丘技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 165, name: "<耶路技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 166, name: "<十字技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 167, name: "<阿拉技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 168, name: "<人间技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 169, name: "<饿鬼技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 170, name: "<妖灵技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 171, name: "<幕府技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 172, name: "<织田技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 173, name: "<德川技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 174, name: "<英美技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 175, name: "<苏联技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 176, name: "<德国技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 177, name: "<仙域技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 178, name: "<玄天技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 179, name: "<合欢技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 180, name: "<地球技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 181, name: "<宇宙技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 182, name: "<维斯技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 183, name: "<落云技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 184, name: "<卡玛技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 185, name: "<慕然技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 186, name: "<中立技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 187, name: "<联盟技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 188, name: "<部落技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 189, name: "<至尊技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 190, name: "<暗裔技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 191, name: "<变种技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 192, name: "<大唐技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 193, name: "<妖族技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 194, name: "<天庭技能>威力", category: "技能组", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1500, combatFlag: true, uiFlag: false },
  { id: 195, name: "<雷系技能>威力", category: "元素类", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1000, combatFlag: true, uiFlag: false },
  { id: 196, name: "<水系技能>威力", category: "元素类", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1000, combatFlag: true, uiFlag: false },
  { id: 197, name: "<火系技能>威力", category: "元素类", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1000, combatFlag: true, uiFlag: false },
  { id: 198, name: "<木系技能>威力", category: "元素类", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1000, combatFlag: true, uiFlag: false },
  { id: 199, name: "<土系技能>威力", category: "元素类", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1000, combatFlag: true, uiFlag: false },
  { id: 200, name: "<精神技能>威力", category: "元素类", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1000, combatFlag: true, uiFlag: false },
  { id: 201, name: "<神圣技能>威力", category: "元素类", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1000, combatFlag: true, uiFlag: false },
  { id: 202, name: "<黑暗技能>威力", category: "元素类", default: 20, unit: "百分比", calcType: "乘法", affix: "无", capMin: 0, capMax: 1000, combatFlag: true, uiFlag: false },
]

/** 按 id 索引（1..202） */
export const ATTRIBUTE_BY_ID: Record<number, AttributeDefinition> = Object.fromEntries(
  ATTRIBUTES.map((a) => [a.id, a]),
)

/** 属性 id（1..202），即 sx.json 的属性编号 */
export type AttributeId = number
/** 角色属性面板：属性 id → 数值。这是诸天模型的统一属性载体，替代原散落的 CombatStats 字段 */
export type AttributeMap = Record<AttributeId, number>
