export type CareerCategory = '剑' | '刀' | '拳' | '暗' | '医' | '内家'
export type CareerTier = '初级' | '一阶' | '二阶' | '三阶' | '四阶' | '五阶'

export const SKILL_TYPE_NAMES: Record<number, string> = {
  1: '通用',
  2: '战技',
  3: '武功',
  4: '符咒',
  5: '箭弩',
  6: '方术',
  7: '异能',
  8: '神技',
  9: '斗气',
  10: '忍术',
  11: '魔法',
  12: '功法',
  13: '枪械',
  14: '机甲',
  15: '召唤',
  16: '医术',
}

export interface CareerRequirement {
  careerId: string
  level: number
}

export interface CareerGrowth {
  physicalAttack: number
  magicAttack: number
  speed: number
  physicalDefense: number
  magicDefense: number
  heal: number
}

export interface CareerDefinition {
  id: string
  zyId: number
  name: string
  description: string
  tier: CareerTier
  rank: 1 | 2 | 3 | 4 | 5 | 6
  skillTypeIds: number[]
  growth: CareerGrowth
  requirements: CareerRequirement[]
  basicAttackSkillId: number
}

export const STARTER_CAREER_ID = 'job_1'

export const CAREERS: CareerDefinition[] = [
  {
    id: 'job_1',
    zyId: 1,
    name: "白丁",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '初级',
    rank: 1,
    skillTypeIds: [1],
    growth: {
      physicalAttack: 0.9,
      magicAttack: 0.9,
      speed: 0.9,
      physicalDefense: 0.9,
      magicDefense: 0.9,
      heal: 0.9,
    },
    requirements: [],
    basicAttackSkillId: 1,
  },
  {
    id: 'job_2',
    zyId: 2,
    name: "护卫",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '一阶',
    rank: 2,
    skillTypeIds: [2],
    growth: {
      physicalAttack: 1.1,
      magicAttack: 1.2,
      speed: 0.8,
      physicalDefense: 1.1,
      magicDefense: 0.8,
      heal: 0.7,
    },
    requirements: [{ careerId: 'job_1', level: 5 }],
    basicAttackSkillId: 2,
  },
  {
    id: 'job_3',
    zyId: 3,
    name: "武夫",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '一阶',
    rank: 2,
    skillTypeIds: [3],
    growth: {
      physicalAttack: 1.2,
      magicAttack: 1,
      speed: 0.8,
      physicalDefense: 0.9,
      magicDefense: 1.1,
      heal: 0.8,
    },
    requirements: [{ careerId: 'job_1', level: 5 }],
    basicAttackSkillId: 3,
  },
  {
    id: 'job_4',
    zyId: 4,
    name: "学者",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '一阶',
    rank: 2,
    skillTypeIds: [4],
    growth: {
      physicalAttack: 0.8,
      magicAttack: 0.9,
      speed: 1.3,
      physicalDefense: 1.1,
      magicDefense: 1,
      heal: 0.8,
    },
    requirements: [{ careerId: 'job_1', level: 5 }],
    basicAttackSkillId: 4,
  },
  {
    id: 'job_5',
    zyId: 5,
    name: "弓手",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '一阶',
    rank: 2,
    skillTypeIds: [5],
    growth: {
      physicalAttack: 1.1,
      magicAttack: 0.9,
      speed: 0.8,
      physicalDefense: 1,
      magicDefense: 1.2,
      heal: 0.8,
    },
    requirements: [{ careerId: 'job_1', level: 5 }],
    basicAttackSkillId: 5,
  },
  {
    id: 'job_6',
    zyId: 6,
    name: "方士",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '一阶',
    rank: 2,
    skillTypeIds: [6],
    growth: {
      physicalAttack: 0.8,
      magicAttack: 0.8,
      speed: 1.1,
      physicalDefense: 1.2,
      magicDefense: 0.9,
      heal: 1.3,
    },
    requirements: [{ careerId: 'job_1', level: 5 }],
    basicAttackSkillId: 6,
  },
  {
    id: 'job_7',
    zyId: 7,
    name: "异能者",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '二阶',
    rank: 3,
    skillTypeIds: [7],
    growth: {
      physicalAttack: 1.2,
      magicAttack: 1.4,
      speed: 0.9,
      physicalDefense: 1.2,
      magicDefense: 0.9,
      heal: 1,
    },
    requirements: [{ careerId: 'job_2', level: 10 }],
    basicAttackSkillId: 7,
  },
  {
    id: 'job_8',
    zyId: 8,
    name: "圣教徒",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '二阶',
    rank: 3,
    skillTypeIds: [8],
    growth: {
      physicalAttack: 1.1,
      magicAttack: 1.2,
      speed: 1,
      physicalDefense: 1.4,
      magicDefense: 1,
      heal: 0.8,
    },
    requirements: [{ careerId: 'job_2', level: 10 }],
    basicAttackSkillId: 8,
  },
  {
    id: 'job_9',
    zyId: 9,
    name: "侠客",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '二阶',
    rank: 3,
    skillTypeIds: [9],
    growth: {
      physicalAttack: 1.4,
      magicAttack: 1.1,
      speed: 0.8,
      physicalDefense: 1,
      magicDefense: 1.2,
      heal: 0.8,
    },
    requirements: [{ careerId: 'job_3', level: 10 }],
    basicAttackSkillId: 9,
  },
  {
    id: 'job_10',
    zyId: 10,
    name: "武士",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '二阶',
    rank: 3,
    skillTypeIds: [10],
    growth: {
      physicalAttack: 1.3,
      magicAttack: 1.2,
      speed: 0.9,
      physicalDefense: 0.9,
      magicDefense: 1.3,
      heal: 1,
    },
    requirements: [{ careerId: 'job_3', level: 10 }],
    basicAttackSkillId: 10,
  },
  {
    id: 'job_11',
    zyId: 11,
    name: "巫师",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '二阶',
    rank: 3,
    skillTypeIds: [11],
    growth: {
      physicalAttack: 0.8,
      magicAttack: 0.9,
      speed: 1.5,
      physicalDefense: 1.2,
      magicDefense: 1.1,
      heal: 0.9,
    },
    requirements: [{ careerId: 'job_4', level: 10 }],
    basicAttackSkillId: 11,
  },
  {
    id: 'job_12',
    zyId: 12,
    name: "道众",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '二阶',
    rank: 3,
    skillTypeIds: [12],
    growth: {
      physicalAttack: 0.8,
      magicAttack: 1,
      speed: 1.4,
      physicalDefense: 1.1,
      magicDefense: 1.2,
      heal: 0.8,
    },
    requirements: [{ careerId: 'job_4', level: 10 }],
    basicAttackSkillId: 12,
  },
  {
    id: 'job_13',
    zyId: 13,
    name: "游侠",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '二阶',
    rank: 3,
    skillTypeIds: [13],
    growth: {
      physicalAttack: 1.3,
      magicAttack: 1,
      speed: 0.9,
      physicalDefense: 1.1,
      magicDefense: 1.4,
      heal: 0.7,
    },
    requirements: [{ careerId: 'job_5', level: 10 }],
    basicAttackSkillId: 13,
  },
  {
    id: 'job_14',
    zyId: 14,
    name: "火炮手",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '二阶',
    rank: 3,
    skillTypeIds: [14],
    growth: {
      physicalAttack: 1.2,
      magicAttack: 1.1,
      speed: 1,
      physicalDefense: 1.2,
      magicDefense: 1.2,
      heal: 1,
    },
    requirements: [{ careerId: 'job_5', level: 10 }],
    basicAttackSkillId: 14,
  },
  {
    id: 'job_15',
    zyId: 15,
    name: "通灵者",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '二阶',
    rank: 3,
    skillTypeIds: [15],
    growth: {
      physicalAttack: 0.9,
      magicAttack: 1,
      speed: 1.3,
      physicalDefense: 1.3,
      magicDefense: 1.1,
      heal: 1.4,
    },
    requirements: [{ careerId: 'job_6', level: 10 }],
    basicAttackSkillId: 15,
  },
  {
    id: 'job_16',
    zyId: 16,
    name: "医生",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '二阶',
    rank: 3,
    skillTypeIds: [16],
    growth: {
      physicalAttack: 0.8,
      magicAttack: 0.9,
      speed: 1.2,
      physicalDefense: 1.4,
      magicDefense: 1,
      heal: 1.5,
    },
    requirements: [{ careerId: 'job_6', level: 10 }],
    basicAttackSkillId: 16,
  },
  {
    id: 'job_17',
    zyId: 17,
    name: "变种人",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '三阶',
    rank: 4,
    skillTypeIds: [7],
    growth: {
      physicalAttack: 1.42,
      magicAttack: 1.65,
      speed: 1.06,
      physicalDefense: 1.42,
      magicDefense: 1.06,
      heal: 1.18,
    },
    requirements: [{ careerId: 'job_7', level: 10 }],
    basicAttackSkillId: 17,
  },
  {
    id: 'job_18',
    zyId: 18,
    name: "圣殿军",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '三阶',
    rank: 4,
    skillTypeIds: [8],
    growth: {
      physicalAttack: 1.3,
      magicAttack: 1.42,
      speed: 1.18,
      physicalDefense: 1.65,
      magicDefense: 1.18,
      heal: 0.94,
    },
    requirements: [{ careerId: 'job_8', level: 10 }],
    basicAttackSkillId: 18,
  },
  {
    id: 'job_19',
    zyId: 19,
    name: "斗者",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '三阶',
    rank: 4,
    skillTypeIds: [9],
    growth: {
      physicalAttack: 1.65,
      magicAttack: 1.3,
      speed: 0.94,
      physicalDefense: 1.18,
      magicDefense: 1.42,
      heal: 0.94,
    },
    requirements: [{ careerId: 'job_9', level: 10 }],
    basicAttackSkillId: 19,
  },
  {
    id: 'job_20',
    zyId: 20,
    name: "忍者",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '三阶',
    rank: 4,
    skillTypeIds: [10],
    growth: {
      physicalAttack: 1.53,
      magicAttack: 1.42,
      speed: 1.06,
      physicalDefense: 1.06,
      magicDefense: 1.53,
      heal: 1.18,
    },
    requirements: [{ careerId: 'job_10', level: 10 }],
    basicAttackSkillId: 20,
  },
  {
    id: 'job_21',
    zyId: 21,
    name: "魔法师",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '三阶',
    rank: 4,
    skillTypeIds: [11],
    growth: {
      physicalAttack: 0.94,
      magicAttack: 1.06,
      speed: 1.77,
      physicalDefense: 1.42,
      magicDefense: 1.3,
      heal: 1.06,
    },
    requirements: [{ careerId: 'job_11', level: 10 }],
    basicAttackSkillId: 21,
  },
  {
    id: 'job_22',
    zyId: 22,
    name: "修真者",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '三阶',
    rank: 4,
    skillTypeIds: [12],
    growth: {
      physicalAttack: 0.94,
      magicAttack: 1.18,
      speed: 1.65,
      physicalDefense: 1.3,
      magicDefense: 1.42,
      heal: 0.94,
    },
    requirements: [{ careerId: 'job_12', level: 10 }],
    basicAttackSkillId: 22,
  },
  {
    id: 'job_23',
    zyId: 23,
    name: "枪手",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '三阶',
    rank: 4,
    skillTypeIds: [13],
    growth: {
      physicalAttack: 1.53,
      magicAttack: 1.18,
      speed: 1.06,
      physicalDefense: 1.3,
      magicDefense: 1.65,
      heal: 0.83,
    },
    requirements: [{ careerId: 'job_13', level: 10 }],
    basicAttackSkillId: 23,
  },
  {
    id: 'job_24',
    zyId: 24,
    name: "机甲驾驶员",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '三阶',
    rank: 4,
    skillTypeIds: [14],
    growth: {
      physicalAttack: 1.42,
      magicAttack: 1.3,
      speed: 1.18,
      physicalDefense: 1.42,
      magicDefense: 1.42,
      heal: 1.18,
    },
    requirements: [{ careerId: 'job_14', level: 10 }],
    basicAttackSkillId: 24,
  },
  {
    id: 'job_25',
    zyId: 25,
    name: "德鲁伊",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '三阶',
    rank: 4,
    skillTypeIds: [15],
    growth: {
      physicalAttack: 1.06,
      magicAttack: 1.18,
      speed: 1.53,
      physicalDefense: 1.53,
      magicDefense: 1.3,
      heal: 1.65,
    },
    requirements: [{ careerId: 'job_15', level: 10 }],
    basicAttackSkillId: 25,
  },
  {
    id: 'job_26',
    zyId: 26,
    name: "老中医",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '三阶',
    rank: 4,
    skillTypeIds: [16],
    growth: {
      physicalAttack: 0.94,
      magicAttack: 1.06,
      speed: 1.42,
      physicalDefense: 1.65,
      magicDefense: 1.18,
      heal: 1.77,
    },
    requirements: [{ careerId: 'job_16', level: 10 }],
    basicAttackSkillId: 26,
  },
  {
    id: 'job_27',
    zyId: 27,
    name: "超能力者",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '四阶',
    rank: 5,
    skillTypeIds: [7],
    growth: {
      physicalAttack: 1.67,
      magicAttack: 1.95,
      speed: 1.25,
      physicalDefense: 1.67,
      magicDefense: 1.25,
      heal: 1.39,
    },
    requirements: [{ careerId: 'job_17', level: 10 }],
    basicAttackSkillId: 27,
  },
  {
    id: 'job_28',
    zyId: 28,
    name: "神殿教皇",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '四阶',
    rank: 5,
    skillTypeIds: [8],
    growth: {
      physicalAttack: 1.53,
      magicAttack: 1.67,
      speed: 1.39,
      physicalDefense: 1.95,
      magicDefense: 1.39,
      heal: 1.11,
    },
    requirements: [{ careerId: 'job_18', level: 10 }],
    basicAttackSkillId: 28,
  },
  {
    id: 'job_29',
    zyId: 29,
    name: "封号斗罗",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '四阶',
    rank: 5,
    skillTypeIds: [9],
    growth: {
      physicalAttack: 1.95,
      magicAttack: 1.53,
      speed: 1.11,
      physicalDefense: 1.39,
      magicDefense: 1.67,
      heal: 1.11,
    },
    requirements: [{ careerId: 'job_19', level: 10 }],
    basicAttackSkillId: 29,
  },
  {
    id: 'job_30',
    zyId: 30,
    name: "影",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '四阶',
    rank: 5,
    skillTypeIds: [10],
    growth: {
      physicalAttack: 1.81,
      magicAttack: 1.67,
      speed: 1.25,
      physicalDefense: 1.25,
      magicDefense: 1.81,
      heal: 1.39,
    },
    requirements: [{ careerId: 'job_20', level: 10 }],
    basicAttackSkillId: 30,
  },
  {
    id: 'job_31',
    zyId: 31,
    name: "法皇",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '四阶',
    rank: 5,
    skillTypeIds: [11],
    growth: {
      physicalAttack: 1.11,
      magicAttack: 1.25,
      speed: 2.09,
      physicalDefense: 1.67,
      magicDefense: 1.53,
      heal: 1.25,
    },
    requirements: [{ careerId: 'job_21', level: 10 }],
    basicAttackSkillId: 31,
  },
  {
    id: 'job_32',
    zyId: 32,
    name: "散仙",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '四阶',
    rank: 5,
    skillTypeIds: [12],
    growth: {
      physicalAttack: 1.11,
      magicAttack: 1.39,
      speed: 1.95,
      physicalDefense: 1.53,
      magicDefense: 1.67,
      heal: 1.11,
    },
    requirements: [{ careerId: 'job_22', level: 10 }],
    basicAttackSkillId: 32,
  },
  {
    id: 'job_33',
    zyId: 33,
    name: "新人类",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '四阶',
    rank: 5,
    skillTypeIds: [13],
    growth: {
      physicalAttack: 1.81,
      magicAttack: 1.39,
      speed: 1.25,
      physicalDefense: 1.53,
      magicDefense: 1.95,
      heal: 0.97,
    },
    requirements: [{ careerId: 'job_23', level: 10 }],
    basicAttackSkillId: 33,
  },
  {
    id: 'job_34',
    zyId: 34,
    name: "王牌机师",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '四阶',
    rank: 5,
    skillTypeIds: [14],
    growth: {
      physicalAttack: 1.67,
      magicAttack: 1.53,
      speed: 1.39,
      physicalDefense: 1.67,
      magicDefense: 1.67,
      heal: 1.39,
    },
    requirements: [{ careerId: 'job_24', level: 10 }],
    basicAttackSkillId: 34,
  },
  {
    id: 'job_35',
    zyId: 35,
    name: "位面行者",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '四阶',
    rank: 5,
    skillTypeIds: [15],
    growth: {
      physicalAttack: 1.25,
      magicAttack: 1.39,
      speed: 1.81,
      physicalDefense: 1.81,
      magicDefense: 1.53,
      heal: 1.95,
    },
    requirements: [{ careerId: 'job_25', level: 10 }],
    basicAttackSkillId: 35,
  },
  {
    id: 'job_36',
    zyId: 36,
    name: "科学伟人",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '四阶',
    rank: 5,
    skillTypeIds: [16],
    growth: {
      physicalAttack: 1.11,
      magicAttack: 1.25,
      speed: 1.67,
      physicalDefense: 1.95,
      magicDefense: 1.39,
      heal: 2.09,
    },
    requirements: [{ careerId: 'job_26', level: 10 }],
    basicAttackSkillId: 36,
  },
  {
    id: 'job_37',
    zyId: 37,
    name: "主神",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '五阶',
    rank: 6,
    skillTypeIds: [8, 11],
    growth: {
      physicalAttack: 1.76,
      magicAttack: 1.92,
      speed: 2.4,
      physicalDefense: 2.24,
      magicDefense: 1.76,
      heal: 1.44,
    },
    requirements: [{ careerId: 'job_28', level: 10 }, { careerId: 'job_31', level: 10 }],
    basicAttackSkillId: 37,
  },
  {
    id: 'job_38',
    zyId: 38,
    name: "天帝",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '五阶',
    rank: 6,
    skillTypeIds: [7, 10],
    growth: {
      physicalAttack: 2.08,
      magicAttack: 2.24,
      speed: 1.44,
      physicalDefense: 1.92,
      magicDefense: 2.08,
      heal: 1.6,
    },
    requirements: [{ careerId: 'job_27', level: 10 }, { careerId: 'job_30', level: 10 }],
    basicAttackSkillId: 38,
  },
  {
    id: 'job_39',
    zyId: 39,
    name: "仙尊",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '五阶',
    rank: 6,
    skillTypeIds: [12, 15],
    growth: {
      physicalAttack: 1.44,
      magicAttack: 1.6,
      speed: 2.24,
      physicalDefense: 2.08,
      magicDefense: 1.92,
      heal: 2.24,
    },
    requirements: [{ careerId: 'job_32', level: 10 }, { careerId: 'job_35', level: 10 }],
    basicAttackSkillId: 39,
  },
  {
    id: 'job_40',
    zyId: 40,
    name: "人皇",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '五阶',
    rank: 6,
    skillTypeIds: [9, 13],
    growth: {
      physicalAttack: 2.24,
      magicAttack: 1.76,
      speed: 1.44,
      physicalDefense: 1.76,
      magicDefense: 2.24,
      heal: 1.28,
    },
    requirements: [{ careerId: 'job_29', level: 10 }, { careerId: 'job_33', level: 10 }],
    basicAttackSkillId: 40,
  },
  {
    id: 'job_41',
    zyId: 41,
    name: "造物者",
    description: "这是一个神奇的职业。我还没想好怎么介绍它。",
    tier: '五阶',
    rank: 6,
    skillTypeIds: [14, 16],
    growth: {
      physicalAttack: 1.92,
      magicAttack: 1.76,
      speed: 1.92,
      physicalDefense: 2.24,
      magicDefense: 1.92,
      heal: 2.4,
    },
    requirements: [{ careerId: 'job_34', level: 10 }, { careerId: 'job_36', level: 10 }],
    basicAttackSkillId: 41,
  }
]

export const CAREER_GROWTH_FIELDS: Array<{ id: keyof CareerGrowth; label: string }> = [
  { id: 'physicalAttack', label: '物攻' },
  { id: 'magicAttack', label: '法攻' },
  { id: 'speed', label: '速度' },
  { id: 'physicalDefense', label: '物防' },
  { id: 'magicDefense', label: '法防' },
  { id: 'heal', label: '治疗' },
]

export const careerById = (id: string): CareerDefinition | undefined =>
  CAREERS.find((career) => career.id === id)

export const careersInRank = (rank: CareerDefinition['rank']): CareerDefinition[] =>
  CAREERS.filter((career) => career.rank === rank)

export const careerSkillTypeNames = (career: CareerDefinition): string[] =>
  career.skillTypeIds.map((id) => SKILL_TYPE_NAMES[id] ?? '未知')

export const careerJobBookName = (career: CareerDefinition): string =>
  `${career.name}转职书`

export const growthGrade = (coeff: number): string => {
  if (coeff >= 2.3) return 'SSS'
  if (coeff >= 2.0) return 'SS'
  if (coeff >= 1.7) return 'S'
  if (coeff >= 1.4) return 'A'
  if (coeff >= 1.2) return 'B'
  if (coeff >= 1.0) return 'C'
  if (coeff >= 0.8) return 'D'
  return 'E'
}

export const formatGrowthCoeff = (coeff: number): string =>
  coeff.toFixed(2).replace(/0+$/, '').replace(/\.$/, '')
