// 由 scripts 依据 docs/武功重设计方案 生成，请勿手改；展示性 lore，详见设计文档
// 势力武功 240 门、城市通用武功 60 门、心法 40 门
export interface MartialLore {
  description: string
  origin: string
  stageName: string
  powerNote: string
  tags: string[]
}

export const MARTIAL_LORE: Record<string, MartialLore> = {
  'qingfeng_hall_a1': { description: '两段连击，剑势平正，总威力为同阶单体1.1倍', origin: '《射雕英雄传》', stageName: '初传', powerNote: '1.15 ×2段(总1.27)', tags: ['单体', '连击'] },
  'qingfeng_hall_b1': { description: '三段连击，一剑幻出三道剑影，象征剑意分化', origin: '《射雕英雄传》', stageName: '进境', powerNote: '1.5 ×3段', tags: ['单体', '连击'] },
  'qingfeng_hall_c1': { description: '四段连击踏罡步斗，末段附带迟缓20%持续3秒', origin: '《射雕英雄传》', stageName: '真传', powerNote: '1.85 ×4段(总1.7)', tags: ['单体', '连击', '迟缓'] },
  'qingfeng_hall_d1': { description: '五段连击玉石俱焚，末段给目标挂破绽标记（友方对其伤害加深15%，触发后消失）', origin: '《射雕英雄传》', stageName: '秘传', powerNote: '2.2 ×5段(总2.42)', tags: ['单体', '连击', '破绽'] },
  'qingfeng_hall_a2': { description: '单体重击锁住关隘，附带破甲20%持续4秒', origin: '江湖流传', stageName: '初传', powerNote: '1.04', tags: ['单体', '破甲'] },
  'qingfeng_hall_b2': { description: '单体重击剑意肃杀如霜，附带迟缓30%持续3秒', origin: '江湖流传', stageName: '进境', powerNote: '1.43', tags: ['单体', '迟缓'] },
  'qingfeng_hall_c2': { description: '两段重剑连击阴阳交济，第二段附带破甲30%持续4秒', origin: '江湖流传', stageName: '真传', powerNote: '1.85 ×2段', tags: ['单体', '连击', '破甲'] },
  'qingfeng_hall_d2': { description: '蓄力0.8秒后一剑开山，附带破甲40%持续5秒', origin: '江湖流传', stageName: '秘传', powerNote: '2.42', tags: ['单体', '蓄力', '破甲'] },
  'tieyi_school_a1': { description: '单体重击掌出如龙，附带击退一格', origin: '《射雕英雄传》（降龙十八掌第一式）', stageName: '初传', powerNote: '1.15', tags: ['单体', '击退'] },
  'tieyi_school_b1': { description: '掌风横扫，群体伤害（单体基准的60%）', origin: '《射雕英雄传》（降龙十八掌第二式）', stageName: '进境', powerNote: '0.9', tags: ['群体'] },
  'tieyi_school_c1': { description: '先给自己套护盾（吸收量=威力×0.8）蓄势，再单体反击', origin: '《射雕英雄传》（降龙十八掌第三式）', stageName: '真传', powerNote: '1.67', tags: ['单体', '护盾'] },
  'tieyi_school_d1': { description: '掌势一往无前，自身生命低于40%时威力提升30%（狂暴），群体伤害', origin: '《射雕英雄传》（降龙十八掌第四式）', stageName: '秘传', powerNote: '1.43', tags: ['群体', '狂暴'] },
  'tieyi_school_a2': { description: '掌影如莲瓣纷飞，单体伤害并附带中毒1层（每秒最大生命0.6%，持续6秒）', origin: '《射雕英雄传》', stageName: '初传', powerNote: '0.92', tags: ['单体', '中毒'] },
  'tieyi_school_b2': { description: '两段连击拳走游龙，末段附带迟缓25%持续3秒', origin: '《射雕英雄传》（洪七公所传）', stageName: '进境', powerNote: '1.5 ×2段(总1.5)', tags: ['单体', '连击', '迟缓'] },
  'tieyi_school_c2': { description: '绵里藏铁，单体伤害并附带中毒2层、易伤15%持续4秒', origin: '江湖流传', stageName: '真传', powerNote: '1.48', tags: ['单体', '中毒', '易伤'] },
  'tieyi_school_d2': { description: '掌势如羝羊困于藩篱，群体中毒2层并迟缓20%持续4秒，令敌进退两难', origin: '江湖流传', stageName: '秘传', powerNote: '1.1', tags: ['群体', '中毒', '迟缓'] },
  'renxin_hall_a1': { description: '桃花岛疗伤圣药，群体治疗（单体基准的60%）', origin: '《射雕英雄传》', stageName: '初传', powerNote: '0.69', tags: ['群疗'] },
  'renxin_hall_b1': { description: '以毒攻毒，净化单体友方全部减益并治疗', origin: '《射雕英雄传》', stageName: '进境', powerNote: '1.28', tags: ['单疗', 'cleanse'] },
  'renxin_hall_c1': { description: '奇门遁甲护体，为生命最低的友方治疗并套护盾（吸收量=威力×0.6）', origin: '《射雕英雄传》', stageName: '真传', powerNote: '1.57', tags: ['单疗', '护盾'] },
  'renxin_hall_d1': { description: '箫声如潮抚慰心脉，群体治疗并净化全体减益、回气10点', origin: '《射雕英雄传》', stageName: '秘传', powerNote: '1.32', tags: ['群疗', 'cleanse', '回气'] },
  'renxin_hall_a2': { description: '弹指点穴，单体低伤害并点穴1秒', origin: '《射雕英雄传》', stageName: '初传', powerNote: '0.58', tags: ['单体', '点穴'] },
  'renxin_hall_b2': { description: '拂穴封脉，单体伤害并封穴2秒、驱散敌方1个增益', origin: '《射雕英雄传》', stageName: '进境', powerNote: '1.2', tags: ['单体', '封穴', 'dispel'] },
  'renxin_hall_c2': { description: '掌法如落英缤纷，三段连击，每段附带中毒1层（可叠3层）', origin: '《射雕英雄传》', stageName: '真传', powerNote: '1.85 ×3段(总1.83)', tags: ['单体', '连击', '中毒'] },
  'renxin_hall_d2': { description: '箫中藏剑潇洒狠辣，四段连击每段附毒，末段点穴1.5秒', origin: '《射雕英雄传》', stageName: '秘传', powerNote: '2.2 ×4段(总2.0)', tags: ['单体', '连击', '中毒', '点穴'] },
  'world_01_common_sword_01': { description: '剑走轻灵，两段连击', origin: '江湖流传', stageName: '通用', powerNote: '0.95 ×2段(总1.0)', tags: ['单体', '连击'] },
  'world_01_common_blade_01': { description: '刀法狠辣专断门路，单体伤害并破甲15%持续3秒', origin: '《天龙八部》', stageName: '通用', powerNote: '0.9', tags: ['单体', '破甲'] },
  'world_01_common_fist_01': { description: '大宋开国拳法，招式朴实稳健的单体重击', origin: '《天龙八部》（聚贤庄闻名）', stageName: '通用', powerNote: '0.95', tags: ['单体'] },
  'world_01_common_shadow_01': { description: '一把碎石如飞蝗扑面，群体低伤害', origin: '江湖流传', stageName: '通用', powerNote: '0.62', tags: ['群体'] },
  'world_01_common_doctor_01': { description: '金针刺穴活血，单体治疗并净化1个减益', origin: '江湖流传', stageName: '通用', powerNote: '0.81', tags: ['单疗', 'cleanse'] },
  'world_01_common_inner_01': { description: '硬功横练，自身受到伤害降低30%持续5秒', origin: '江湖流传', stageName: '通用', powerNote: '', tags: ['护体', '金钟'] },
  'qingfeng_hall_heart_01': { description: '玄门正宗循序渐进，偏重 gaugeRate 与 energyRecovery', origin: '《射雕英雄传》', stageName: '', powerNote: '', tags: [] },
  'tieyi_school_heart_01': { description: '丐帮弟子行脚天下，偏重 survivalBonus 与 gaugeRate', origin: '江湖流传', stageName: '', powerNote: '', tags: [] },
  'renxin_hall_heart_01': { description: '桃花岛医毒相济，偏重 energyRecovery 与 cooldownRate', origin: '江湖流传', stageName: '', powerNote: '', tags: [] },
  'world_01_heart_common': { description: '入门吐纳之术，均衡小幅提升 energyRecovery', origin: '江湖流传', stageName: '', powerNote: '', tags: [] },
  'duanlang_blade_a1': { description: '两段连击，如桨起桨落，每段威力 55%', origin: '江湖流传', stageName: '初传', powerNote: '1.25', tags: ['damage 单体', '连击2段'] },
  'duanlang_blade_b1': { description: '两段连击，末段刀锋划开伤口，附流血每秒 1% 持续 3 秒', origin: '江湖流传', stageName: '进境', powerNote: '1.50', tags: ['damage 单体', '连击2段、流血'] },
  'duanlang_blade_c1': { description: '三段连击逐浪递进，第三段刀风迟滞敌势，附迟缓 25% 持续 2 秒', origin: '江湖流传', stageName: '真传', powerNote: '2.05', tags: ['damage 单体', '连击3段、迟缓'] },
  'duanlang_blade_d1': { description: '四段连击后一记断浪重斩，末段附带点穴 1.5 秒', origin: '江湖流传', stageName: '秘传', powerNote: '2.40', tags: ['damage 单体', '连击4段、点穴'] },
  'duanlang_blade_a2': { description: '沉腰蓄劲一刀重劈，破甲 20% 持续 3 秒', origin: '江湖流传', stageName: '初传', powerNote: '1.15', tags: ['damage 单体', '破甲'] },
  'duanlang_blade_b2': { description: '刚猛横斩将敌劈退，击退并破甲 15% 持续 3 秒', origin: '江湖流传', stageName: '进境', powerNote: '1.50', tags: ['damage 单体', '击退、破甲'] },
  'duanlang_blade_c2': { description: '狂暴：自身生命低于 40% 时威力提升 30%，仿困兽之斗', origin: '江湖流传', stageName: '真传', powerNote: '1.85', tags: ['damage 单体', '狂暴'] },
  'duanlang_blade_d2': { description: '蓄力 1 秒后全力一刀，破甲 30% 并击退，低血时再获狂暴加成', origin: '江湖流传', stageName: '秘传', powerNote: '2.50', tags: ['damage 单体', '蓄力、破甲、击退、狂暴'] },
  'yexing_tower_a1': { description: '杖影如蛇两段连击，每段威力 55%', origin: '《射雕英雄传》', stageName: '初传', powerNote: '1.25', tags: ['damage 单体', '连击2段'] },
  'yexing_tower_b1': { description: '三段连击，杖头毒蛇撕咬，末段附流血每秒 1% 持续 3 秒', origin: '《射雕英雄传》', stageName: '进境', powerNote: '1.60', tags: ['damage 单体', '连击3段、流血'] },
  'yexing_tower_c1': { description: '劲透骨骼直取要穴，伤害减半，点穴 2.5 秒', origin: '《射雕英雄传》', stageName: '真传', powerNote: '0.95', tags: ['damage 单体', '点穴'] },
  'yexing_tower_d1': { description: '掌力挟雪山阴寒，高额单体伤害并迟缓 30% 持续 3 秒', origin: '《射雕英雄传》', stageName: '秘传', powerNote: '2.20', tags: ['damage 单体', '迟缓'] },
  'yexing_tower_a2': { description: '驱蛇啮敌，中毒每秒失去最大生命 0.8%，可叠 2 层，持续 4 秒', origin: '《射雕英雄传》', stageName: '初传', powerNote: '1.05', tags: ['damage 单体', '中毒'] },
  'yexing_tower_b2': { description: '臂如灵蛇两段连击，每段附加中毒 1 层', origin: '《射雕英雄传》', stageName: '进境', powerNote: '1.50', tags: ['damage 单体', '连击2段、中毒'] },
  'yexing_tower_c2': { description: '逆转经脉以毒攻毒：净化自身全部减益，每净化 1 个获攻击 +10% 持续 3 秒，自损 5% 生命为代价', origin: '《射雕英雄传》', stageName: '真传', powerNote: '', tags: ['cleanse 自身', '自损、减益转增益'] },
  'yexing_tower_d2': { description: '群蛇倾巢：群体中毒每秒失去最大生命 1%，可叠 3 层，持续 5 秒，并附迟缓 20%', origin: '江湖流传', stageName: '秘传', powerNote: '1.45', tags: ['damage 群体', '中毒、迟缓'] },
  'guiyuan_manor_a1': { description: '内劲贯注剑尖，轻灵单体内劲伤害', origin: '《神雕侠侣》', stageName: '初传', powerNote: '1.15', tags: ['damage 单体'] },
  'guiyuan_manor_b1': { description: '玉蜂针两段连击，针劲钻入内息，附破气 15% 持续 3 秒', origin: '《神雕侠侣》', stageName: '进境', powerNote: '1.60', tags: ['damage 单体', '连击2段、破气'] },
  'guiyuan_manor_c1': { description: '拳招拟古代美女仪态，内劲三段连击，每段威力 40%', origin: '《神雕侠侣》', stageName: '真传', powerNote: '2.05', tags: ['damage 单体', '连击3段'] },
  'guiyuan_manor_d1': { description: '双剑合璧之意：蓄力 1 秒后双剑齐出，高额内劲伤害并破气 30% 持续 3 秒', origin: '《神雕侠侣》', stageName: '秘传', powerNote: '2.50', tags: ['damage 单体', '蓄力、破气'] },
  'guiyuan_manor_a2': { description: '金铃索舞护周身，自身闪避提高 20% 持续 3 秒', origin: '《神雕侠侣》', stageName: '初传', powerNote: '', tags: ['guard 自身', '闪避'] },
  'guiyuan_manor_b2': { description: '掌势如天罗地网困敌，群体迟缓 25% 持续 3 秒并为自身套上护盾', origin: '《神雕侠侣》', stageName: '进境', powerNote: '0.80', tags: ['damage 群体', '迟缓、护盾'] },
  'guiyuan_manor_c2': { description: '寒玉淬体：金钟减伤 30% 持续 4 秒，期间每秒回复 1% 生命', origin: '江湖流传', stageName: '真传', powerNote: '', tags: ['heal 自身', '金钟、持续回复'] },
  'guiyuan_manor_d2': { description: '古墓护体绝艺：全体友方套上护盾，并反伤 15% 持续 4 秒', origin: '江湖流传', stageName: '秘传', powerNote: '', tags: ['guard 群体', '护盾、反伤'] },
  'world_02_common_sword_01': { description: '天地人三才连环，三段连击，每段威力 40%', origin: '江湖流传', stageName: '通用', powerNote: '1.10', tags: ['damage 单体', '连击3段'] },
  'world_02_common_blade_01': { description: '大开大阖走劈砍一路，破甲 15% 持续 3 秒', origin: '江湖流传', stageName: '通用', powerNote: '1.00', tags: ['damage 单体', '破甲'] },
  'world_02_common_fist_01': { description: '腿法连环两段连击，末段一记蹬踢击退目标', origin: '江湖流传', stageName: '通用', powerNote: '1.10', tags: ['damage 单体', '连击2段、击退'] },
  'world_02_common_shadow_01': { description: '袖中藏箭出其不意，附流血每秒 1% 持续 3 秒', origin: '江湖流传', stageName: '通用', powerNote: '1.00', tags: ['damage 单体', '流血'] },
  'world_02_common_doctor_01': { description: '推拿活气过血回阳，治疗单体并净化 1 个减益', origin: '江湖流传', stageName: '通用', powerNote: '1.00', tags: ['heal 单体', 'cleanse'] },
  'world_02_common_inner_01': { description: '佛门硬功金钟罩体，受到伤害降低 30% 持续 3 秒', origin: '江湖流传', stageName: '通用', powerNote: '', tags: ['guard 自身', '金钟'] },
  'duanlang_blade_heart_01': { description: '刀走轻灵、如潮起落：偏重 gaugeRate 与 momentumBonus，契合快刀连击节奏', origin: '江湖流传', stageName: '', powerNote: '', tags: [] },
  'yexing_tower_heart_01': { description: '蹲身蓄力、以静制动：偏重 survivalBonus，辅以 energyRecovery 支撑蓄力爆发', origin: '《射雕英雄传》', stageName: '', powerNote: '', tags: [] },
  'guiyuan_manor_heart_01': { description: '寒玉静修、气息绵长：偏重 energyRecovery 与 cooldownRate，续航出招两宜', origin: '《神雕侠侣》', stageName: '', powerNote: '', tags: [] },
  'world_02_heart_common': { description: '华山混元一气、内外兼修：五项均衡，略偏 survivalBonus', origin: '《碧血剑》', stageName: '', powerNote: '', tags: [] },
  'tingyu_sword_a1': { description: '二段连击吐出枣核，第二段附带流血（每秒当前生命1%，3秒）', origin: '《神雕侠侣》', stageName: '初传', powerNote: '', tags: ['单体', '连击、流血'] },
  'tingyu_sword_b1': { description: '三段连击，每段概率叠中毒1层（每秒最大生命0.8%，可叠2层，5秒）', origin: '《神雕侠侣》', stageName: '进境', powerNote: '', tags: ['单体', '连击、中毒'] },
  'tingyu_sword_c1': { description: '撒网困敌：敌方群体迟缓30%（4秒）并封穴1.5秒，附带少量伤害', origin: '《神雕侠侣》', stageName: '真传', powerNote: '', tags: ['群体', '迟缓、封穴'] },
  'tingyu_sword_d1': { description: '绝情断肠六段连击，段段递增，末段附带点穴1.5秒', origin: '江湖流传', stageName: '秘传', powerNote: '', tags: ['单体', '连击、点穴'] },
  'tingyu_sword_a2': { description: '刚猛单体重劈，附带击退一格打乱站位', origin: '江湖流传', stageName: '初传', powerNote: '', tags: ['单体', '击退'] },
  'tingyu_sword_b2': { description: '横扫敌方群体（单体威力的60%），附带击退', origin: '《神雕侠侣》（公孙止兵刃，阴阳倒乱刃法的前置铺垫）', stageName: '进境', powerNote: '', tags: ['群体', '击退'] },
  'tingyu_sword_c2': { description: '金刀锯齿撕裂：破甲30%（6秒）并附带流血（每秒当前生命1.2%，4秒）', origin: '江湖流传', stageName: '真传', powerNote: '', tags: ['单体', '破甲、流血'] },
  'tingyu_sword_d2': { description: '金刀黑剑倒乱齐出：两段连击，首段破甲25%（5秒），并进入狂暴（自身生命<50%时威力+40%）', origin: '《神雕侠侣》', stageName: '秘传', powerNote: '', tags: ['单体', '连击、破甲、狂暴'] },
  'feixing_dock_a1': { description: '召唤豹影突袭：二段连击，末段流血（每秒当前生命1%，3秒）', origin: '江湖流传', stageName: '初传', powerNote: '', tags: ['单体', '召唤、连击、流血'] },
  'feixing_dock_b1': { description: '召唤青狼：单体伤害并挂破绽标记（友方对其伤害加深15%，触发后消失）', origin: '江湖流传', stageName: '进境', powerNote: '', tags: ['单体', '召唤、破绽标记'] },
  'feixing_dock_c1': { description: '召唤苍鹰俯冲：三段连击，末段点穴1秒', origin: '江湖流传', stageName: '真传', powerNote: '', tags: ['单体', '召唤、连击、点穴'] },
  'feixing_dock_d1': { description: '召唤猛虎扑杀：四段连击高额点杀，末段流血（每秒当前生命1.5%，4秒），虎啸附带敌方群体迟缓20%（3秒）', origin: '江湖流传', stageName: '秘传', powerNote: '', tags: ['单体', '召唤、连击、流血、迟缓'] },
  'feixing_dock_a2': { description: '召唤毒蛇啮咬：单体伤害并叠中毒1层（每秒最大生命0.8%，可叠3层，6秒）', origin: '江湖流传', stageName: '初传', powerNote: '', tags: ['单体', '召唤、中毒'] },
  'feixing_dock_b2': { description: '毒针暗袭：叠中毒2层并迟缓25%（4秒）', origin: '江湖流传', stageName: '进境', powerNote: '', tags: ['单体', '中毒、迟缓'] },
  'feixing_dock_c2': { description: '毒瘴弥漫：敌方群体叠中毒1层（每秒最大生命0.7%，可叠2层，6秒）', origin: '江湖流传', stageName: '真传', powerNote: '', tags: ['群体', '中毒'] },
  'feixing_dock_d2': { description: '百兽齐出朝拜兽王：群体伤害并叠中毒2层，兽王追加一段高额单体伤害', origin: '江湖流传', stageName: '秘传', powerNote: '', tags: ['群体', '召唤、中毒、连击'] },
  'tiaoxi_court_a1': { description: '阴寒内劲单体伤害，附带迟缓20%（3秒）', origin: '《射雕英雄传》', stageName: '初传', powerNote: '', tags: ['单体', '迟缓'] },
  'tiaoxi_court_b1': { description: '运诀蓄力1秒后释放内劲爆发，威力加成50%', origin: '《射雕英雄传》', stageName: '进境', powerNote: '', tags: ['单体', '蓄力'] },
  'tiaoxi_court_c1': { description: '掌力凌顶：敌方群体内劲伤害（单体威力60%）并破气20%（5秒）', origin: '《射雕英雄传》', stageName: '真传', powerNote: '', tags: ['群体', '破气'] },
  'tiaoxi_court_d1': { description: '精气神三花聚顶：蓄力1.5秒后打出极高单体内劲，附带破气40%（6秒）', origin: '《射雕英雄传》', stageName: '秘传', powerNote: '', tags: ['单体', '蓄力、破气'] },
  'tiaoxi_court_a2': { description: '身法凌云：自身闪避率提高35%（4秒）', origin: '《射雕英雄传》', stageName: '初传', powerNote: '', tags: ['护体', '闪避'] },
  'tiaoxi_court_b2': { description: '重阳真人遗刻参悟：为全体友方套上护盾（吸收量为自身生命10%，5秒）', origin: '江湖流传', stageName: '进境', powerNote: '', tags: ['护体', '护盾'] },
  'tiaoxi_court_c2': { description: '罡气护体：自身金钟减伤50%（5秒），并反伤20%', origin: '江湖流传', stageName: '真传', powerNote: '', tags: ['护体', '金钟、反伤'] },
  'tiaoxi_court_d2': { description: '阵法：需我方存活≥3人方可施放；全体金钟减伤30%（6秒）+反伤25%，阵成时全体回气15点', origin: '《射雕英雄传》', stageName: '秘传', powerNote: '', tags: ['护体', '阵法、金钟、反伤、回气'] },
  'world_03_common_sword_01': { description: '阴阳两仪二段连击，刚柔各一段', origin: '《倚天屠龙记》', stageName: '通用', powerNote: '', tags: ['单体', '连击'] },
  'world_03_common_blade_01': { description: '八卦游走横扫，敌方群体伤害（单体威力60%）', origin: '江湖流传', stageName: '通用', powerNote: '', tags: ['群体'] },
  'world_03_common_fist_01': { description: '五行连环单体拳击，附带破甲15%（4秒）', origin: '江湖流传', stageName: '通用', powerNote: '', tags: ['单体', '破甲'] },
  'world_03_common_shadow_01': { description: '铁莲子连珠打出：二段连击，末段流血（每秒当前生命1%，3秒）', origin: '江湖流传', stageName: '通用', powerNote: '', tags: ['单体', '连击、流血'] },
  'world_03_common_doctor_01': { description: '妙手回春：治疗友方单体（威力即治疗量系数）', origin: '江湖流传', stageName: '通用', powerNote: '', tags: ['单疗'] },
  'world_03_common_inner_01': { description: '童子筑基内劲：单体内劲伤害并破气15%（4秒）', origin: '江湖流传', stageName: '通用', powerNote: '', tags: ['单体', '破气'] },
  'tingyu_sword_heart_01': { description: '闭守周身穴道，偏重 survivalBonus + cooldownRate（穴道自闭、毒点难侵，契合绝情谷毒控对耗）', origin: '《神雕侠侣》', stageName: '', powerNote: '', tags: [] },
  'feixing_dock_heart_01': { description: '驭兽助战、行动如兽，偏重 gaugeRate + momentumBonus（行动条与气势增长更快）', origin: '江湖流传', stageName: '', powerNote: '', tags: [] },
  'tiaoxi_court_heart_01': { description: '玄门内功宗源，偏重 energyRecovery + gaugeRate（真气绵长、气息生生不息）', origin: '《射雕英雄传》', stageName: '', powerNote: '', tags: [] },
  'world_03_heart_common': { description: '华山正宗内功，偏重 energyRecovery + momentumBonus（蓄劲发劲、绵里藏针）', origin: '《笑傲江湖》', stageName: '', powerNote: '', tags: [] },
  'zhenyue_blade_a1': { description: '剑气单体伤害，附带破气10%持续4秒', origin: '《天龙八部》', stageName: '初传', powerNote: '1.15', tags: ['单体', '破气'] },
  'zhenyue_blade_b1': { description: '两段连击，每段55%，灵动巧妙', origin: '《天龙八部》', stageName: '进境', powerNote: '1.65', tags: ['单体', '连击'] },
  'zhenyue_blade_c1': { description: '蓄力1.5秒后释放大开大阖的一剑，高爆发', origin: '《天龙八部》', stageName: '真传', powerNote: '2.10', tags: ['单体', '蓄力'] },
  'zhenyue_blade_d1': { description: '古拙雄劲的三段连击，每段40%，末段附带破气20%持续6秒', origin: '《天龙八部》', stageName: '秘传', powerNote: '2.40', tags: ['单体', '连击、破气'] },
  'zhenyue_blade_a2': { description: '为友方单体套上护盾，吸收量按威力换算', origin: '《天龙八部》', stageName: '初传', powerNote: '1.15', tags: ['护盾·单体'] },
  'zhenyue_blade_b2': { description: '自身金钟，5秒内受到伤害降低30%', origin: '《天龙八部》', stageName: '进境', powerNote: '', tags: ['金钟'] },
  'zhenyue_blade_c2': { description: '5秒内将受到的伤害30%反弹给攻击者', origin: '《天龙八部》', stageName: '真传', powerNote: '', tags: ['反伤'] },
  'zhenyue_blade_d2': { description: '全队护盾，并附带加速15%持续5秒（一品境界护佑全军）', origin: '《天龙八部》', stageName: '秘传', powerNote: '1.45', tags: ['护盾·群体', '加速'] },
  'mianshan_school_a1': { description: '单体治疗，禅音抚平伤势', origin: '江湖流传', stageName: '初传', powerNote: '1.15', tags: ['单疗'] },
  'mianshan_school_b1': { description: '单体治疗并净化1个减益状态', origin: '江湖流传', stageName: '进境', powerNote: '1.50', tags: ['单疗', 'cleanse'] },
  'mianshan_school_c1': { description: '群体治疗，治疗量约为单体的60%', origin: '江湖流传', stageName: '真传', powerNote: '1.10', tags: ['群疗'] },
  'mianshan_school_d1': { description: '复活一名阵亡友方并恢复其30%生命', origin: '江湖流传', stageName: '秘传', powerNote: '', tags: ['revive'] },
  'mianshan_school_a2': { description: '指劲单体伤害，附带中毒1层（每秒1%最大生命，持续6秒）', origin: '《天龙八部》', stageName: '初传', powerNote: '1.15', tags: ['单体', '中毒'] },
  'mianshan_school_b2': { description: '无形指力伤害，附带封穴2秒（无法施放武功）', origin: '《天龙八部》', stageName: '进境', powerNote: '0.95', tags: ['单体', '封穴'] },
  'mianshan_school_c2': { description: '刀气群体伤害，附带火毒（中毒1层持续6秒）', origin: '《天龙八部》', stageName: '真传', powerNote: '1.10', tags: ['群体', '中毒'] },
  'mianshan_school_d2': { description: '阵法：我方存活≥3人方可施放，六道剑气群体伤害', origin: '《天龙八部》', stageName: '秘传', powerNote: '1.45', tags: ['群体', '阵法'] },
  'baicao_hall_a1': { description: '两段连击，每段55%，出手迅捷', origin: '《天龙八部》', stageName: '初传', powerNote: '1.25', tags: ['单体', '连击'] },
  'baicao_hall_b1': { description: '剪伤单体，附带流血（每秒1%当前生命，持续5秒）', origin: '《天龙八部》', stageName: '进境', powerNote: '1.50', tags: ['单体', '流血'] },
  'baicao_hall_c1': { description: '腹语惑敌：单体伤害减半，附带点穴1.5秒', origin: '《天龙八部》', stageName: '真传', powerNote: '0.95', tags: ['单体', '点穴'] },
  'baicao_hall_d1': { description: '铁杖重击单体，附带点穴2秒与封穴2秒，一击制敌', origin: '江湖流传', stageName: '秘传', powerNote: '1.60', tags: ['单体', '点穴、封穴'] },
  'baicao_hall_a2': { description: '掌挟蝎毒：单体伤害，附带中毒1层持续6秒', origin: '江湖流传', stageName: '初传', powerNote: '1.15', tags: ['单体', '中毒'] },
  'baicao_hall_b2': { description: '撒出毒砂：群体小额伤害，附带中毒1层持续6秒', origin: '江湖流传', stageName: '进境', powerNote: '0.90', tags: ['群体', '中毒'] },
  'baicao_hall_c2': { description: '两段连击（每段50%），鞭上淬毒，附带中毒2层', origin: '《天龙八部》', stageName: '真传', powerNote: '1.85', tags: ['单体', '连击、中毒'] },
  'baicao_hall_d2': { description: '群毒爆发：群体伤害并叠中毒2层，同时驱散敌方全体1个增益（以毒攻毒）', origin: '江湖流传', stageName: '秘传', powerNote: '1.45', tags: ['群体', 'dispel', '中毒'] },
  'world_04_common_sword_01': { description: '一剑破势：单体伤害，附带破甲10%持续4秒', origin: '《倚天屠龙记》', stageName: '通用', powerNote: '1.10', tags: ['单体', '破甲'] },
  'world_04_common_blade_01': { description: '滚地近身：单体伤害，附带击退打乱站位', origin: '江湖流传', stageName: '通用', powerNote: '1.10', tags: ['单体', '击退'] },
  'world_04_common_fist_01': { description: '放长击远：两段连击，每段55%', origin: '江湖流传', stageName: '通用', powerNote: '1.20', tags: ['单体', '连击'] },
  'world_04_common_shadow_01': { description: '五瓣梅花：单体伤害，附带中毒1层持续5秒', origin: '江湖流传', stageName: '通用', powerNote: '1.10', tags: ['单体', '中毒'] },
  'world_04_common_doctor_01': { description: '金针度穴：单体治疗', origin: '江湖流传', stageName: '通用', powerNote: '1.10', tags: ['单疗'] },
  'world_04_common_inner_01': { description: '龟息蛰伏：为自身套上护盾，吸收量按威力换算', origin: '江湖流传', stageName: '通用', powerNote: '1.10', tags: ['护盾·单体'] },
  'zhenyue_blade_heart_01': { description: '段氏内家根基，偏重 gaugeRate + momentumBonus（剑气积蓄更快）', origin: '江湖流传', stageName: '', powerNote: '', tags: [] },
  'mianshan_school_heart_01': { description: '枯荣之间生生不息，偏重 survivalBonus + energyRecovery', origin: '《天龙八部》', stageName: '', powerNote: '', tags: [] },
  'baicao_hall_heart_01': { description: '恶徒狠辣路数，偏重 momentumBonus + cooldownRate（出手更频）', origin: '江湖流传', stageName: '', powerNote: '', tags: [] },
  'world_04_heart_common': { description: '血刀门镇门内功，偏重 survivalBonus + energyRecovery', origin: '《连城诀》', stageName: '', powerNote: '', tags: [] },
  'cangfeng_manor_a1': { description: '三路擒拿化打一体，单体内劲伤害并破气 20% 持续 4 秒', origin: '《天龙八部》', stageName: '初传', powerNote: '1.15', tags: ['单体', '破气'] },
  'cangfeng_manor_b1': { description: '蓄力 1 秒后释放纯阳内劲，单体高额伤害', origin: '《天龙八部》', stageName: '进境', powerNote: '1.73', tags: ['单体', '蓄力'] },
  'cangfeng_manor_c1': { description: '冰片入体，中毒每秒 1% 最大生命可叠 2 层持续 6 秒，并迟缓 20% 持续 4 秒', origin: '《天龙八部》', stageName: '真传', powerNote: '0.93', tags: ['单体', '中毒、迟缓'] },
  'cangfeng_manor_d1': { description: '掌力曲直如意，群体内劲伤害并破气 30% 持续 5 秒，承天山六阳掌纯阳之劲而化刚为曲', origin: '《天龙八部》', stageName: '秘传', powerNote: '1.32', tags: ['群体', '破气'] },
  'cangfeng_manor_a2': { description: '自身闪避率提高 30%，持续 6 秒', origin: '《天龙八部》', stageName: '初传', powerNote: '0', tags: ['闪避'] },
  'cangfeng_manor_b2': { description: '袖风拂要穴，点穴 1.5 秒并附少量伤害', origin: '《天龙八部》', stageName: '进境', powerNote: '0.75', tags: ['单体', '点穴'] },
  'cangfeng_manor_c2': { description: '音波扰神，敌方群体迟缓 25% 持续 4 秒，并驱散其 1 个增益', origin: '《天龙八部》', stageName: '真传', powerNote: '0', tags: ['驱散', '迟缓'] },
  'cangfeng_manor_d2': { description: '无相无形：自身受到伤害降低 40% 持续 6 秒，并以 50% 威力复制目标上一个武功', origin: '《天龙八部》', stageName: '秘传', powerNote: '0', tags: ['金钟、复制'] },
  'hengjiang_blade_a1': { description: '两段连击，轻灵刺击', origin: '《越女剑》', stageName: '初传', powerNote: '1.27', tags: ['单体', '连击'] },
  'hengjiang_blade_b1': { description: '三段连击，剑影如白猿扑击，末段附带流血每秒 1% 当前生命持续 4 秒', origin: '《越女剑》意象衍生', stageName: '进境', powerNote: '1.65', tags: ['单体', '连击、流血'] },
  'hengjiang_blade_c1': { description: '三段连击，第三段棒点要穴点穴 1 秒，承越女剑法连击之势而增制敌之效', origin: '《越女剑》意象衍生', stageName: '真传', powerNote: '1.53', tags: ['单体', '连击、点穴'] },
  'hengjiang_blade_d1': { description: '五段连击如猿公亲授，总威力为同阶单体 1.1 倍，末段附流血每秒 1.5% 当前生命持续 5 秒', origin: '《越女剑》', stageName: '秘传', powerNote: '2.42', tags: ['单体', '连击、流血'] },
  'hengjiang_blade_a2': { description: '单体伤害并破甲 20% 持续 4 秒，剑走奇险', origin: '《碧血剑》', stageName: '初传', powerNote: '1.15', tags: ['单体', '破甲'] },
  'hengjiang_blade_b2': { description: '剑随身走，单体伤害并将目标击退一位', origin: '《碧血剑》', stageName: '进境', powerNote: '1.50', tags: ['单体', '击退'] },
  'hengjiang_blade_c2': { description: '锥形剑气透甲，破甲 30% 持续 5 秒并易伤 10% 持续 4 秒', origin: '《碧血剑》', stageName: '真传', powerNote: '1.67', tags: ['单体', '破甲、易伤'] },
  'hengjiang_blade_d2': { description: '蓄力 1.5 秒后金蛇吞噬一击，破甲 40% 持续 6 秒，集游身、锥影之大成', origin: '《碧血剑》', stageName: '秘传', powerNote: '2.53', tags: ['单体', '蓄力、破甲'] },
  'xinglin_valley_a1': { description: '两段连击，自暗处伏杀突袭', origin: '江湖流传', stageName: '初传', powerNote: '1.27', tags: ['单体', '连击'] },
  'xinglin_valley_b1': { description: '三段连击，刀轮绞割附流血每秒 1% 当前生命持续 4 秒', origin: '江湖流传', stageName: '进境', powerNote: '1.65', tags: ['单体', '连击、流血'] },
  'xinglin_valley_c1': { description: '刀阵锁敌：给目标挂破绽标记（友方伤害加深 15%），再三段连击点杀', origin: '江湖流传', stageName: '真传', powerNote: '1.85', tags: ['单体', '连击、破绽标记'] },
  'xinglin_valley_d1': { description: '四段连击天罗罩顶，末段点穴 1.5 秒，机关刀阵杀着之最', origin: '江湖流传', stageName: '秘传', powerNote: '2.42', tags: ['单体', '连击、点穴'] },
  'xinglin_valley_a2': { description: '貂毒入体，中毒每秒 1% 最大生命持续 5 秒，可叠 1 层', origin: '《天龙八部》', stageName: '初传', powerNote: '0.58', tags: ['单体', '中毒'] },
  'xinglin_valley_b2': { description: '万毒之王，中毒每秒 1.2% 最大生命可叠 2 层持续 6 秒', origin: '《天龙八部》', stageName: '进境', powerNote: '0.75', tags: ['单体', '中毒'] },
  'xinglin_valley_c2': { description: '中毒每秒 1% 最大生命可叠 3 层持续 6 秒，并迟缓 25% 持续 4 秒', origin: '《天龙八部》', stageName: '真传', powerNote: '0.93', tags: ['单体', '中毒、迟缓'] },
  'xinglin_valley_d2': { description: '群体中毒每秒 1.5% 最大生命可叠 3 层持续 8 秒，诸毒齐发令敌万劫不复', origin: '江湖流传', stageName: '秘传', powerNote: '1.10', tags: ['群体', '中毒'] },
  'world_05_common_sword_01': { description: '两段连击，剑势如松间清风连绵不断', origin: '《笑傲江湖》', stageName: '通用', powerNote: '1.27', tags: ['单体', '连击'] },
  'world_05_common_blade_01': { description: '三段连击，刀势如狂风骤雨', origin: '《笑傲江湖》', stageName: '通用', powerNote: '1.27', tags: ['单体', '连击'] },
  'world_05_common_fist_01': { description: '两段连击，双拳翻飞密不透风', origin: '江湖流传', stageName: '通用', powerNote: '1.27', tags: ['单体', '连击'] },
  'world_05_common_shadow_01': { description: '单体伤害并附流血每秒 1% 当前生命持续 4 秒', origin: '江湖流传', stageName: '通用', powerNote: '1.15', tags: ['单体', '流血'] },
  'world_05_common_doctor_01': { description: '治疗友方单体并净化 1 个减益', origin: '《黄帝内经·素问》典故', stageName: '通用', powerNote: '1.15', tags: ['单疗', 'cleanse'] },
  'world_05_common_inner_01': { description: '自身闪避率提高 20%，持续 5 秒', origin: '江湖流传', stageName: '通用', powerNote: '0', tags: ['闪避'] },
  'cangfeng_manor_heart_01': { description: '吸内倾向：偏重 energyRecovery，辅以 momentumBonus——纳人内力为己用，真气回转与战意积累双优', origin: '《天龙八部》', stageName: '', powerNote: '', tags: [] },
  'hengjiang_blade_heart_01': { description: '统御九天九部之规：偏重 gaugeRate 与 cooldownRate，行动条与技能轮转更快', origin: '江湖流传', stageName: '', powerNote: '', tags: [] },
  'xinglin_valley_heart_01': { description: '以毒养身：偏重 survivalBonus，辅以 momentumBonus——毒功护体、败中求胜', origin: '江湖流传', stageName: '', powerNote: '', tags: [] },
  'world_05_heart_common': { description: '王怜花毕生所学，博而均衡：energyRecovery / gaugeRate / cooldownRate 三项兼顾', origin: '《多情剑客无情剑》', stageName: '', powerNote: '', tags: [] },
  'zhenshan_gate_a1': { description: '二段连击，第一段威力 40%、第二段 60%，出手即中', origin: '《边城浪子》', stageName: '初传', powerNote: '1.27', tags: ['damage 单体', '连击×2'] },
  'zhenshan_gate_b1': { description: '单段突斩，命中附带流血（每秒当前生命 1.5%，持续 4 秒）', origin: '《边城浪子》', stageName: '进境', powerNote: '1.20', tags: ['damage 单体', '流血'] },
  'zhenshan_gate_c1': { description: '三段连击，第三段附带点穴 1.5 秒', origin: '《天涯·明月·刀》', stageName: '真传', powerNote: '1.40', tags: ['damage 单体', '连击×3、点穴'] },
  'zhenshan_gate_d1': { description: '四段连击，第三段破甲 25%（6 秒），末段点穴 2 秒', origin: '《边城浪子》', stageName: '秘传', powerNote: '2.42', tags: ['damage 单体', '连击×4、破甲、点穴'] },
  'zhenshan_gate_a2': { description: '单体重斩，附带破甲 20%（5 秒）', origin: '江湖流传', stageName: '初传', powerNote: '1.00', tags: ['damage 单体', '破甲'] },
  'zhenshan_gate_b2': { description: '群体横扫并击退敌方前排，打乱阵型', origin: '江湖流传', stageName: '进境', powerNote: '0.90', tags: ['damage 群体', '击退'] },
  'zhenshan_gate_c2': { description: '单体重击，自身生命低于 40% 时威力提升 50%（狂暴）', origin: '江湖流传', stageName: '真传', powerNote: '1.85', tags: ['damage 单体', '狂暴'] },
  'zhenshan_gate_d2': { description: '金、银、铜、铁、铅五轮齐出：五段群体连击，末段附带破气 25%（6 秒）', origin: '《神雕侠侣》', stageName: '秘传', powerNote: '1.45', tags: ['damage 群体', '连击×5、破气'] },
  'wuteng_stockade_a1': { description: '单体重掌，附带击退', origin: '《射雕英雄传》', stageName: '初传', powerNote: '1.15', tags: ['damage 单体', '击退'] },
  'wuteng_stockade_b1': { description: '群体掌风，附带击退敌方全体', origin: '《射雕英雄传》', stageName: '进境', powerNote: '0.90', tags: ['damage 群体', '击退'] },
  'wuteng_stockade_c1': { description: '蓄劲重掌，附带破甲 25%（6 秒）', origin: '《射雕英雄传》', stageName: '真传', powerNote: '1.60', tags: ['damage 单体', '破甲'] },
  'wuteng_stockade_d1': { description: '双掌齐出：二段连击，每段附带破甲 15%（可叠，6 秒），末段击退', origin: '《射雕英雄传》', stageName: '秘传', powerNote: '2.42', tags: ['damage 单体', '连击×2、破甲、击退'] },
  'wuteng_stockade_a2': { description: '棒影缠身，低伤害并迟缓目标（行动条速率 -30%，5 秒）', origin: '《射雕英雄传》', stageName: '初传', powerNote: '0.70', tags: ['damage 单体', '迟缓'] },
  'wuteng_stockade_b2': { description: '巧劲挑击，附带中毒（每秒最大生命 1.2%，可叠 2 层，6 秒）', origin: '《射雕英雄传》', stageName: '进境', powerNote: '1.00', tags: ['damage 单体', '中毒'] },
  'wuteng_stockade_c2': { description: '棒封要穴，封穴 3 秒并附带中毒（每秒最大生命 1.0%，6 秒）', origin: '《射雕英雄传》', stageName: '真传', powerNote: '0.95', tags: ['damage 单体', '封穴、中毒'] },
  'wuteng_stockade_d2': { description: '棒势圆转：借力转移下一次受到的攻击，并对敌方群体下毒（每秒最大生命 1.0%，可叠 2 层，6 秒）', origin: '《射雕英雄传》', stageName: '秘传', powerNote: '0.75', tags: ['damage 群体', '借力、中毒'] },
  'baoyuan_temple_a1': { description: '单体治疗，并附带少量持续恢复感（以威力体现）', origin: '《射雕英雄传》', stageName: '初传', powerNote: '1.15', tags: ['heal 单体'] },
  'baoyuan_temple_b1': { description: '单体治疗并净化 1 个减益', origin: '《射雕英雄传》', stageName: '进境', powerNote: '1.30', tags: ['heal 单体', 'cleanse'] },
  'baoyuan_temple_c1': { description: '笔指合一：群体治疗并净化全体各 1 个减益', origin: '《神雕侠侣》', stageName: '真传', powerNote: '1.10', tags: ['heal 群体', 'cleanse'] },
  'baoyuan_temple_d1': { description: '渔樵耕读四艺齐施：复活 1 名阵亡友方，群体治疗并加护盾（吸收量为治疗量 30%，6 秒）', origin: '《神雕侠侣》', stageName: '秘传', powerNote: '1.45', tags: ['revive', 'heal 群体', '护盾'] },
  'baoyuan_temple_a2': { description: '琴音乱心，迟缓目标（行动条速率 -30%，5 秒）', origin: '《射雕英雄传》', stageName: '初传', powerNote: '0.60', tags: ['damage 单体', '迟缓'] },
  'baoyuan_temple_b2': { description: '棋势锁困，封穴 3 秒并附带中毒（每秒最大生命 1.0%，6 秒）', origin: '《射雕英雄传》', stageName: '进境', powerNote: '0.75', tags: ['damage 单体', '封穴、中毒'] },
  'baoyuan_temple_c2': { description: '草书一笔点落，点穴 2 秒并驱散目标 1 个增益', origin: '《神雕侠侣》', stageName: '真传', powerNote: '0.90', tags: ['damage 单体', 'dispel', '点穴'] },
  'baoyuan_temple_d2': { description: '琴棋书画齐发：敌方群体中毒（每秒最大生命 1.2%，可叠 2 层，6 秒）并迟缓（-25%，5 秒），驱散敌方全体各 1 个增益', origin: '《神雕侠侣》', stageName: '秘传', powerNote: '0.80', tags: ['damage 群体', 'dispel', '中毒、迟缓'] },
  'world_06_common_sword_01': { description: '剑走轻灵幻变：三段连击，附带闪避提升 15%（4 秒）', origin: '《笑傲江湖》', stageName: '通用', powerNote: '1.32', tags: ['damage 单体', '连击×3、闪避'] },
  'world_06_common_blade_01': { description: '军中制式刀法：单体重斩，附带破甲 15%（5 秒）', origin: '江湖流传', stageName: '通用', powerNote: '1.05', tags: ['damage 单体', '破甲'] },
  'world_06_common_fist_01': { description: '大开大阖的单体重拳，附带击退', origin: '江湖流传', stageName: '通用', powerNote: '1.20', tags: ['damage 单体', '击退'] },
  'world_06_common_shadow_01': { description: '暗器淬毒：单体伤害并中毒（每秒最大生命 1.0%，可叠 2 层，6 秒）', origin: '江湖流传', stageName: '通用', powerNote: '0.80', tags: ['damage 单体', '中毒'] },
  'world_06_common_doctor_01': { description: '群体治疗', origin: '江湖流传', stageName: '通用', powerNote: '0.75', tags: ['heal 群体'] },
  'world_06_common_inner_01': { description: '横练护体：自身金钟减伤 30%（6 秒），并微量自疗', origin: '江湖流传', stageName: '通用', powerNote: '0.50', tags: ['heal 自身', '金钟'] },
  'zhenshan_gate_heart_01': { description: '密宗刚猛内劲：偏重 momentumBonus（气势增益）与 survivalBonus（生存增益），契合狂刀越战越勇', origin: '《神雕侠侣》', stageName: '', powerNote: '', tags: [] },
  'wuteng_stockade_heart_01': { description: '丐帮硬桥硬马的桩功：偏重 survivalBonus 与 energyRecovery（真气回复），支撑刚拳高频出掌', origin: '江湖流传', stageName: '', powerNote: '', tags: [] },
  'baoyuan_temple_heart_01': { description: '佛门禅定之功：偏重 energyRecovery 与 cooldownRate（冷却加速），利于医术轮转施放', origin: '《神雕侠侣》', stageName: '', powerNote: '', tags: [] },
  'world_06_heart_common': { description: '破而后立、为他人作嫁：偏重 survivalBonus 与 gaugeRate（行动条速率），残血时韧性更足', origin: '《绝代双骄》', stageName: '', powerNote: '', tags: [] },
  'wanren_court_a1': { description: '鹰爪锁喉重击，附带破绽标记（友方对其伤害加深 15%）', origin: '《倚天屠龙记》（殷天正）', stageName: '初传', powerNote: '1.15', tags: ['damage 单体', '破绽'] },
  'wanren_court_b1': { description: '七伤皆损：自损当前生命 5%，换来破甲 25%/4 秒的重拳', origin: '《倚天屠龙记》（谢逊）', stageName: '进境', powerNote: '1.72', tags: ['damage 单体', '自损、破甲'] },
  'wanren_court_c1': { description: '三段连击（0.4/0.35/0.35），掌势层层推进，末段击退乱阵', origin: '《倚天屠龙记》（阳顶天）', stageName: '真传', powerNote: '2.04', tags: ['damage 单体', '连击、击退'] },
  'wanren_court_d1': { description: '借力：将下一次受到的攻击转移给敌方随机目标，随后顺势反击一拳', origin: '《倚天屠龙记》', stageName: '秘传', powerNote: '1.10', tags: ['damage 单体', '借力'] },
  'wanren_court_a2': { description: '寒毒入体：中毒（每秒 0.8% 最大生命，8 秒）并迟缓 20%/4 秒', origin: '《倚天屠龙记》（韦一笑）', stageName: '初传', powerNote: '0.92', tags: ['damage 单体', '中毒、迟缓'] },
  'wanren_court_b2': { description: '两段连击（0.55/0.55），蝠影过处每段附加中毒 1 层（可叠 3 层）', origin: '江湖流传（青翼蝠王身法衍化）', stageName: '进境', powerNote: '1.20', tags: ['damage 单体', '连击、中毒'] },
  'wanren_court_c2': { description: '诡招旁出：破气 20%/5 秒，并使目标易伤 15%/5 秒', origin: '《倚天屠龙记》（波斯明教遗刻）', stageName: '真传', powerNote: '1.57', tags: ['damage 单体', '破气、易伤'] },
  'wanren_court_d2': { description: '焚我残躯，熊熊圣火：自损当前生命 12%，群体烈焰灼烧并附加中毒 2 层', origin: '江湖流传（圣火令歌诀衍化）', stageName: '秘传', powerNote: '1.43', tags: ['damage 群体', '自损、中毒'] },
  'juezong_gate_a1': { description: '内劲吐力，掌至破气 15%/3 秒', origin: '《倚天屠龙记》', stageName: '初传', powerNote: '1.15', tags: ['damage 单体', '破气'] },
  'juezong_gate_b1': { description: '借力：卸转下一次受到的攻击予敌方随机目标，并以六成威力反震', origin: '江湖流传（太极劲意衍化）', stageName: '进境', powerNote: '0.90', tags: ['damage 单体', '借力'] },
  'juezong_gate_c1': { description: '蓄力 1.2 秒后铁掌震空，威力加成并破气 25%/4 秒', origin: '江湖流传（武当刚劲一面）', stageName: '真传', powerNote: '2.22', tags: ['damage 单体', '蓄力、破气'] },
  'juezong_gate_d1': { description: '蓄力 1.5 秒，圆转如意：高额内劲一击，同时借力卸去下一次攻击', origin: '《倚天屠龙记》（张三丰晚年所创）', stageName: '秘传', powerNote: '2.42', tags: ['damage 单体', '蓄力、借力'] },
  'juezong_gate_a2': { description: '身法登云：自身闪避提高 30%/5 秒', origin: '《倚天屠龙记》', stageName: '初传', powerNote: '0.40', tags: ['guard 自身', '闪避'] },
  'juezong_gate_b2': { description: '以攻为守：虎爪点穴 1.2 秒，并为自身套上小额护盾', origin: '《倚天屠龙记》', stageName: '进境', powerNote: '0.75', tags: ['damage 单体', '点穴、护盾'] },
  'juezong_gate_c2': { description: '为气血最低的友方套护盾（吸收量随威力缩放），并附金钟减伤 15%/4 秒', origin: '江湖流传（两仪劲意衍化）', stageName: '真传', powerNote: '1.85', tags: ['heal 单体', '护盾、金钟'] },
  'juezong_gate_d2': { description: '阵法：需我方存活 ≥3 人方可施放，全体护盾并获得加速 15%/6 秒', origin: '《倚天屠龙记》', stageName: '秘传', powerNote: '2.20', tags: ['guard 群体', '阵法、护盾、加速'] },
  'jingmai_court_a1': { description: '两段连击（0.55/0.55），剑势绵密如缕', origin: '《倚天屠龙记》', stageName: '初传', powerNote: '1.15', tags: ['damage 单体', '连击'] },
  'jingmai_court_b1': { description: '三段连击（0.4/0.35/0.35），专截腕脉，末段封穴 2 秒（仅可普攻）', origin: '《倚天屠龙记》（灭绝师太）', stageName: '进境', powerNote: '1.10', tags: ['damage 单体', '连击、封穴'] },
  'jingmai_court_c1': { description: '灭剑式·剑出无回：高威力直刺，附加流血（每秒 1% 当前生命，5 秒）', origin: '《倚天屠龙记》（灭绝师太双剑之一）', stageName: '真传', powerNote: '1.85', tags: ['damage 单体', '流血'] },
  'jingmai_court_d1': { description: '灭尽绝尘：四段连击（0.3×2/0.2×2），末段点穴 1.5 秒，对流血中的目标伤害加深 20%', origin: '《倚天屠龙记》（灭绝师太双剑之一）', stageName: '秘传', powerNote: '2.00', tags: ['damage 单体', '连击、点穴、易伤'] },
  'jingmai_court_a2': { description: '掌剑齐施横扫群体（单体威力的 60%），金光照处破甲 15%/3 秒', origin: '《倚天屠龙记》', stageName: '初传', powerNote: '0.69', tags: ['damage 群体', '破甲'] },
  'jingmai_court_b2': { description: '倚天之利，无坚不摧：单体重斩破甲 30%/5 秒', origin: '江湖流传（倚天神兵剑招衍化）', stageName: '进境', powerNote: '1.65', tags: ['damage 单体', '破甲'] },
  'jingmai_court_c2': { description: '鞭势如蟒缠身：两段连击（0.5/0.5），末段击退并迟缓 15%/4 秒', origin: '《倚天屠龙记》（周芷若，九阴真经所载）', stageName: '真传', powerNote: '1.85', tags: ['damage 单体', '连击、击退、迟缓'] },
  'jingmai_court_d2': { description: '狠爪透颅：高威力破甲 25%/4 秒并附加流血，对生命低于 30% 的目标伤害加深 25%', origin: '《射雕英雄传》（九阴真经所载）', stageName: '秘传', powerNote: '2.42', tags: ['damage 单体', '破甲、流血、易伤'] },
  'world_07_common_sword_01': { description: '剑势沉稳如盘山路转：三段连击，威力逐段递升（0.3/0.35/0.45）', origin: '《笑傲江湖》（泰山派）', stageName: '通用', powerNote: '1.25', tags: ['damage 单体', '连击'] },
  'world_07_common_blade_01': { description: '两仪反转，刀走逆位：破甲 15%/3 秒', origin: '《倚天屠龙记》（华山派）', stageName: '通用', powerNote: '1.25', tags: ['damage 单体', '破甲'] },
  'world_07_common_fist_01': { description: '朴实无华的两段连击（0.5/0.5），拳拳到肉', origin: '江湖流传（少林入门拳）', stageName: '通用', powerNote: '1.25', tags: ['damage 单体', '连击'] },
  'world_07_common_shadow_01': { description: '暗器透骨：单点爆发并附加流血（每秒 0.8% 当前生命，4 秒）', origin: '江湖流传', stageName: '通用', powerNote: '1.25', tags: ['damage 单体', '流血'] },
  'world_07_common_doctor_01': { description: '蝶谷医术：治疗气血最低的友方，并净化 1 个减益', origin: '江湖流传（胡青牛医道衍化）', stageName: '通用', powerNote: '1.25', tags: ['heal 单体', 'cleanse'] },
  'world_07_common_inner_01': { description: '以头为槌硬撼：自损当前生命 3%，破甲 10%/3 秒', origin: '江湖流传', stageName: '通用', powerNote: '1.38', tags: ['damage 单体', '自损、破甲'] },
  'wanren_court_heart_01': { description: '偏重 energyRecovery 与 survivalBonus：九阳生生不息，真气绵长、百毒不侵', origin: '《倚天屠龙记》', stageName: '', powerNote: '', tags: [] },
  'juezong_gate_heart_01': { description: '偏重 gaugeRate 与 survivalBonus：纯阳温养，行动条积攒与生存并重', origin: '《倚天屠龙记》（张三丰）', stageName: '', powerNote: '', tags: [] },
  'jingmai_court_heart_01': { description: '偏重 energyRecovery 与 cooldownRate：九阳残篇，回气稍快、剑招周转更灵', origin: '《倚天屠龙记》（郭襄得自觉远）', stageName: '', powerNote: '', tags: [] },
  'world_07_heart_common': { description: '偏重 momentumBonus 与 cooldownRate：九阴博杂，全面增益气势与招式周转', origin: '《射雕英雄传》', stageName: '', powerNote: '', tags: [] },
  'shuofeng_blade_a1': { description: '入门筑基拳法，正面硬撼，单体重击并破甲15%/4秒', origin: '《天龙八部》', stageName: '初传', powerNote: '1.15', tags: ['damage单体', '破甲'] },
  'shuofeng_blade_b1': { description: '刚猛掌势开山裂石，单体伤害并击退目标', origin: '《天龙八部》', stageName: '进境', powerNote: '1.50', tags: ['damage单体', '击退'] },
  'shuofeng_blade_c1': { description: '掌力外放扫荡群敌，群体伤害并破甲20%/4秒', origin: '《天龙八部》', stageName: '真传', powerNote: '1.50', tags: ['damage群体', '破甲'] },
  'shuofeng_blade_d1': { description: '蓄劲增伤：高真气消耗换高威力，单体毁灭重击并破甲30%/5秒', origin: '《天龙八部》', stageName: '秘传', powerNote: '2.60', tags: ['damage单体', '【现有近似】蓄劲增伤', '破甲'] },
  'shuofeng_blade_a2': { description: '阴柔指劲点打经脉，单体伤害并迟缓25%/4秒', origin: '《天龙八部》', stageName: '初传', powerNote: '1.05', tags: ['damage单体', '迟缓'] },
  'shuofeng_blade_b2': { description: '擒拿锁穴，单体伤害并点穴1秒', origin: '《倚天屠龙记》', stageName: '进境', powerNote: '1.35', tags: ['damage单体', '点穴'] },
  'shuofeng_blade_c2': { description: '阴柔掌劲透入脏腑，单体伤害并附加中毒2层（每秒1%最大生命/5秒）', origin: '《天龙八部》', stageName: '真传', powerNote: '1.70', tags: ['damage单体', '中毒'] },
  'shuofeng_blade_d2': { description: '袈裟卷荡阴劲四溢，群体伤害并附加中毒2层与迟缓20%/4秒', origin: '《天龙八部》', stageName: '秘传', powerNote: '1.80', tags: ['damage群体', '中毒', '迟缓'] },
  'huajin_hall_a1': { description: '破尽天下剑招，单体剑击并附加破绽标记（友方伤害加深10%，触发后消失）', origin: '《笑傲江湖》', stageName: '初传', powerNote: '1.15', tags: ['damage单体', '破绽'] },
  'huajin_hall_b1': { description: '两段连击（各55%），末段附加破绽标记（加深12%）', origin: '《笑傲江湖》', stageName: '进境', powerNote: '1.65', tags: ['damage单体', '连击', '破绽'] },
  'huajin_hall_c1': { description: '剑走轻灵直破内力，单体伤害并破气30%/5秒，同时附加破绽标记', origin: '《笑傲江湖》', stageName: '真传', powerNote: '1.70', tags: ['damage单体', '破气', '破绽'] },
  'huajin_hall_d1': { description: '九剑归一，三段连击（40/30/30），每段命中刷新破绽标记（加深15%），对已有破绽目标威力+20%', origin: '《笑傲江湖》', stageName: '秘传', powerNote: '2.40', tags: ['damage单体', '连击', '破绽'] },
  'huajin_hall_a2': { description: '剑出夺命，单体重斩并破甲25%/4秒', origin: '《三少爷的剑》', stageName: '初传', powerNote: '1.15', tags: ['damage单体', '破甲'] },
  'huajin_hall_b2': { description: '两段重斩（各55%），末段击退目标', origin: '《三少爷的剑》', stageName: '进境', powerNote: '1.65', tags: ['damage单体', '连击', '击退'] },
  'huajin_hall_c2': { description: '燕十三初悟的死亡之剑，单体巨额伤害，附带狂暴（自身生命低于40%时威力+30%）', origin: '《三少爷的剑》', stageName: '真传', powerNote: '1.85', tags: ['damage单体', '狂暴'] },
  'huajin_hall_d2': { description: '完整的第十五剑：自损当前生命10%，单体毁灭性伤害并破甲40%/5秒', origin: '《三少爷的剑》', stageName: '秘传', powerNote: '2.60', tags: ['damage单体', '自损', '破甲'] },
  'jingang_court_a1': { description: '以指力渡入内息疏通经脉，治疗单体友方', origin: '《射雕英雄传》', stageName: '初传', powerNote: '1.15', tags: ['heal单体'] },
  'jingang_court_b1': { description: '六脉内息温养周身气血，群体治疗', origin: '江湖流传', stageName: '进境', powerNote: '1.20', tags: ['heal群体'] },
  'jingang_court_c1': { description: '南帝渡人指法，治疗单体并净化其全部减益', origin: '江湖流传', stageName: '真传', powerNote: '1.70', tags: ['heal单体', 'cleanse'] },
  'jingang_court_d1': { description: '耗尽真元逆转生死，复活单体阵亡友方并恢复其30%生命', origin: '江湖流传', stageName: '秘传', powerNote: '', tags: ['revive单体', 'heal'] },
  'jingang_court_a2': { description: '少冲剑气轻灵诡速，循经截脉，单体剑气伤害并迟缓25%/4秒', origin: '《天龙八部》', stageName: '初传', powerNote: '1.05', tags: ['damage单体', '迟缓'] },
  'jingang_court_b2': { description: '剑气变化精微，专破护体内劲，单体伤害并破气25%/5秒', origin: '《天龙八部》', stageName: '进境', powerNote: '1.50', tags: ['damage单体', '破气'] },
  'jingang_court_c2': { description: '六脉剑气合一横扫，群体伤害并驱散敌方1个增益', origin: '江湖流传', stageName: '真传', powerNote: '1.50', tags: ['damage群体', 'dispel'] },
  'jingang_court_d2': { description: '完整六脉剑谱六剑齐发，六段剑气连击（每段约20%），无视站位封锁', origin: '《天龙八部》', stageName: '秘传', powerNote: '2.40', tags: ['damage单体', '连击'] },
  'world_08_common_sword_01': { description: '林家辟邪剑，剑招奇诡迅捷，三段连击（40/30/30）', origin: '《笑傲江湖》', stageName: '通用', powerNote: '1.45', tags: ['damage单体', '连击'] },
  'world_08_common_blade_01': { description: '秦红棉修罗刀，刀势狠辣，单体伤害并流血（每秒1.5%当前生命/5秒）', origin: '《天龙八部》', stageName: '通用', powerNote: '1.30', tags: ['damage单体', '流血'] },
  'world_08_common_fist_01': { description: '刚猛暴烈贴山靠，单体重击并破甲20%/4秒', origin: '江湖流传', stageName: '通用', powerNote: '1.30', tags: ['damage单体', '破甲'] },
  'world_08_common_shadow_01': { description: '李莫愁淬毒银针，单体暗器伤害并附加中毒1层（每秒1%最大生命/6秒）', origin: '《神雕侠侣》', stageName: '通用', powerNote: '1.15', tags: ['damage单体', '中毒'] },
  'world_08_common_doctor_01': { description: '循子午流注行针渡气，治疗单体并净化其1个减益', origin: '江湖流传', stageName: '通用', powerNote: '1.30', tags: ['heal单体', 'cleanse'] },
  'world_08_common_inner_01': { description: '排打淬体筋骨如铁，自身金钟（受到伤害降低30%/5秒）', origin: '江湖流传', stageName: '通用', powerNote: '', tags: ['金钟'] },
  'shuofeng_blade_heart_01': { description: '少林镇寺内功，易筋锻骨、生生不息：偏重 survivalBonus + energyRecovery', origin: '《天龙八部》', stageName: '', powerNote: '', tags: [] },
  'huajin_hall_heart_01': { description: '无相依心、招意无形，契合逍遥剑法料敌机先：偏重 cooldownRate + momentumBonus', origin: '江湖流传', stageName: '', powerNote: '', tags: [] },
  'jingang_court_heart_01': { description: '段氏家传内息，温养绵长以续疗力：偏重 energyRecovery + survivalBonus', origin: '江湖流传', stageName: '', powerNote: '', tags: [] },
  'world_08_heart_common': { description: '佛门伏魔内劲，蓄势刚猛、愈战愈勇：偏重 gaugeRate + momentumBonus', origin: '《侠客行》', stageName: '', powerNote: '', tags: [] },
  'tianxia_sword_a1': { description: '凝掌重击单体，附带击退，打乱敌方站位', origin: '《天龙八部》', stageName: '初传', powerNote: '1.15', tags: ['单体', '击退'] },
  'tianxia_sword_b1': { description: '正面硬撼重击，附带破甲 20% 持续 4 秒', origin: '《天龙八部》', stageName: '进境', powerNote: '1.50', tags: ['单体', '破甲'] },
  'tianxia_sword_c1': { description: '蓄力 0.8 秒后凌空重击，附带击退', origin: '《天龙八部》', stageName: '真传', powerNote: '1.85', tags: ['单体', '蓄力、击退'] },
  'tianxia_sword_d1': { description: '降龙第一刚掌，劲力有余不尽，单体重击附带易伤 15% 持续 5 秒', origin: '《天龙八部》', stageName: '秘传', powerNote: '2.42', tags: ['单体', '易伤'] },
  'tianxia_sword_a2': { description: '柔劲缠绕单体，附带迟缓 25% 持续 4 秒', origin: '《天龙八部》', stageName: '初传', powerNote: '1.15', tags: ['单体', '迟缓'] },
  'tianxia_sword_b2': { description: '三段连击，掌势连绵，末段附带迟缓 25% 持续 4 秒', origin: '《天龙八部》', stageName: '进境', powerNote: '1.65', tags: ['单体', '连击、迟缓'] },
  'tianxia_sword_c2': { description: '绵劲暗伤侵体，附带中毒可叠 2 层（每秒 0.8% 最大生命，持续 5 秒）', origin: '《天龙八部》', stageName: '真传', powerNote: '1.50', tags: ['单体', '中毒'] },
  'tianxia_sword_d2': { description: '乔峰隔空擒拿绝学，将敌方单体拉至身前并点穴 1.5 秒', origin: '《天龙八部》', stageName: '秘传', powerNote: '1.20', tags: ['单体', '拉近、点穴'] },
  'tongbi_society_a1': { description: '金针渡穴治疗单体，附带净化 1 个减益', origin: '《天龙八部》', stageName: '初传', powerNote: '1.15', tags: ['单疗', 'cleanse'] },
  'tongbi_society_b1': { description: '薛慕华名号神功，群体治疗，活人无数', origin: '《天龙八部》', stageName: '进境', powerNote: '0.98', tags: ['群疗'] },
  'tongbi_society_c1': { description: '高额单体治疗，并为目标套上吸收治疗量 40% 的护盾持续 5 秒（医一人，必令其有生路）', origin: '《笑傲江湖》', stageName: '真传', powerNote: '1.85', tags: ['单疗', '护盾'] },
  'tongbi_society_d1': { description: '复活 1 名阵亡友方恢复 50% 生命，并附带群体治疗', origin: '江湖流传', stageName: '秘传', powerNote: '1.50', tags: ['复活', '群疗'] },
  'tongbi_society_a2': { description: '范百龄琴音乱神，群体迟缓 20% 持续 5 秒', origin: '《天龙八部》', stageName: '初传', powerNote: '0.60', tags: ['群体', '迟缓'] },
  'tongbi_society_b2': { description: '布下珍珑困敌：需我方存活 ≥3 人方可施放（阵法），群体点穴 1 秒', origin: '《天龙八部》', stageName: '进境', powerNote: '0.50', tags: ['群体', '阵法、点穴'] },
  'tongbi_society_c2': { description: '墨毒蚀骨，单体中毒可叠 3 层（每秒 0.7% 最大生命，持续 5 秒），并驱散目标 1 个增益', origin: '《天龙八部》', stageName: '真传', powerNote: '1.50', tags: ['单体', 'dispel', '中毒'] },
  'tongbi_society_d2': { description: '逍遥御风，己方群体加速 25% 持续 5 秒，并净化全部减益', origin: '江湖流传', stageName: '秘传', powerNote: '', tags: ['净化', '加速'] },
  'zhoutian_sect_a1': { description: '刀法基础式，两段连击，贴身缠斗', origin: '江湖流传', stageName: '初传', powerNote: '1.27', tags: ['单体', '连击'] },
  'zhoutian_sect_b1': { description: '胡一刀嫡传快刀，三段连击，末段附带流血（每秒 1% 当前生命，持续 4 秒）', origin: '《雪山飞狐》', stageName: '进境', powerNote: '1.65', tags: ['单体', '连击、流血'] },
  'zhoutian_sect_c1': { description: '刀光如雪四段连击，每段附带破甲 5% 可叠至 20%，持续 4 秒', origin: '《雪山飞狐》', stageName: '真传', powerNote: '2.04', tags: ['单体', '连击、破甲'] },
  'zhoutian_sect_d1': { description: '胡家刀法登峰造极，五段连击，末段雪亮一刀附带点穴 1 秒', origin: '《雪山飞狐》', stageName: '秘传', powerNote: '2.42', tags: ['单体', '连击、点穴'] },
  'zhoutian_sect_a2': { description: '血刀老祖嫡传，单体重斩附带吸血 30%', origin: '《连城诀》', stageName: '初传', powerNote: '1.10', tags: ['单体', '吸血'] },
  'zhoutian_sect_b2': { description: '吸血 40%，并进入狂暴：自身生命低于 50% 时威力提升 20%', origin: '《连城诀》', stageName: '进境', powerNote: '1.50', tags: ['单体', '吸血、狂暴'] },
  'zhoutian_sect_c2': { description: '狂刀横扫群体，附带群体吸血 25%', origin: '《连城诀》', stageName: '真传', powerNote: '1.20', tags: ['群体', '吸血'] },
  'zhoutian_sect_d2': { description: '血刀门至高杀招，高额单体重击吸血 50%，狂暴（生命低于 40% 威力 +30%）触发时追加击退', origin: '《连城诀》', stageName: '秘传', powerNote: '2.20', tags: ['单体', '吸血、狂暴、击退'] },
  'world_09_common_sword_01': { description: '无尘道长快剑，三段连击，末段附带流血（每秒 1% 当前生命，持续 3 秒）', origin: '《书剑恩仇录》', stageName: '通用', powerNote: '1.49', tags: ['单体', '连击、流血'] },
  'world_09_common_blade_01': { description: '王元霸金刀门刚猛刀法，单体重击附带破甲 15% 持续 4 秒', origin: '《笑傲江湖》', stageName: '通用', powerNote: '1.35', tags: ['单体', '破甲'] },
  'world_09_common_fist_01': { description: '桥手刚劲，单体直拳附带击退', origin: '江湖流传', stageName: '通用', powerNote: '1.35', tags: ['单体', '击退'] },
  'world_09_common_shadow_01': { description: '歹毒暗器爆发点杀，单体高威力附带流血（每秒 1.2% 当前生命，持续 3 秒）', origin: '江湖流传', stageName: '通用', powerNote: '1.35', tags: ['单体', '流血'] },
  'world_09_common_doctor_01': { description: '神医典故，单体治疗并净化 1 个减益', origin: '江湖流传', stageName: '通用', powerNote: '1.35', tags: ['单疗', 'cleanse'] },
  'world_09_common_inner_01': { description: '佛门护体，自身受到伤害降低 30% 持续 5 秒', origin: '江湖流传', stageName: '通用', powerNote: '', tags: ['护体', '金钟'] },
  'tianxia_sword_heart_01': { description: '游坦之机缘巧合所习佛门内功，偏重 survivalBonus（抗击打）与 energyRecovery（真气绵长）', origin: '《天龙八部》', stageName: '', powerNote: '', tags: [] },
  'tongbi_society_heart_01': { description: '珍珑棋局困中有解，偏重 cooldownRate（布局迅捷）与 gaugeRate（行动条运转）', origin: '《天龙八部》', stageName: '', powerNote: '', tags: [] },
  'zhoutian_sect_heart_01': { description: '雪山苦寒磨砺刀意，偏重 momentumBonus（连击/狂暴增益放大）与 survivalBonus', origin: '《雪山飞狐》', stageName: '', powerNote: '', tags: [] },
  'world_09_heart_common': { description: '丁典所传玄门正宗内功，偏重 energyRecovery 与 survivalBonus（神照经有起死回生之能）', origin: '《连城诀》', stageName: '', powerNote: '', tags: [] },
  'baizhan_blade_a1': { description: '两段连击，快剑只求抢先出手', origin: '《多情剑客无情剑》', stageName: '初传', powerNote: '', tags: ['单体', '连击2段'] },
  'baizhan_blade_b1': { description: '单点爆发直取咽喉，附带流血（每秒当前生命1%，持续4秒）', origin: '江湖流传', stageName: '进境', powerNote: '', tags: ['单体', '流血'] },
  'baizhan_blade_c1': { description: '四段连击杀剑连环，末段附带点穴1秒', origin: '《多情剑客无情剑》（荆无命）', stageName: '真传', powerNote: '', tags: ['单体', '连击4段、点穴'] },
  'baizhan_blade_d1': { description: '三段连击，首段挂破绽标记（友方伤害加深15%），末段点穴1.5秒，一剑定胜负', origin: '《陆小凤传奇》（西门吹雪）', stageName: '秘传', powerNote: '', tags: ['单体', '连击3段、破绽标记、点穴'] },
  'baizhan_blade_a2': { description: '铁剑正面硬撼，附带破甲25%持续4秒', origin: '《多情剑客无情剑》（郭嵩阳）', stageName: '初传', powerNote: '', tags: ['单体', '破甲'] },
  'baizhan_blade_b2': { description: '重剑下压附带破甲25%持续4秒，并将目标击退一格', origin: '江湖流传', stageName: '进境', powerNote: '', tags: ['单体', '破甲、击退'] },
  'baizhan_blade_c2': { description: '蓄力1.5秒后挥出重斩，蓄力期间可被打断', origin: '江湖流传', stageName: '真传', powerNote: '', tags: ['单体', '蓄力'] },
  'baizhan_blade_d2': { description: '大巧不工的一击，破甲30%持续5秒并击退目标，重剑线威力之巅', origin: '《神雕侠侣》（杨过）', stageName: '秘传', powerNote: '', tags: ['单体', '破甲、击退'] },
  'zhuiming_office_a1': { description: '两段连击暗器直取心口', origin: '《天龙八部》', stageName: '初传', powerNote: '', tags: ['单体', '连击2段'] },
  'zhuiming_office_b1': { description: '单点细针淬毒，附带中毒2层（每秒最大生命1%，持续5秒）', origin: '《天龙八部》', stageName: '进境', powerNote: '', tags: ['单体', '中毒'] },
  'zhuiming_office_c1': { description: '三段连击刺穴，末段附带点穴1秒', origin: '《天龙八部》', stageName: '真传', powerNote: '', tags: ['单体', '连击3段、点穴'] },
  'zhuiming_office_d1': { description: '阴毒掌劲爆发点杀，附带中毒3层并将伤害20%转化为自身生命', origin: '《天龙八部》', stageName: '秘传', powerNote: '', tags: ['单体', '中毒、吸血'] },
  'zhuiming_office_a2': { description: '群体施毒，敌方全体的中毒2层（每秒最大生命0.8%，持续5秒）', origin: '《天龙八部》', stageName: '初传', powerNote: '', tags: ['群体', '中毒'] },
  'zhuiming_office_b2': { description: '单体鞭击缠毒，中毒3层并附带迟缓30%持续4秒', origin: '《天龙八部》', stageName: '进境', powerNote: '', tags: ['单体', '中毒、迟缓'] },
  'zhuiming_office_c2': { description: '群体毒散，敌方全体的中毒2层并封穴3秒（无法施放武功）', origin: '《天龙八部》', stageName: '真传', powerNote: '', tags: ['群体', '中毒、封穴'] },
  'zhuiming_office_d2': { description: '群体万毒并发，中毒3层、驱散敌方全体1个增益，以毒攻毒对我方转为净化', origin: '江湖流传', stageName: '秘传', powerNote: '', tags: ['群体', '驱散', '净化', '中毒'] },
  'qihuang_society_a1': { description: '单点指劲打穴，附带点穴1秒', origin: '《天龙八部》', stageName: '初传', powerNote: '', tags: ['单体', '点穴'] },
  'qihuang_society_b1': { description: '两段连击，刀光如燕尾分剪', origin: '江湖流传', stageName: '进境', powerNote: '', tags: ['单体', '连击2段'] },
  'qihuang_society_c1': { description: '三段连击博采诸家刀法，附带流血（每秒当前生命1.2%，持续4秒）', origin: '江湖流传', stageName: '真传', powerNote: '', tags: ['单体', '连击3段、流血'] },
  'qihuang_society_d1': { description: '复制目标上一个武功并以80%威力即刻释放', origin: '《天龙八部》', stageName: '秘传', powerNote: '', tags: ['单体', '复制'] },
  'qihuang_society_a2': { description: '刚猛正面斩击，附带破甲20%持续4秒', origin: '江湖流传', stageName: '初传', powerNote: '', tags: ['单体', '破甲'] },
  'qihuang_society_b2': { description: '自身生命低于40%时威力提升30%（狂暴），命中附带击退', origin: '江湖流传', stageName: '进境', powerNote: '', tags: ['单体', '狂暴、击退'] },
  'qihuang_society_c2': { description: '蓄力1秒后力劈，附带破气25%持续4秒', origin: '江湖流传', stageName: '真传', powerNote: '', tags: ['单体', '蓄力、破气'] },
  'qihuang_society_d2': { description: '借力：将下一次受到的攻击转移给敌方随机目标；同时自身反伤30%持续3秒', origin: '《天龙八部》', stageName: '秘传', powerNote: '', tags: ['单体', '借力、反伤'] },
  'world_10_common_sword_01': { description: '两段连击，剑光如电', origin: '《笑傲江湖》（丁坚）', stageName: '通用', powerNote: '', tags: ['单体', '连击2段'] },
  'world_10_common_blade_01': { description: '单体重斩，附带破甲20%持续3秒', origin: '《萧十一郎》', stageName: '通用', powerNote: '', tags: ['单体', '破甲'] },
  'world_10_common_fist_01': { description: '虎形刚猛、鹤形轻灵，两段连击', origin: '江湖流传（洪拳）', stageName: '通用', powerNote: '', tags: ['单体', '连击2段'] },
  'world_10_common_shadow_01': { description: '群体暗器齐发，密如暴雨', origin: '《楚留香传奇》', stageName: '通用', powerNote: '', tags: ['群体'] },
  'world_10_common_doctor_01': { description: '治疗友方单体并净化其1个减益', origin: '江湖流传', stageName: '通用', powerNote: '', tags: ['单疗', '净化'] },
  'world_10_common_inner_01': { description: '为友方单体套上吸收伤害的护盾（吸收量按威力等值），持续4秒', origin: '《绝代双骄》（移花宫）', stageName: '通用', powerNote: '', tags: ['护体', '护盾'] },
  'baizhan_blade_heart_01': { description: '长春不老、生生不息，偏重 survivalBonus 与 energyRecovery', origin: '《天龙八部》', stageName: '', powerNote: '', tags: [] },
  'zhuiming_office_heart_01': { description: '化人内力为己用，偏重 energyRecovery（与吸内机制联动）与 cooldownRate', origin: '《天龙八部》', stageName: '', powerNote: '', tags: [] },
  'qihuang_society_heart_01': { description: '参合百家、借势蓄力，偏重 momentumBonus 与 gaugeRate', origin: '江湖流传', stageName: '', powerNote: '', tags: [] },
  'world_10_heart_common': { description: '阴阳交征、动如雷霆，偏重 gaugeRate 与 momentumBonus', origin: '《天涯明月刀》', stageName: '', powerNote: '', tags: [] },
}
