// 本文件由 scripts/generate-zhutian-skills.mjs 从《诸天刷宝录》解包数据生成，请勿手改。
// 数据源：jn.json（技能）、fw.json（范围）、zh.json（召唤物）、zy.json（职业普攻）。
// 范围翻译：单体/自身/全体保持原义，十字与九宫等按「主目标邻近扩散 N 格」近似。

export type SkillBehavior = 'attack' | 'heal' | 'shield' | 'status' | 'revive' | 'advance-gauge' | 'grant-energy' | 'summon' | 'passive'
export type SkillRangeKind = 'single' | 'spread' | 'all' | 'self'

export interface CombatSkillContent {
  /** 原版 jn 表 id */
  id: number
  name: string
  behavior: SkillBehavior
  targetSide: 'enemy' | 'ally'
  route: 'external' | 'internal' | 'support'
  /** 元素 0 无 / 1 雷 / 2 水 / 3 火 / 4 木 / 5 土 / 6 精神 / 7 神圣 / 8 黑暗 */
  element: number
  /** 威力百分比（技能等级 1）；推条技能表示行动条推进百分比 */
  powerPercent: number
  /** 能量档 0-5；冷却 = 能量档 × 4 秒 */
  energyCost: number
  cooldownMs: number
  hits: number
  rangeKind: SkillRangeKind
  rangeCount: number
  reach: 'melee' | 'ranged'
  /** 技能系（专精乘区 60+cat-1） */
  skillCategory: number
  appliedBuffId?: number
  appliedBuffChance?: number
  appliedBuffStacks?: number
  /** 增效：施法者身上每层该 buff 提升伤害百分比 */
  enhanceBuffId?: number
  enhancePerStack?: number
  summonId?: number
  passiveAttributes?: ReadonlyArray<{ sxId: number; value: number }>
}

export const COMBAT_SKILLS: Readonly<Record<number, CombatSkillContent>> = {
  1: { id: 1, name: '攻击', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 0, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 1 },
  2: { id: 2, name: '钝击', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 0, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 2 },
  3: { id: 3, name: '铁拳', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 0, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 3 },
  4: { id: 4, name: '冰击', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 2, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 4 },
  5: { id: 5, name: '射击', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 0, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 5 },
  6: { id: 6, name: '包扎', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 0, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 6 },
  7: { id: 7, name: '猛击I', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 4, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 7 },
  8: { id: 8, name: '圣击I', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 7, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 8 },
  9: { id: 9, name: '劈砍I', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 5, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 9 },
  10: { id: 10, name: '突刺I', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 8, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 10 },
  11: { id: 11, name: '火符I', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 3, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 11 },
  12: { id: 12, name: '御雷I', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 1, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 12 },
  13: { id: 13, name: '射箭I', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 2, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 13 },
  14: { id: 14, name: '炮击I', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 14 },
  15: { id: 15, name: '抚慰I', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 8, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 15 },
  16: { id: 16, name: '治疗I', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 6, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 16 },
  17: { id: 17, name: '猛击II', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 4, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 7 },
  18: { id: 18, name: '圣击II', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 7, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 8 },
  19: { id: 19, name: '劈砍II', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 5, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 9 },
  20: { id: 20, name: '突刺II', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 8, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 10 },
  21: { id: 21, name: '火符II', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 3, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 11 },
  22: { id: 22, name: '御雷II', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 1, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 12 },
  23: { id: 23, name: '射箭II', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 2, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 13 },
  24: { id: 24, name: '炮击II', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 14 },
  25: { id: 25, name: '抚慰II', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 8, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 15 },
  26: { id: 26, name: '治疗II', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 6, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 16 },
  27: { id: 27, name: '猛击III', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 4, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 7 },
  28: { id: 28, name: '圣击III', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 7, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 8 },
  29: { id: 29, name: '劈砍III', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 5, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 9 },
  30: { id: 30, name: '突刺III', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 8, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 10 },
  31: { id: 31, name: '火符III', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 3, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 11 },
  32: { id: 32, name: '御雷III', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 1, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 12 },
  33: { id: 33, name: '射箭III', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 2, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 13 },
  34: { id: 34, name: '炮击III', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 14 },
  35: { id: 35, name: '抚慰III', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 8, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 15 },
  36: { id: 36, name: '治疗III', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 6, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 16 },
  37: { id: 37, name: '神之指', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 7, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 3, rangeKind: 'spread', rangeCount: 3, reach: 'melee', skillCategory: 8 },
  38: { id: 38, name: '天帝斩', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 8, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 2, rangeKind: 'spread', rangeCount: 3, reach: 'melee', skillCategory: 10 },
  39: { id: 39, name: '天雷破', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 1, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 3, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 12 },
  40: { id: 40, name: '人皇剑', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 2, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 9 },
  41: { id: 41, name: '粒子轰', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 1, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 4, rangeKind: 'spread', rangeCount: 3, reach: 'melee', skillCategory: 14 },
  42: { id: 42, name: '野球拳', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 0, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 5, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 1 },
  45: { id: 45, name: '竖斩', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 0, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 2, rangeKind: 'spread', rangeCount: 3, reach: 'melee', skillCategory: 1 },
  47: { id: 47, name: '战场庇护', behavior: 'status', targetSide: 'ally', route: 'support', element: 0, powerPercent: 100, energyCost: 5, cooldownMs: 20000, hits: 1, rangeKind: 'all', rangeCount: 15, reach: 'ranged', skillCategory: 1, appliedBuffId: 11, appliedBuffChance: 1, appliedBuffStacks: 1 },
  48: { id: 48, name: '虎盾击', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 4, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 2, appliedBuffId: 2, appliedBuffChance: 0.2, appliedBuffStacks: 1 },
  49: { id: 49, name: '十字突刺', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 4, powerPercent: 90, energyCost: 2, cooldownMs: 8000, hits: 2, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 2, appliedBuffId: 14, appliedBuffChance: 0.7, appliedBuffStacks: 1 },
  50: { id: 50, name: '自愈', behavior: 'heal', targetSide: 'ally', route: 'support', element: 4, powerPercent: 20, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 2 },
  51: { id: 51, name: '魏武护卫', behavior: 'status', targetSide: 'ally', route: 'support', element: 4, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'spread', rangeCount: 9, reach: 'ranged', skillCategory: 2, appliedBuffId: 13, appliedBuffChance: 1, appliedBuffStacks: 1 },
  52: { id: 52, name: '啸龙锤', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 4, powerPercent: 90, energyCost: 4, cooldownMs: 16000, hits: 5, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 2, appliedBuffId: 2, appliedBuffChance: 1, appliedBuffStacks: 1 },
  53: { id: 53, name: '天下归心', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 4, powerPercent: 95, energyCost: 5, cooldownMs: 20000, hits: 3, rangeKind: 'spread', rangeCount: 6, reach: 'melee', skillCategory: 2, appliedBuffId: 2, appliedBuffChance: 0.15, appliedBuffStacks: 1 },
  54: { id: 54, name: '凝神箭', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 2, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 5 },
  55: { id: 55, name: '迅捷步伐', behavior: 'status', targetSide: 'ally', route: 'support', element: 2, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 5, appliedBuffId: 17, appliedBuffChance: 1, appliedBuffStacks: 1 },
  56: { id: 56, name: '专注心神', behavior: 'status', targetSide: 'ally', route: 'support', element: 2, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 5, appliedBuffId: 19, appliedBuffChance: 1, appliedBuffStacks: 3 },
  57: { id: 57, name: '百步穿杨', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 2, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 5, enhanceBuffId: 19, enhancePerStack: 15 },
  59: { id: 59, name: '铁箭雨', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 2, powerPercent: 100, energyCost: 5, cooldownMs: 20000, hits: 8, rangeKind: 'all', rangeCount: 15, reach: 'melee', skillCategory: 5, enhanceBuffId: 19, enhancePerStack: 15 },
  60: { id: 60, name: '疗伤', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 6, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 6 },
  62: { id: 62, name: '刮骨刀', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 6, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 3, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 6, appliedBuffId: 12, appliedBuffChance: 1, appliedBuffStacks: 1 },
  63: { id: 63, name: '青囊书', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 6, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 6, enhanceBuffId: 20, enhancePerStack: 10 },
  64: { id: 64, name: '起死回生', behavior: 'revive', targetSide: 'ally', route: 'internal', element: 6, powerPercent: 100, energyCost: 4, cooldownMs: 16000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 6 },
  65: { id: 65, name: '悬壶济世', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 6, powerPercent: 100, energyCost: 5, cooldownMs: 20000, hits: 5, rangeKind: 'all', rangeCount: 15, reach: 'ranged', skillCategory: 6, enhanceBuffId: 20, enhancePerStack: 10 },
  66: { id: 66, name: '鬼爪', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 8, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 3, rangeKind: 'spread', rangeCount: 3, reach: 'melee', skillCategory: 15 },
  67: { id: 67, name: '勾魂', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 8, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 3, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 15 },
  68: { id: 68, name: '回魂', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 8, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 15 },
  72: { id: 72, name: '召唤亡灵', behavior: 'summon', targetSide: 'ally', route: 'internal', element: 8, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 15, summonId: 4 },
  73: { id: 73, name: '鸿蒙太清录', behavior: 'passive', targetSide: 'ally', route: 'support', element: 2, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 1, passiveAttributes: [{ sxId: 131, value: 120 }] },
  74: { id: 74, name: '枯木缠绕', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 4, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 11 },
  75: { id: 75, name: '清泉回春', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 2, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'spread', rangeCount: 5, reach: 'ranged', skillCategory: 6 },
  76: { id: 76, name: '金刚伏魔功', behavior: 'passive', targetSide: 'ally', route: 'support', element: 5, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 1, passiveAttributes: [{ sxId: 134, value: 120 }] },
  77: { id: 77, name: '摩西的赐福', behavior: 'passive', targetSide: 'ally', route: 'support', element: 7, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 1, passiveAttributes: [{ sxId: 136, value: 120 }] },
  78: { id: 78, name: '玄天长生法', behavior: 'passive', targetSide: 'ally', route: 'support', element: 4, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 1, passiveAttributes: [{ sxId: 131, value: 120 }] },
  79: { id: 79, name: '九部天雷录', behavior: 'passive', targetSide: 'ally', route: 'support', element: 1, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 1, passiveAttributes: [{ sxId: 133, value: 120 }] },
  80: { id: 80, name: '无相显真决', behavior: 'passive', targetSide: 'ally', route: 'support', element: 6, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 1, passiveAttributes: [{ sxId: 135, value: 120 }] },
  81: { id: 81, name: '火灵扇袭', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 3, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'spread', rangeCount: 3, reach: 'melee', skillCategory: 4 },
  83: { id: 83, name: '左右互博', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 5, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 2, rangeKind: 'spread', rangeCount: 3, reach: 'melee', skillCategory: 3 },
  84: { id: 84, name: '竖劈', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 5, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 2, rangeKind: 'spread', rangeCount: 3, reach: 'melee', skillCategory: 9 },
  85: { id: 85, name: '火枪突', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 3, rangeKind: 'spread', rangeCount: 4, reach: 'melee', skillCategory: 3 },
  86: { id: 86, name: '晕锤', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 4, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 7 },
  87: { id: 87, name: '穿甲', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 2, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 13 },
  88: { id: 88, name: '光剑', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 7, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 2, rangeKind: 'spread', rangeCount: 3, reach: 'melee', skillCategory: 8 },
  89: { id: 89, name: '三连击', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 1, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 3, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 9 },
  90: { id: 90, name: '暗刃', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 8, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 2, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 10 },
  91: { id: 91, name: '刮骨', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 6, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 3, rangeKind: 'spread', rangeCount: 3, reach: 'melee', skillCategory: 15 },
  92: { id: 92, name: '土轰', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 5, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'spread', rangeCount: 3, reach: 'melee', skillCategory: 4 },
  93: { id: 93, name: '火扇', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 3, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 2, rangeKind: 'spread', rangeCount: 6, reach: 'melee', skillCategory: 12 },
  95: { id: 95, name: '碎冰', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 2, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 3, rangeKind: 'spread', rangeCount: 9, reach: 'melee', skillCategory: 6 },
  96: { id: 96, name: '圣光', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 7, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'spread', rangeCount: 4, reach: 'ranged', skillCategory: 16 },
  98: { id: 98, name: '亵渎', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 8, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 11 },
  101: { id: 101, name: '飞龙在天', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 70, energyCost: 2, cooldownMs: 8000, hits: 3, rangeKind: 'spread', rangeCount: 3, reach: 'melee', skillCategory: 3, appliedBuffId: 5, appliedBuffChance: 0.5, appliedBuffStacks: 1 },
  102: { id: 102, name: '亢龙有悔', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 70, energyCost: 4, cooldownMs: 16000, hits: 5, rangeKind: 'spread', rangeCount: 6, reach: 'melee', skillCategory: 3, appliedBuffId: 5, appliedBuffChance: 0.5, appliedBuffStacks: 1 },
  103: { id: 103, name: '蟠龙击', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 2, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 3, enhanceBuffId: 5, enhancePerStack: 10 },
  104: { id: 104, name: '打狗阵', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 5, rangeKind: 'spread', rangeCount: 9, reach: 'melee', skillCategory: 3, enhanceBuffId: 5, enhancePerStack: 10 },
  105: { id: 105, name: '擒龙心法', behavior: 'status', targetSide: 'ally', route: 'support', element: 3, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 3, appliedBuffId: 7, appliedBuffChance: 1, appliedBuffStacks: 1 },
  106: { id: 106, name: '铁布衫', behavior: 'shield', targetSide: 'ally', route: 'internal', element: 5, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 2 },
  107: { id: 107, name: '金钟罩', behavior: 'status', targetSide: 'ally', route: 'support', element: 5, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 2, appliedBuffId: 11, appliedBuffChance: 1, appliedBuffStacks: 1 },
  108: { id: 108, name: '十八铜人阵', behavior: 'shield', targetSide: 'ally', route: 'internal', element: 5, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'spread', rangeCount: 3, reach: 'ranged', skillCategory: 2 },
  109: { id: 109, name: '少林棍法', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 5, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 2, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 2 },
  110: { id: 110, name: '达摩杖法', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 5, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 4, rangeKind: 'spread', rangeCount: 3, reach: 'melee', skillCategory: 2 },
  111: { id: 111, name: '混元般若功', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 5, powerPercent: 100, energyCost: 4, cooldownMs: 16000, hits: 3, rangeKind: 'spread', rangeCount: 9, reach: 'melee', skillCategory: 2 },
  113: { id: 113, name: '落剑式', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 1, powerPercent: 90, energyCost: 2, cooldownMs: 8000, hits: 3, rangeKind: 'spread', rangeCount: 2, reach: 'melee', skillCategory: 3 },
  115: { id: 115, name: '迷踪步', behavior: 'status', targetSide: 'ally', route: 'support', element: 1, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 3, appliedBuffId: 22, appliedBuffChance: 1, appliedBuffStacks: 1 },
  116: { id: 116, name: '紫瑕心法', behavior: 'status', targetSide: 'ally', route: 'support', element: 1, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 3, appliedBuffId: 21, appliedBuffChance: 1, appliedBuffStacks: 5 },
  117: { id: 117, name: '辟邪剑气', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 1, powerPercent: 100, energyCost: 4, cooldownMs: 16000, hits: 8, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 3, enhanceBuffId: 21, enhancePerStack: 5 },
  119: { id: 119, name: '太极拳', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 2, powerPercent: 90, energyCost: 3, cooldownMs: 12000, hits: 5, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 6, appliedBuffId: 23, appliedBuffChance: 0.7, appliedBuffStacks: 1 },
  121: { id: 121, name: '武当心法', behavior: 'grant-energy', targetSide: 'ally', route: 'support', element: 2, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 6 },
  124: { id: 124, name: '崩山拳', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 5, powerPercent: 90, energyCost: 1, cooldownMs: 4000, hits: 2, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 1 },
  125: { id: 125, name: '岩阳破煞', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 5, powerPercent: 90, energyCost: 2, cooldownMs: 8000, hits: 4, rangeKind: 'spread', rangeCount: 3, reach: 'melee', skillCategory: 1 },
  126: { id: 126, name: '八卦锁魂拳', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 5, powerPercent: 90, energyCost: 3, cooldownMs: 12000, hits: 6, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 1 },
  127: { id: 127, name: '醒狮掌', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 5, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 8, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 1, enhanceBuffId: 24, enhancePerStack: 15 },
  128: { id: 128, name: '回神诀', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 5, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 1, enhanceBuffId: 24, enhancePerStack: 20 },
  129: { id: 129, name: '山河怒', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 5, powerPercent: 100, energyCost: 4, cooldownMs: 16000, hits: 4, rangeKind: 'spread', rangeCount: 9, reach: 'melee', skillCategory: 1, enhanceBuffId: 24, enhancePerStack: 15 },
  130: { id: 130, name: '雷击符', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 1, powerPercent: 95, energyCost: 1, cooldownMs: 4000, hits: 3, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 4, appliedBuffId: 25, appliedBuffChance: 0.2, appliedBuffStacks: 1 },
  131: { id: 131, name: '狂雷符', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 1, powerPercent: 95, energyCost: 3, cooldownMs: 12000, hits: 4, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 4, appliedBuffId: 25, appliedBuffChance: 0.2, appliedBuffStacks: 1 },
  132: { id: 132, name: '九天御雷符', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 1, powerPercent: 95, energyCost: 5, cooldownMs: 20000, hits: 6, rangeKind: 'all', rangeCount: 15, reach: 'melee', skillCategory: 4, appliedBuffId: 25, appliedBuffChance: 0.2, appliedBuffStacks: 1 },
  133: { id: 133, name: '破魔符', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 1, powerPercent: 90, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 4, appliedBuffId: 16, appliedBuffChance: 0.7, appliedBuffStacks: 1 },
  134: { id: 134, name: '破魔阵', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 1, powerPercent: 90, energyCost: 2, cooldownMs: 8000, hits: 2, rangeKind: 'spread', rangeCount: 3, reach: 'ranged', skillCategory: 4, appliedBuffId: 16, appliedBuffChance: 0.7, appliedBuffStacks: 1 },
  135: { id: 135, name: '紫霄破魔阵', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 1, powerPercent: 90, energyCost: 4, cooldownMs: 16000, hits: 3, rangeKind: 'spread', rangeCount: 9, reach: 'ranged', skillCategory: 4, appliedBuffId: 16, appliedBuffChance: 0.7, appliedBuffStacks: 1 },
  136: { id: 136, name: '火箭', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 5, appliedBuffId: 26, appliedBuffChance: 1, appliedBuffStacks: 5 },
  137: { id: 137, name: '烈焰箭', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 2, rangeKind: 'spread', rangeCount: 4, reach: 'melee', skillCategory: 5, appliedBuffId: 26, appliedBuffChance: 1, appliedBuffStacks: 12 },
  138: { id: 138, name: '爆裂箭', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 3, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 5, appliedBuffId: 26, appliedBuffChance: 1, appliedBuffStacks: 20 },
  139: { id: 139, name: '专注瞄准', behavior: 'status', targetSide: 'ally', route: 'support', element: 3, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 5, appliedBuffId: 27, appliedBuffChance: 1, appliedBuffStacks: 1 },
  140: { id: 140, name: '星火爆弩箭', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 3, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 5, enhanceBuffId: 26, enhancePerStack: 2 },
  141: { id: 141, name: '烈焰机关弩', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 3, rangeKind: 'spread', rangeCount: 9, reach: 'ranged', skillCategory: 5, enhanceBuffId: 26, enhancePerStack: 2 },
  142: { id: 142, name: '施毒术', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 4, powerPercent: 60, energyCost: 1, cooldownMs: 4000, hits: 2, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 4, appliedBuffId: 3, appliedBuffChance: 0.7, appliedBuffStacks: 1 },
  143: { id: 143, name: '青棘毒咒', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 4, powerPercent: 60, energyCost: 3, cooldownMs: 12000, hits: 3, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 4, appliedBuffId: 3, appliedBuffChance: 0.7, appliedBuffStacks: 1 },
  144: { id: 144, name: '荆棘毒雨', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 4, powerPercent: 60, energyCost: 5, cooldownMs: 20000, hits: 4, rangeKind: 'spread', rangeCount: 11, reach: 'melee', skillCategory: 4, appliedBuffId: 3, appliedBuffChance: 0.7, appliedBuffStacks: 1 },
  145: { id: 145, name: '木毒刺', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 4, powerPercent: 60, energyCost: 2, cooldownMs: 8000, hits: 3, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 4, appliedBuffId: 3, appliedBuffChance: 1, appliedBuffStacks: 1 },
  146: { id: 146, name: '中毒加深', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 4, powerPercent: 60, energyCost: 4, cooldownMs: 16000, hits: 5, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 4, appliedBuffId: 3, appliedBuffChance: 1, appliedBuffStacks: 3 },
  147: { id: 147, name: '林木源聚爆', behavior: 'status', targetSide: 'ally', route: 'support', element: 4, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 4, appliedBuffId: 28, appliedBuffChance: 1, appliedBuffStacks: 1 },
  148: { id: 148, name: '追猎箭', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 1, powerPercent: 90, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 5, appliedBuffId: 30, appliedBuffChance: 0.7, appliedBuffStacks: 1 },
  149: { id: 149, name: '穿心箭影', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 1, powerPercent: 90, energyCost: 3, cooldownMs: 12000, hits: 3, rangeKind: 'spread', rangeCount: 4, reach: 'melee', skillCategory: 5, appliedBuffId: 30, appliedBuffChance: 0.7, appliedBuffStacks: 1 },
  150: { id: 150, name: '闪影猎袭', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 1, powerPercent: 90, energyCost: 5, cooldownMs: 20000, hits: 4, rangeKind: 'spread', rangeCount: 7, reach: 'melee', skillCategory: 5, appliedBuffId: 30, appliedBuffChance: 0.7, appliedBuffStacks: 1 },
  151: { id: 151, name: '缚网箭', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 1, powerPercent: 90, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 5, appliedBuffId: 18, appliedBuffChance: 1, appliedBuffStacks: 1 },
  152: { id: 152, name: '狩猎经验', behavior: 'status', targetSide: 'ally', route: 'support', element: 1, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 5, appliedBuffId: 29, appliedBuffChance: 1, appliedBuffStacks: 1 },
  153: { id: 153, name: '目标追击', behavior: 'status', targetSide: 'ally', route: 'support', element: 1, powerPercent: 100, energyCost: 4, cooldownMs: 16000, hits: 1, rangeKind: 'all', rangeCount: 15, reach: 'ranged', skillCategory: 5, appliedBuffId: 17, appliedBuffChance: 1, appliedBuffStacks: 1 },
  154: { id: 154, name: '守护结界', behavior: 'shield', targetSide: 'ally', route: 'internal', element: 7, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 8 },
  155: { id: 155, name: '神星护壁', behavior: 'shield', targetSide: 'ally', route: 'internal', element: 7, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'spread', rangeCount: 5, reach: 'ranged', skillCategory: 8 },
  156: { id: 156, name: '星辰圣芒盾', behavior: 'shield', targetSide: 'ally', route: 'internal', element: 7, powerPercent: 100, energyCost: 5, cooldownMs: 20000, hits: 1, rangeKind: 'all', rangeCount: 15, reach: 'ranged', skillCategory: 8 },
  157: { id: 157, name: '神辉击', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 7, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 3, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 8 },
  158: { id: 158, name: '圣祈之光', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 7, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 8 },
  159: { id: 159, name: '圣辉庇佑盾', behavior: 'status', targetSide: 'ally', route: 'support', element: 7, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'all', rangeCount: 15, reach: 'ranged', skillCategory: 8, appliedBuffId: 15, appliedBuffChance: 1, appliedBuffStacks: 1 },
  160: { id: 160, name: '点燃', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 3, powerPercent: 70, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 11, appliedBuffId: 4, appliedBuffChance: 1, appliedBuffStacks: 1 },
  161: { id: 161, name: '火球连击', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 3, powerPercent: 70, energyCost: 2, cooldownMs: 8000, hits: 3, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 11, appliedBuffId: 4, appliedBuffChance: 1, appliedBuffStacks: 3 },
  162: { id: 162, name: '火陨术', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 3, powerPercent: 70, energyCost: 3, cooldownMs: 12000, hits: 4, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 11, appliedBuffId: 4, appliedBuffChance: 0.7, appliedBuffStacks: 1 },
  163: { id: 163, name: '引爆', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 3, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 2, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 11, enhanceBuffId: 4, enhancePerStack: 15 },
  164: { id: 164, name: '归元决', behavior: 'status', targetSide: 'ally', route: 'support', element: 3, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 11, appliedBuffId: 31, appliedBuffChance: 1, appliedBuffStacks: 1 },
  165: { id: 165, name: '星火燎原', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 3, powerPercent: 100, energyCost: 5, cooldownMs: 20000, hits: 4, rangeKind: 'spread', rangeCount: 11, reach: 'melee', skillCategory: 11, enhanceBuffId: 4, enhancePerStack: 15 },
  166: { id: 166, name: '还春术', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 6, powerPercent: 70, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 6, appliedBuffId: 6, appliedBuffChance: 1, appliedBuffStacks: 1 },
  167: { id: 167, name: '月辉养元', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 6, powerPercent: 70, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'spread', rangeCount: 5, reach: 'ranged', skillCategory: 6, appliedBuffId: 6, appliedBuffChance: 1, appliedBuffStacks: 1 },
  168: { id: 168, name: '清泉沁心咒', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 6, powerPercent: 70, energyCost: 5, cooldownMs: 20000, hits: 1, rangeKind: 'all', rangeCount: 15, reach: 'ranged', skillCategory: 6, appliedBuffId: 6, appliedBuffChance: 1, appliedBuffStacks: 1 },
  169: { id: 169, name: '幽泉血咒', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 6, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 3, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 6 },
  170: { id: 170, name: '仙脉灵注咒', behavior: 'status', targetSide: 'ally', route: 'support', element: 6, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 6, appliedBuffId: 32, appliedBuffChance: 1, appliedBuffStacks: 1 },
  171: { id: 171, name: '阎罗换生诀', behavior: 'revive', targetSide: 'ally', route: 'internal', element: 6, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 6 },
  172: { id: 172, name: '怒剑式', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 5, powerPercent: 95, energyCost: 1, cooldownMs: 4000, hits: 3, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 9 },
  174: { id: 174, name: '剑气斩妖', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 5, powerPercent: 95, energyCost: 3, cooldownMs: 12000, hits: 5, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 9 },
  175: { id: 175, name: '灵识洞察', behavior: 'status', targetSide: 'ally', route: 'support', element: 5, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 9, appliedBuffId: 34, appliedBuffChance: 1, appliedBuffStacks: 1 },
  176: { id: 176, name: '剑灵怒', behavior: 'status', targetSide: 'ally', route: 'support', element: 5, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 9, appliedBuffId: 33, appliedBuffChance: 1, appliedBuffStacks: 20 },
  177: { id: 177, name: '万剑归宗', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 5, powerPercent: 100, energyCost: 5, cooldownMs: 20000, hits: 12, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 9, enhanceBuffId: 33, enhancePerStack: 3 },
  178: { id: 178, name: '孤魂敕令', behavior: 'summon', targetSide: 'ally', route: 'internal', element: 8, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 15, summonId: 1 },
  179: { id: 179, name: '幽鬼驱令', behavior: 'summon', targetSide: 'ally', route: 'internal', element: 8, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 15, summonId: 2 },
  180: { id: 180, name: '黄泉使令', behavior: 'summon', targetSide: 'ally', route: 'internal', element: 8, powerPercent: 100, energyCost: 4, cooldownMs: 16000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 15, summonId: 3 },
  181: { id: 181, name: '灵源幽唤', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 8, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 3, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 15 },
  182: { id: 182, name: '往生咒', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 8, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 15 },
  183: { id: 183, name: '百鬼夜行', behavior: 'status', targetSide: 'ally', route: 'support', element: 8, powerPercent: 100, energyCost: 5, cooldownMs: 20000, hits: 1, rangeKind: 'all', rangeCount: 15, reach: 'ranged', skillCategory: 15, appliedBuffId: 35, appliedBuffChance: 1, appliedBuffStacks: 1 },
  184: { id: 184, name: '镜念', behavior: 'status', targetSide: 'ally', route: 'support', element: 1, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 3, appliedBuffId: 36, appliedBuffChance: 1, appliedBuffStacks: 1 },
  185: { id: 185, name: '剑心', behavior: 'status', targetSide: 'ally', route: 'support', element: 1, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 3, appliedBuffId: 37, appliedBuffChance: 1, appliedBuffStacks: 1 },
  186: { id: 186, name: '拔刀', behavior: 'status', targetSide: 'ally', route: 'support', element: 1, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 3, appliedBuffId: 36, appliedBuffChance: 1, appliedBuffStacks: 4 },
  187: { id: 187, name: '居合', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 1, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 3, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 3, enhanceBuffId: 36, enhancePerStack: 20 },
  188: { id: 188, name: '一闪', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 1, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 3, enhanceBuffId: 36, enhancePerStack: 20 },
  189: { id: 189, name: '乱刀', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 1, powerPercent: 100, energyCost: 4, cooldownMs: 16000, hits: 8, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 3, enhanceBuffId: 36, enhancePerStack: 20 },
  190: { id: 190, name: '隐匿', behavior: 'status', targetSide: 'ally', route: 'support', element: 8, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 10, appliedBuffId: 22, appliedBuffChance: 1, appliedBuffStacks: 1 },
  191: { id: 191, name: '烟雾玉', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 8, powerPercent: 50, energyCost: 3, cooldownMs: 12000, hits: 3, rangeKind: 'all', rangeCount: 15, reach: 'melee', skillCategory: 10, appliedBuffId: 38, appliedBuffChance: 0.5, appliedBuffStacks: 1 },
  192: { id: 192, name: '八岐血咒', behavior: 'status', targetSide: 'ally', route: 'support', element: 8, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 10, appliedBuffId: 39, appliedBuffChance: 1, appliedBuffStacks: 1 },
  193: { id: 193, name: '手里剑', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 8, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 10, enhanceBuffId: 39, enhancePerStack: 20 },
  194: { id: 194, name: '潜影蛇手', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 8, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 5, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 10, enhanceBuffId: 39, enhancePerStack: 20 },
  195: { id: 195, name: '万蛇之阵', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 8, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 6, rangeKind: 'spread', rangeCount: 11, reach: 'melee', skillCategory: 10, enhanceBuffId: 39, enhancePerStack: 20 },
  196: { id: 196, name: '火炮修理', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 3, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 14 },
  197: { id: 197, name: '护卫姿态', behavior: 'status', targetSide: 'ally', route: 'support', element: 3, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 14, appliedBuffId: 41, appliedBuffChance: 1, appliedBuffStacks: 1 },
  198: { id: 198, name: '射击姿态', behavior: 'status', targetSide: 'ally', route: 'support', element: 3, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 14, appliedBuffId: 40, appliedBuffChance: 1, appliedBuffStacks: 1 },
  199: { id: 199, name: '火铳贯穿', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 3, rangeKind: 'spread', rangeCount: 3, reach: 'melee', skillCategory: 14 },
  200: { id: 200, name: '铁炮轰炸', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 5, rangeKind: 'spread', rangeCount: 9, reach: 'melee', skillCategory: 14 },
  201: { id: 201, name: '天下布武', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 100, energyCost: 4, cooldownMs: 16000, hits: 8, rangeKind: 'all', rangeCount: 15, reach: 'melee', skillCategory: 14 },
  203: { id: 203, name: '乌拉搏击', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 5, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 3, rangeKind: 'spread', rangeCount: 3, reach: 'melee', skillCategory: 2, appliedBuffId: 42, appliedBuffChance: 0.5, appliedBuffStacks: 1 },
  204: { id: 204, name: '喀秋莎弹幕', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 5, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 6, rangeKind: 'spread', rangeCount: 6, reach: 'melee', skillCategory: 2, appliedBuffId: 42, appliedBuffChance: 0.5, appliedBuffStacks: 1 },
  205: { id: 205, name: '战壕坚守', behavior: 'status', targetSide: 'ally', route: 'support', element: 5, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'spread', rangeCount: 3, reach: 'ranged', skillCategory: 2, appliedBuffId: 13, appliedBuffChance: 1, appliedBuffStacks: 1 },
  206: { id: 206, name: '冲锋号', behavior: 'status', targetSide: 'ally', route: 'support', element: 5, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 1, rangeKind: 'spread', rangeCount: 5, reach: 'ranged', skillCategory: 2, appliedBuffId: 7, appliedBuffChance: 1, appliedBuffStacks: 1 },
  207: { id: 207, name: '军人意志', behavior: 'status', targetSide: 'ally', route: 'support', element: 5, powerPercent: 100, energyCost: 4, cooldownMs: 16000, hits: 1, rangeKind: 'all', rangeCount: 15, reach: 'ranged', skillCategory: 2, appliedBuffId: 13, appliedBuffChance: 1, appliedBuffStacks: 1 },
  208: { id: 208, name: '装弹', behavior: 'status', targetSide: 'ally', route: 'support', element: 2, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 13, appliedBuffId: 43, appliedBuffChance: 1, appliedBuffStacks: 3 },
  209: { id: 209, name: '弹夹', behavior: 'status', targetSide: 'ally', route: 'support', element: 2, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 13, appliedBuffId: 43, appliedBuffChance: 1, appliedBuffStacks: 8 },
  210: { id: 210, name: '弹药箱', behavior: 'status', targetSide: 'ally', route: 'support', element: 2, powerPercent: 100, energyCost: 5, cooldownMs: 20000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 13, appliedBuffId: 43, appliedBuffChance: 1, appliedBuffStacks: 20 },
  211: { id: 211, name: '机枪射击', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 2, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 6, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 13, enhanceBuffId: 43, enhancePerStack: 30 },
  212: { id: 212, name: '徐进弹幕', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 2, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 8, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 13, enhanceBuffId: 43, enhancePerStack: 30 },
  213: { id: 213, name: '绝命狙击', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 2, powerPercent: 100, energyCost: 4, cooldownMs: 16000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 13, enhanceBuffId: 43, enhancePerStack: 30 },
  214: { id: 214, name: '外科手术', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 6, powerPercent: 120, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 16 },
  215: { id: 215, name: '医疗小队', behavior: 'heal', targetSide: 'ally', route: 'internal', element: 6, powerPercent: 100, energyCost: 4, cooldownMs: 16000, hits: 1, rangeKind: 'all', rangeCount: 15, reach: 'ranged', skillCategory: 16 },
  216: { id: 216, name: '重返战场', behavior: 'revive', targetSide: 'ally', route: 'internal', element: 6, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 16 },
  217: { id: 217, name: '山姆梦', behavior: 'advance-gauge', targetSide: 'ally', route: 'support', element: 6, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 16 },
  218: { id: 218, name: '灯塔辉光', behavior: 'advance-gauge', targetSide: 'ally', route: 'support', element: 6, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 16 },
  219: { id: 219, name: '星条荣耀', behavior: 'advance-gauge', targetSide: 'ally', route: 'support', element: 6, powerPercent: 100, energyCost: 5, cooldownMs: 20000, hits: 1, rangeKind: 'all', rangeCount: 15, reach: 'ranged', skillCategory: 16 },
  220: { id: 220, name: '玄冰碎', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 2, powerPercent: 90, energyCost: 1, cooldownMs: 4000, hits: 3, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 4, appliedBuffId: 44, appliedBuffChance: 0.5, appliedBuffStacks: 1 },
  221: { id: 221, name: '寒星爆', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 2, powerPercent: 90, energyCost: 2, cooldownMs: 8000, hits: 3, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 4, appliedBuffId: 44, appliedBuffChance: 0.5, appliedBuffStacks: 1 },
  222: { id: 222, name: '霜刃风暴', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 2, powerPercent: 90, energyCost: 4, cooldownMs: 16000, hits: 4, rangeKind: 'all', rangeCount: 15, reach: 'melee', skillCategory: 4, appliedBuffId: 44, appliedBuffChance: 0.5, appliedBuffStacks: 1 },
  223: { id: 223, name: '玲珑心', behavior: 'status', targetSide: 'ally', route: 'support', element: 2, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 4, appliedBuffId: 9, appliedBuffChance: 1, appliedBuffStacks: 1 },
  224: { id: 224, name: '冰灵心法', behavior: 'status', targetSide: 'ally', route: 'support', element: 2, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 4, appliedBuffId: 6, appliedBuffChance: 1, appliedBuffStacks: 1 },
  225: { id: 225, name: '寒域疯魔阵', behavior: 'status', targetSide: 'ally', route: 'support', element: 2, powerPercent: 100, energyCost: 4, cooldownMs: 16000, hits: 1, rangeKind: 'all', rangeCount: 15, reach: 'ranged', skillCategory: 4, appliedBuffId: 9, appliedBuffChance: 1, appliedBuffStacks: 1 },
  226: { id: 226, name: '紫霄雷击', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 1, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 3, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 12, appliedBuffId: 46, appliedBuffChance: 1, appliedBuffStacks: 3 },
  227: { id: 227, name: '天罡雷暴', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 1, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 4, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 12, appliedBuffId: 46, appliedBuffChance: 1, appliedBuffStacks: 6 },
  228: { id: 228, name: '雷狱天罚', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 1, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 5, rangeKind: 'spread', rangeCount: 9, reach: 'melee', skillCategory: 12, appliedBuffId: 46, appliedBuffChance: 1, appliedBuffStacks: 9 },
  229: { id: 229, name: '九霄雷动', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 1, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 6, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 12, enhanceBuffId: 46, enhancePerStack: 10 },
  230: { id: 230, name: '锐芒诀', behavior: 'status', targetSide: 'ally', route: 'support', element: 1, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 12, appliedBuffId: 34, appliedBuffChance: 1, appliedBuffStacks: 1 },
  231: { id: 231, name: '混沌雷劫爆', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 1, powerPercent: 100, energyCost: 4, cooldownMs: 16000, hits: 8, rangeKind: 'all', rangeCount: 15, reach: 'melee', skillCategory: 12, enhanceBuffId: 46, enhancePerStack: 10 },
  232: { id: 232, name: '长生斩', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 4, powerPercent: 90, energyCost: 1, cooldownMs: 4000, hits: 3, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 7 },
  233: { id: 233, name: '穿星刺', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 4, powerPercent: 90, energyCost: 2, cooldownMs: 8000, hits: 4, rangeKind: 'spread', rangeCount: 3, reach: 'melee', skillCategory: 7 },
  235: { id: 235, name: '灵木刀', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 4, powerPercent: 90, energyCost: 2, cooldownMs: 8000, hits: 6, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 7 },
  236: { id: 236, name: '汲血刃', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 4, powerPercent: 90, energyCost: 3, cooldownMs: 12000, hits: 2, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 7, enhanceBuffId: 47, enhancePerStack: 10 },
  237: { id: 237, name: '苍生不朽功', behavior: 'status', targetSide: 'ally', route: 'support', element: 4, powerPercent: 100, energyCost: 4, cooldownMs: 16000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 7, appliedBuffId: 48, appliedBuffChance: 1, appliedBuffStacks: 1 },
  238: { id: 238, name: '能量护盾充能', behavior: 'shield', targetSide: 'ally', route: 'internal', element: 1, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 14 },
  239: { id: 239, name: '近战姿态', behavior: 'status', targetSide: 'ally', route: 'support', element: 1, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 14, appliedBuffId: 50, appliedBuffChance: 1, appliedBuffStacks: 1 },
  240: { id: 240, name: '震荡波冲击', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 1, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 5, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 14 },
  241: { id: 241, name: '热能导弹风暴', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 1, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 5, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 14 },
  242: { id: 242, name: '远程姿态', behavior: 'status', targetSide: 'ally', route: 'support', element: 1, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 14, appliedBuffId: 49, appliedBuffChance: 1, appliedBuffStacks: 1 },
  243: { id: 243, name: '离子炮齐射', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 1, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 4, rangeKind: 'all', rangeCount: 15, reach: 'melee', skillCategory: 14 },
  244: { id: 244, name: '原力突刺', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 3, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 7 },
  245: { id: 245, name: '光剑连击', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 3, rangeKind: 'spread', rangeCount: 3, reach: 'melee', skillCategory: 7 },
  246: { id: 246, name: '原力激发', behavior: 'status', targetSide: 'ally', route: 'support', element: 3, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 7, appliedBuffId: 51, appliedBuffChance: 1, appliedBuffStacks: 5 },
  247: { id: 247, name: '光剑旋风斩', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 5, rangeKind: 'spread', rangeCount: 9, reach: 'melee', skillCategory: 7, enhanceBuffId: 51, enhancePerStack: 20 },
  249: { id: 249, name: '激光乱舞', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 100, energyCost: 5, cooldownMs: 20000, hits: 6, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 7, enhanceBuffId: 51, enhancePerStack: 20 },
  250: { id: 250, name: '战术分析', behavior: 'status', targetSide: 'ally', route: 'support', element: 8, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 13, appliedBuffId: 53, appliedBuffChance: 1, appliedBuffStacks: 1 },
  251: { id: 251, name: '离子狙击', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 8, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 5, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 13, appliedBuffId: 52, appliedBuffChance: 1, appliedBuffStacks: 1 },
  253: { id: 253, name: '爆能枪', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 8, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 3, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 13, enhanceBuffId: 52, enhancePerStack: 35 },
  255: { id: 255, name: '死星粒子炮', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 8, powerPercent: 100, energyCost: 5, cooldownMs: 20000, hits: 7, rangeKind: 'all', rangeCount: 15, reach: 'melee', skillCategory: 13, enhanceBuffId: 52, enhancePerStack: 35 },
  258: { id: 258, name: '斗气愈灵阵', behavior: 'grant-energy', targetSide: 'ally', route: 'internal', element: 2, powerPercent: 100, energyCost: 4, cooldownMs: 16000, hits: 1, rangeKind: 'all', rangeCount: 15, reach: 'ranged', skillCategory: 16 },
  259: { id: 259, name: '灵源诀', behavior: 'grant-energy', targetSide: 'ally', route: 'support', element: 2, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 16 },
  261: { id: 261, name: '落云回天阵', behavior: 'grant-energy', targetSide: 'ally', route: 'support', element: 2, powerPercent: 100, energyCost: 4, cooldownMs: 16000, hits: 1, rangeKind: 'all', rangeCount: 15, reach: 'ranged', skillCategory: 16 },
  263: { id: 263, name: '腐灵毒雾', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 4, powerPercent: 80, energyCost: 2, cooldownMs: 8000, hits: 3, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 12, appliedBuffId: 3, appliedBuffChance: 1, appliedBuffStacks: 1 },
  265: { id: 265, name: '毒蚀术', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 4, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 3, rangeKind: 'single', rangeCount: 1, reach: 'melee', skillCategory: 12, enhanceBuffId: 3, enhancePerStack: 20 },
  267: { id: 267, name: '万毒归宗', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 4, powerPercent: 100, energyCost: 4, cooldownMs: 16000, hits: 5, rangeKind: 'all', rangeCount: 15, reach: 'melee', skillCategory: 12, enhanceBuffId: 3, enhancePerStack: 20 },
  269: { id: 269, name: '炎龙破空击', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 120, energyCost: 3, cooldownMs: 12000, hits: 4, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 9 },
  270: { id: 270, name: '炽炎爆裂拳', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 120, energyCost: 5, cooldownMs: 20000, hits: 8, rangeKind: 'all', rangeCount: 15, reach: 'melee', skillCategory: 9 },
  271: { id: 271, name: '炎狱斗气阵', behavior: 'status', targetSide: 'ally', route: 'support', element: 3, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 9, appliedBuffId: 54, appliedBuffChance: 1, appliedBuffStacks: 1 },
  272: { id: 272, name: '炎爆斗气波', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 120, energyCost: 2, cooldownMs: 8000, hits: 3, rangeKind: 'spread', rangeCount: 3, reach: 'melee', skillCategory: 9 },
  273: { id: 273, name: '火凤翔天击', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 3, powerPercent: 120, energyCost: 4, cooldownMs: 16000, hits: 5, rangeKind: 'spread', rangeCount: 9, reach: 'melee', skillCategory: 9 },
  275: { id: 275, name: '灰烬新星', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 3, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 4, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 11 },
  276: { id: 276, name: '炎魔之握', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 3, powerPercent: 100, energyCost: 4, cooldownMs: 16000, hits: 5, rangeKind: 'all', rangeCount: 15, reach: 'melee', skillCategory: 11 },
  279: { id: 279, name: '海妖之怒', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 2, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 5, rangeKind: 'all', rangeCount: 15, reach: 'melee', skillCategory: 11 },
  280: { id: 280, name: '圣光之誓', behavior: 'shield', targetSide: 'ally', route: 'internal', element: 7, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'self', rangeCount: 1, reach: 'ranged', skillCategory: 8 },
  284: { id: 284, name: '殉道者之佑', behavior: 'status', targetSide: 'ally', route: 'support', element: 7, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 1, rangeKind: 'spread', rangeCount: 6, reach: 'ranged', skillCategory: 8, appliedBuffId: 57, appliedBuffChance: 1, appliedBuffStacks: 3 },
  287: { id: 287, name: '怨灵聚合', behavior: 'summon', targetSide: 'ally', route: 'internal', element: 8, powerPercent: 100, energyCost: 2, cooldownMs: 8000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 15, summonId: 5 },
  288: { id: 288, name: '憎恶召唤', behavior: 'summon', targetSide: 'ally', route: 'internal', element: 8, powerPercent: 100, energyCost: 4, cooldownMs: 16000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 15, summonId: 6 },
  289: { id: 289, name: '森林之灵', behavior: 'summon', targetSide: 'ally', route: 'internal', element: 4, powerPercent: 100, energyCost: 1, cooldownMs: 4000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 15, summonId: 7 },
  291: { id: 291, name: '梦境觉醒', behavior: 'summon', targetSide: 'ally', route: 'internal', element: 4, powerPercent: 100, energyCost: 5, cooldownMs: 20000, hits: 1, rangeKind: 'single', rangeCount: 1, reach: 'ranged', skillCategory: 15, summonId: 9 },
  292: { id: 292, name: '尸爪', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 8, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 3, rangeKind: 'spread', rangeCount: 3, reach: 'melee', skillCategory: 15 },
  293: { id: 293, name: '操纵', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 8, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 8, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 15 },
  294: { id: 294, name: '锁链击', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 8, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 1, rangeKind: 'spread', rangeCount: 11, reach: 'melee', skillCategory: 15 },
  297: { id: 297, name: '翡翠龙炎', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 4, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 6, rangeKind: 'all', rangeCount: 15, reach: 'melee', skillCategory: 15 },
  299: { id: 299, name: '潮汐之力', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 2, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 5, rangeKind: 'spread', rangeCount: 9, reach: 'melee', skillCategory: 1 },
  301: { id: 301, name: '自然之毒', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 4, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 3, rangeKind: 'spread', rangeCount: 9, reach: 'melee', skillCategory: 1 },
  302: { id: 302, name: '山河崩', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 5, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 3, rangeKind: 'spread', rangeCount: 9, reach: 'melee', skillCategory: 1 },
  303: { id: 303, name: '无限月读', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 6, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 5, rangeKind: 'spread', rangeCount: 9, reach: 'melee', skillCategory: 1 },
  304: { id: 304, name: '龙息', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 7, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 6, rangeKind: 'spread', rangeCount: 9, reach: 'melee', skillCategory: 1 },
  305: { id: 305, name: '暗夜冥击', behavior: 'attack', targetSide: 'enemy', route: 'internal', element: 8, powerPercent: 100, energyCost: 3, cooldownMs: 12000, hits: 5, rangeKind: 'spread', rangeCount: 9, reach: 'melee', skillCategory: 1 },
  306: { id: 306, name: '虎爪', behavior: 'attack', targetSide: 'enemy', route: 'external', element: 1, powerPercent: 100, energyCost: 0, cooldownMs: 0, hits: 3, rangeKind: 'spread', rangeCount: 5, reach: 'melee', skillCategory: 1 },
}

export const skillById = (id: number): CombatSkillContent | undefined => COMBAT_SKILLS[id]

export interface SummonUnitContent {
  /** 原版 zh 表 id，立绘文件 zt_s{id}.webp */
  id: number
  name: string
  /** 六维系数（生命/物攻/物防/法防/法攻/速度，%），乘施法者面板 */
  coeffs: readonly [number, number, number, number, number, number]
  durationMs: number
  route: 'external' | 'internal'
}

export const SUMMON_UNITS: Readonly<Record<number, SummonUnitContent>> = {
  1: { id: 1, name: '孤魂', coeffs: [120, 90, 120, 110, 90, 120], durationMs: 30000, route: 'external' },
  2: { id: 2, name: '野鬼', coeffs: [100, 120, 80, 100, 120, 110], durationMs: 30000, route: 'internal' },
  3: { id: 3, name: '孟婆', coeffs: [130, 110, 100, 120, 110, 110], durationMs: 30000, route: 'external' },
  4: { id: 4, name: '食尸鬼', coeffs: [130, 115, 130, 110, 70, 100], durationMs: 30000, route: 'external' },
  5: { id: 5, name: '怨灵', coeffs: [120, 100, 140, 90, 100, 130], durationMs: 30000, route: 'external' },
  6: { id: 6, name: '憎恶', coeffs: [200, 90, 150, 130, 80, 120], durationMs: 30000, route: 'external' },
  7: { id: 7, name: '妖精', coeffs: [110, 130, 80, 90, 125, 120], durationMs: 30000, route: 'internal' },
  8: { id: 8, name: '古树', coeffs: [150, 80, 105, 110, 140, 140], durationMs: 30000, route: 'internal' },
  9: { id: 9, name: '翡翠龙', coeffs: [170, 110, 110, 140, 170, 130], durationMs: 30000, route: 'internal' },
}

export const summonById = (id: number): SummonUnitContent | undefined => SUMMON_UNITS[id]

// 职业（zy 行号）→ 普攻技能 id
export const BASE_SKILL_BY_ZY: Readonly<Record<number, number>> = {
  1: 1,
  2: 2,
  3: 3,
  4: 4,
  5: 5,
  6: 6,
  7: 7,
  8: 8,
  9: 9,
  10: 10,
  11: 11,
  12: 12,
  13: 13,
  14: 14,
  15: 15,
  16: 16,
  17: 17,
  18: 18,
  19: 19,
  20: 20,
  21: 21,
  22: 22,
  23: 23,
  24: 24,
  25: 25,
  26: 26,
  27: 27,
  28: 28,
  29: 29,
  30: 30,
  31: 31,
  32: 32,
  33: 33,
  34: 34,
  35: 35,
  36: 36,
  37: 37,
  38: 38,
  39: 39,
  40: 40,
  41: 41,
}
