import type { HeroDefinition, MartialDefinition } from './types'

export const HEROES: readonly HeroDefinition[] = [
  {
    id: 'lu_qingshan',
    name: '陆青山',
    epithet: '断浪掌',
    sect: '丐帮',
    element: '火',
    style: '刚',
    description: '掌势开阔，愈战愈勇，是队伍最可靠的破阵者。',
    baseAttack: 18,
    baseDefense: 8,
    baseHp: 112,
    recruitCost: 0,
    initial: true,
  },
  {
    id: 'shen_zhaoxue',
    name: '沈照雪',
    epithet: '寒江医剑',
    sect: '峨眉',
    element: '水',
    style: '柔',
    description: '剑路绵密，善以柔劲化开强攻，持久战尤为稳健。',
    baseAttack: 13,
    baseDefense: 12,
    baseHp: 102,
    recruitCost: 0,
    initial: true,
  },
  {
    id: 'gu_changfeng',
    name: '顾长风',
    epithet: '松间客',
    sect: '武当',
    element: '木',
    style: '柔',
    description: '以静制动，真气悠长，擅长拆解敌手的攻势。',
    baseAttack: 14,
    baseDefense: 13,
    baseHp: 108,
    recruitCost: 0,
    initial: true,
  },
  {
    id: 'yan_qiusheng',
    name: '燕秋声',
    epithet: '铁衣行',
    sect: '丐帮',
    element: '金',
    style: '刚',
    description: '棍影如墙，既能护住同袍，也能一击震退强敌。',
    baseAttack: 17,
    baseDefense: 11,
    baseHp: 122,
    recruitCost: 220,
    initial: false,
  },
  {
    id: 'ning_suyin',
    name: '宁素音',
    epithet: '素心琴',
    sect: '峨眉',
    element: '土',
    style: '柔',
    description: '以琴音运气，招式看似轻缓，实则后劲层叠。',
    baseAttack: 15,
    baseDefense: 14,
    baseHp: 104,
    recruitCost: 260,
    initial: false,
  },
  {
    id: 'jiang_wan',
    name: '江晚',
    epithet: '照影剑',
    sect: '武当',
    element: '水',
    style: '刚',
    description: '剑势似晚潮回卷，与陆青山同队可施展「山河照影」。',
    baseAttack: 20,
    baseDefense: 9,
    baseHp: 108,
    recruitCost: 360,
    initial: false,
  },
  {
    id: 'qi_rumo',
    name: '祁如墨',
    epithet: '醉里乾坤',
    sect: '丐帮',
    element: '土',
    style: '柔',
    description: '步法歪斜难测，能在险境中卸去大半来势。',
    baseAttack: 18,
    baseDefense: 14,
    baseHp: 116,
    recruitCost: 520,
    initial: false,
  },
  {
    id: 'bai_weishuang',
    name: '白微霜',
    epithet: '惊鸿刺',
    sect: '峨眉',
    element: '金',
    style: '刚',
    description: '以峨眉短刺行雷霆之势，专破久守不出的强敌。',
    baseAttack: 23,
    baseDefense: 10,
    baseHp: 101,
    recruitCost: 680,
    initial: false,
  },
  {
    id: 'zhou_xuanyi',
    name: '周玄一',
    epithet: '赤霞真人',
    sect: '武当',
    element: '火',
    style: '柔',
    description: '真气如霞，攻守循环不息，是武当后期阵容的中枢。',
    baseAttack: 24,
    baseDefense: 15,
    baseHp: 120,
    recruitCost: 900,
    initial: false,
  },
] as const

export const MARTIALS: readonly MartialDefinition[] = [
  {
    id: 'dragon_palm',
    name: '沧浪降龙掌',
    element: '火',
    style: '刚',
    description: '以炽烈内劲催掌，攻势一浪高过一浪。',
    basePower: 1.18,
    unlockCost: 0,
    initial: true,
    rankNames: ['起势', '翻江', '断岳'],
  },
  {
    id: 'frost_sword',
    name: '凝霜十三剑',
    element: '水',
    style: '柔',
    description: '剑气如霜，连绵细密，以巧劲寻找破绽。',
    basePower: 1.14,
    unlockCost: 0,
    initial: true,
    rankNames: ['听雪', '封江', '寒彻'],
  },
  {
    id: 'taiji_breath',
    name: '太极吐纳法',
    element: '木',
    style: '柔',
    description: '生生不息的武当心法，攻守均衡，根基最稳。',
    basePower: 1.12,
    unlockCost: 0,
    initial: true,
    rankNames: ['抱元', '化劲', '归一'],
  },
  {
    id: 'vajra_staff',
    name: '金刚伏魔棍',
    element: '金',
    style: '刚',
    description: '棍沉如铁，专破护体真气与坚甲。',
    basePower: 1.24,
    unlockCost: 48,
    initial: false,
    rankNames: ['横江', '镇恶', '伏魔'],
  },
  {
    id: 'earth_origin',
    name: '厚土归元功',
    element: '土',
    style: '柔',
    description: '气沉丹田，厚积薄发，适合长线鏖战。',
    basePower: 1.2,
    unlockCost: 68,
    initial: false,
    rankNames: ['立桩', '承山', '归元'],
  },
] as const

export const COMBO = {
  id: 'mountain_river_reflection',
  name: '山河照影',
  heroIds: ['lu_qingshan', 'jiang_wan'] as const,
  description: '陆青山掌力开山，江晚剑光照影，对敌造成一次强力合击。',
  multiplier: 1.72,
}

export const IDLE_LOCATION = {
  id: 'bluestone_path',
  name: '青石古道',
  description: '山雨初歇，商旅与流寇都沿这条古道往来。适合初入江湖者积累阅历。',
  rewardText: '银两 · 阅历 · 秘籍残页',
}

export const ENEMY_NAMES = ['剪径悍匪', '黑风寨哨探', '负伤刀客', '拦路恶霸', '蒙面剑手'] as const

export const heroById = (id: string) => HEROES.find((hero) => hero.id === id)
export const martialById = (id: string) => MARTIALS.find((martial) => martial.id === id)
