import type {
  BondDefinition,
  ComboDefinition,
  EnemyTraitDefinition,
  EnemyTraitId,
  HeroDefinition,
  MartialDefinition,
  RegionDefinition,
  RegionId,
} from './types'

export const HEROES: readonly HeroDefinition[] = [
  {
    id: 'lu_qingshan',
    name: '陆青山',
    epithet: '断浪掌',
    sect: '丐帮',
    element: '火',
    style: '刚',
    description: '掌势开阔，愈战愈勇，是队伍最可靠的破阵者。',
    baseAttack: 18,
    baseDefense: 8,
    baseHp: 112,
    recruitCost: 0,
    initial: true,
  },
  {
    id: 'shen_zhaoxue',
    name: '沈照雪',
    epithet: '寒江医剑',
    sect: '峨眉',
    element: '水',
    style: '柔',
    description: '剑路绵密，善以柔劲化开强攻，持久战尤为稳健。',
    baseAttack: 13,
    baseDefense: 12,
    baseHp: 102,
    recruitCost: 0,
    initial: true,
  },
  {
    id: 'gu_changfeng',
    name: '顾长风',
    epithet: '松间客',
    sect: '武当',
    element: '木',
    style: '柔',
    description: '以静制动，真气悠长，擅长拆解敌手的攻势。',
    baseAttack: 14,
    baseDefense: 13,
    baseHp: 108,
    recruitCost: 0,
    initial: true,
  },
  {
    id: 'yan_qiusheng',
    name: '燕秋声',
    epithet: '铁衣行',
    sect: '丐帮',
    element: '金',
    style: '刚',
    description: '棍影如墙，既能护住同袍，也能一击震退强敌。',
    baseAttack: 17,
    baseDefense: 11,
    baseHp: 122,
    recruitCost: 220,
    initial: false,
  },
  {
    id: 'ning_suyin',
    name: '宁素音',
    epithet: '素心琴',
    sect: '峨眉',
    element: '土',
    style: '柔',
    description: '以琴音运气，招式看似轻缓，实则后劲层叠。',
    baseAttack: 15,
    baseDefense: 14,
    baseHp: 104,
    recruitCost: 260,
    initial: false,
  },
  {
    id: 'jiang_wan',
    name: '江晚',
    epithet: '照影剑',
    sect: '武当',
    element: '水',
    style: '刚',
    description: '剑势似晚潮回卷，与陆青山同队可施展「山河照影」。',
    baseAttack: 20,
    baseDefense: 9,
    baseHp: 108,
    recruitCost: 360,
    initial: false,
  },
  {
    id: 'qi_rumo',
    name: '祁如墨',
    epithet: '醉里乾坤',
    sect: '丐帮',
    element: '土',
    style: '柔',
    description: '步法歪斜难测，能在险境中卸去大半来势。',
    baseAttack: 18,
    baseDefense: 14,
    baseHp: 116,
    recruitCost: 520,
    initial: false,
  },
  {
    id: 'bai_weishuang',
    name: '白微霜',
    epithet: '惊鸿刺',
    sect: '峨眉',
    element: '金',
    style: '刚',
    description: '以峨眉短刺行雷霆之势，专破久守不出的强敌。',
    baseAttack: 23,
    baseDefense: 10,
    baseHp: 101,
    recruitCost: 680,
    initial: false,
  },
  {
    id: 'zhou_xuanyi',
    name: '周玄一',
    epithet: '赤霞真人',
    sect: '武当',
    element: '火',
    style: '柔',
    description: '真气如霞，攻守循环不息，是武当后期阵容的中枢。',
    baseAttack: 24,
    baseDefense: 15,
    baseHp: 120,
    recruitCost: 900,
    initial: false,
  },
] as const

export const MARTIALS: readonly MartialDefinition[] = [
  {
    id: 'dragon_palm',
    name: '沧浪降龙掌',
    element: '火',
    style: '刚',
    description: '以炽烈内劲催掌，攻势一浪高过一浪。',
    basePower: 1.18,
    unlockCost: 0,
    initial: true,
    rankNames: ['起势', '翻江', '断岳'],
    skill: {
      kind: 'blazing_palm',
      name: '赤浪断岳',
      description: '重掌造成高额伤害，并施加持续 2 回合的灼伤。',
      cooldown: 2,
    },
  },
  {
    id: 'frost_sword',
    name: '凝霜十三剑',
    element: '水',
    style: '柔',
    description: '剑气如霜，连绵细密，以巧劲寻找破绽。',
    basePower: 1.14,
    unlockCost: 0,
    initial: true,
    rankNames: ['听雪', '封江', '寒彻'],
    skill: {
      kind: 'frost_flurry',
      name: '寒江听雪',
      description: '连续两剑追击，并使敌人迟滞 2 回合，降低反击伤害。',
      cooldown: 2,
    },
  },
  {
    id: 'taiji_breath',
    name: '太极吐纳法',
    element: '木',
    style: '柔',
    description: '生生不息的武当心法，攻守均衡，根基最稳。',
    basePower: 1.12,
    unlockCost: 0,
    initial: true,
    rankNames: ['抱元', '化劲', '归一'],
    skill: {
      kind: 'taiji_restore',
      name: '抱元守一',
      description: '以柔劲伤敌，同时治疗气血最低的同伴并为其护体。',
      cooldown: 3,
    },
  },
  {
    id: 'vajra_staff',
    name: '金刚伏魔棍',
    element: '金',
    style: '刚',
    description: '棍沉如铁，专破护体真气与坚甲。',
    basePower: 1.24,
    unlockCost: 48,
    initial: false,
    rankNames: ['横江', '镇恶', '伏魔'],
    skill: {
      kind: 'vajra_sunder',
      name: '金刚镇恶',
      description: '以重棍震裂敌人护体，使其 2 回合内承受更多伤害。',
      cooldown: 2,
    },
  },
  {
    id: 'earth_origin',
    name: '厚土归元功',
    element: '土',
    style: '柔',
    description: '气沉丹田，厚积薄发，适合长线鏖战。',
    basePower: 1.2,
    unlockCost: 68,
    initial: false,
    rankNames: ['立桩', '承山', '归元'],
    skill: {
      kind: 'earth_guard',
      name: '厚土承山',
      description: '稳守反击，并为全队生成可吸收伤害的护体真气。',
      cooldown: 3,
    },
  },
] as const

export const BONDS: readonly BondDefinition[] = [
  {
    id: 'green_hill_iron_oath',
    name: '青山铁衣',
    type: '结义',
    heroIds: ['lu_qingshan', 'yan_qiusheng'],
    story: '古道血战后，陆青山与燕秋声以残酒盟誓，约定同进同退。',
    effectText: '二人同队时，全队受到伤害降低 10%。',
    effect: { type: 'damage_reduction', value: 0.1 },
  },
  {
    id: 'snow_qin_confidants',
    name: '雪照素心',
    type: '知音',
    heroIds: ['shen_zhaoxue', 'ning_suyin'],
    story: '医剑与琴音在寒江相和，沈照雪终于遇见能听懂剑意的人。',
    effectText: '二人同队时，所有治疗与回复效果提高 35%。',
    effect: { type: 'healing', value: 0.35 },
  },
  {
    id: 'wudang_inheritance',
    name: '归一传薪',
    type: '师徒',
    heroIds: ['gu_changfeng', 'zhou_xuanyi'],
    story: '顾长风守住松间旧诺，周玄一则将赤霞心诀倾囊相授。',
    effectText: '二人同队时，武学招式冷却减少 1 次行动。',
    effect: { type: 'skill_haste', value: 1 },
  },
  {
    id: 'evening_frost_rivals',
    name: '晚霜争锋',
    type: '宿敌',
    heroIds: ['jiang_wan', 'bai_weishuang'],
    story: '一剑如晚潮，一刺若惊鸿；二人谁也不肯承认对方更快。',
    effectText: '二人同队时，全队造成伤害提高 15%。',
    effect: { type: 'attack', value: 0.15 },
  },
  {
    id: 'drunken_road_companions',
    name: '醉掌同途',
    type: '同道',
    heroIds: ['lu_qingshan', 'qi_rumo'],
    story: '一个掌势堂皇，一个步法颠倒，却都愿为不平事多管一回。',
    effectText: '二人同队时，全队造成伤害提高 8%。',
    effect: { type: 'attack', value: 0.08 },
  },
] as const

export const COMBOS: readonly ComboDefinition[] = [
  {
    id: 'mountain_river_reflection',
    name: '山河照影',
    heroIds: ['lu_qingshan', 'jiang_wan'],
    description: '陆青山掌力开山，江晚剑光照影，对敌造成一次强力合击。',
    multiplier: 1.72,
    effect: 'damage',
    effectValue: 0,
  },
  {
    id: 'cold_river_harmony',
    name: '寒江和鸣',
    heroIds: ['shen_zhaoxue', 'ning_suyin'],
    description: '寒江剑意随素心琴音流转，攻敌之余调和全队气血。',
    multiplier: 1.28,
    effect: 'restore',
    effectValue: 0.34,
  },
  {
    id: 'true_wudang_duality',
    name: '真武两仪',
    heroIds: ['gu_changfeng', 'zhou_xuanyi'],
    description: '松风与赤霞交汇成两仪护阵，合击后护住全队。',
    multiplier: 1.38,
    effect: 'guard',
    effectValue: 0.3,
  },
  {
    id: 'twin_blades_resonance',
    name: '双锋争鸣',
    heroIds: ['jiang_wan', 'bai_weishuang'],
    description: '剑刺争锋化作同一瞬的寒芒，撕开敌手护体。',
    multiplier: 1.55,
    effect: 'sunder',
    effectValue: 0.24,
  },
] as const

export const ENEMY_TRAITS: Record<EnemyTraitId, EnemyTraitDefinition> = {
  none: {
    id: 'none',
    name: '寻常身手',
    description: '没有额外战斗规则，以基础攻防检验队伍实力。',
    counterHint: '稳步提升侠客、武学和羁绊即可应对。',
  },
  formation_breaker: {
    id: 'formation_breaker',
    name: '破阵重击',
    description: '仅有一名前排存活时，反击伤害提高 45%；两名前排存活时，反击伤害降低 20%。',
    counterHint: '使用两前一后的「磐石阵」，让两名侠客共同稳住前排。',
  },
  iron_armor: {
    id: 'iron_armor',
    name: '黑铁重甲',
    description: '正面强攻只能造成 65% 伤害；后排侠客可攻击甲胄薄弱处，造成 125% 伤害。',
    counterHint: '改用一前两后的「雁行阵」，把主力输出放在后排。',
  },
  frost_aura: {
    id: 'frost_aura',
    name: '寒罡护体',
    description: '非火系武学只能造成 72% 伤害；火系武学可融解寒罡，造成 155% 伤害。',
    counterHint: '让主力改习火系「沧浪降龙掌」，以火劲破开寒罡。',
  },
}

export const REGIONS: readonly RegionDefinition[] = [
  {
    id: 'bluestone_path',
    name: '青石古道',
    description: '山雨初歇，商旅与流寇都沿这条古道往来。适合初入江湖者积累根基。',
    rewardText: '均衡产出 · 银两与阅历',
    rewardMultipliers: { silver: 1, experience: 1, pages: 1 },
    requiredBossId: null,
    enemies: [
      { id: 'road_bandit', name: '剪径悍匪', traitId: 'none', baseHp: 72, baseAttack: 13 },
      { id: 'stone_fist_brute', name: '断碑恶徒', traitId: 'formation_breaker', baseHp: 86, baseAttack: 15 },
    ],
    boss: {
      id: 'boss_stonebreaker',
      name: '断碑手 · 罗震',
      traitId: 'formation_breaker',
      baseHp: 420,
      baseAttack: 32,
      rewards: { silver: 90, experience: 70, pages: 6, reputation: 8 },
    },
  },
  {
    id: 'blackwind_fort',
    name: '黑风寨',
    description: '寨墙依山而筑，披甲悍匪扼守险道。此地阅历丰厚，却会压制正面强攻。',
    rewardText: '阅历专精 · 残页略增',
    rewardMultipliers: { silver: 0.8, experience: 1.55, pages: 1.2 },
    requiredBossId: 'boss_stonebreaker',
    enemies: [
      { id: 'armored_raider', name: '披甲寨兵', traitId: 'iron_armor', baseHp: 152, baseAttack: 23 },
      { id: 'blackwind_scout', name: '黑风寨哨探', traitId: 'none', baseHp: 132, baseAttack: 27 },
    ],
    boss: {
      id: 'boss_blackwind_chief',
      name: '黑风寨主 · 裘霸',
      traitId: 'iron_armor',
      baseHp: 1_050,
      baseAttack: 50,
      rewards: { silver: 260, experience: 320, pages: 16, reputation: 24 },
    },
  },
  {
    id: 'frost_temple',
    name: '寒潭古寺',
    description: '古寺临潭，寒气终年不散。残卷散落其间，守寺高手以寒罡隔绝寻常劲力。',
    rewardText: '残页专精 · 高阶历练',
    rewardMultipliers: { silver: 0.7, experience: 1.15, pages: 2.5 },
    requiredBossId: 'boss_blackwind_chief',
    enemies: [
      { id: 'frost_monk', name: '寒潭武僧', traitId: 'frost_aura', baseHp: 248, baseAttack: 34 },
      { id: 'temple_swordsman', name: '古寺剑侍', traitId: 'none', baseHp: 220, baseAttack: 39 },
    ],
    boss: {
      id: 'boss_frost_arbiter',
      name: '寒潭判官 · 凌沧',
      traitId: 'frost_aura',
      baseHp: 1_900,
      baseAttack: 70,
      rewards: { silver: 520, experience: 620, pages: 36, reputation: 48 },
    },
  },
] as const

export const heroById = (id: string) => HEROES.find((hero) => hero.id === id)
export const martialById = (id: string) => MARTIALS.find((martial) => martial.id === id)
export const regionById = (id: string) => REGIONS.find((region) => region.id === id)
export const enemyTraitById = (id: EnemyTraitId) => ENEMY_TRAITS[id]
export const bossById = (id: string) => REGIONS.map((region) => region.boss).find((boss) => boss.id === id)
export const nextRegionAfter = (regionId: RegionId) => {
  const index = REGIONS.findIndex((region) => region.id === regionId)
  return index >= 0 ? REGIONS[index + 1] : undefined
}
